= Receiving Messages from Kafka

In this section, you are going to see how you can receive messages from a Kafka topic.
For this, you are going to create a new microservice, named `stats`.
This microservice computes statistics based on the results of the fights.
For example, it determines if villains win more battle than heroes, and who is the superhero or super-villain having won the most fights.

== Directory Structure

In this section, we are going to develop the following structure:

[plantuml]
--
@startsalt
{
{
T
super-heroes
+  event-statistics
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  statistics
++++++++++ Fight.java
++++++++++ FightDeserializer.java
++++++++++ Ranking.java
++++++++++ Score.java
++++++++++ SuperStats.java
++++++++++ TeamStats.java
++  pom.xml
}
}
@endsalt
--

== Bootstrapping the Statistics REST Endpoint

Like for the other microservice, the easiest way to create this new Quarkus project is to use a Maven command.
Under the `quarkus-workshop-super-heroes/super-heroes` root directory where you have all your code.

[example, role="cta"]
--

Open a terminal and run the following command:

[source,shell,subs="attributes+"]
----
./mvnw io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DplatformVersion={quarkus-version} \
    -DprojectGroupId=io.quarkus.workshop.super-heroes \
    -DprojectArtifactId=event-statistics \
    -DclassName="io.quarkus.workshop.superheroes.statistics.StatisticResource" \
    -Dpath="api/stats" \
    -Dextensions="kafka, rest-jackson, websockets"
----
--

If you want your IDE to manage this new Maven project, you can declare it in the parent POM by adding this new module in the `<modules>` section:

[source,xml]
----
<module>super-heroes/event-statistics</module>
----

[example, role="cta"]
--

Delete all the classes under the `io.quarkus.workshop.superheroes.statistics` package as well as the associated test classes.
There are just examples.
--

== Consuming Fight

[example, role="cta"]
--

This service receives the `Fight` from the fight microservice.
So, naturally, we need a fight class.

Create the `io.quarkus.workshop.superheroes.statistics.Fight` class with the following content:

[source,java]
----
include::{projectdir}/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/Fight.java[]
----

We also need to a deserializer that will receive the Kafka record and create the `Fight` instances.
Create the `io.quarkus.workshop.superheroes.statistics.FightDeserializer` class with the following content:

[source,java]
----
include::{projectdir}/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/FightDeserializer.java[]
----
--

== Computing Statistics

[example, role="cta"]
--
Now, create the `io.quarkus.workshop.superheroes.statistics.SuperStats` class with the following content.
This class contains two methods annotated with `@Incoming` and `@Outgoing`, both consuming the `Fight` coming from Kafka.

The `computeTeamStats` method transforms the fight stream into a stream of ratio indicating the amount of victories for heroes and villains.
It calls `onItem().transform` method for each received fight.
It sends the computed ratios on the channel `team-stats`.

The `computeTopWinners` method uses more advanced reactive programming constructs such as `group` and `scan`:

[source,java]
----
include::{projectdir}/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/SuperStats.java[tag=!adocJavadoc]
----
--

[example, role="cta"]
--

In addition, create the `io.quarkus.workshop.superheroes.statistics.Ranking`, `io.quarkus.workshop.superheroes.statistics.Score` and `io.quarkus.workshop.superheroes.statistics.TeamStats` classes with the following contents:


Then, create the `Ranking` class, used to compute a floating top 10, with the following content:

[source,java]
----
include::{projectdir}/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/Ranking.java[tag=!adocJavadoc]
----
--
The `Score` class is a simple structure storing the name of a hero or villain and its actual score, _i.e._ the number of won battles.

[source,java]
----
include::{projectdir}/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/Score.java[tag=!adocJavadoc]
----

The `TeamStats` class is an object keeping track of the number of battles won by heroes and villains.

[source,java]
----
include::{projectdir}/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/TeamStats.java[tag=!adocJavadoc]
----

[TIP]
====
The `@RegisterForReflection` annotation instructs the native compilation to allow reflection access to the class.
Without, the serialization/deserialization would not work when running the native executable.
====

== Reading Messages from Kafka

It's now time to connect the `fights` channel with the Kafka topic.

[example, role="cta"]
--
Edit the `application.properties` file and add the following content:

[source,properties]
----
include::{projectdir}/event-statistics/src/main/resources/application.properties[]
----
--

As for the writing side, it configures the Kafka connector.
The `mp.messaging.incoming.fights.auto.offset.reset=earliest` property indicates that the topic is read from the earliest available record.
Check the Kafka configuration to see all the available settings.

