[[kubernetes]]
= Kubernetes

'''

This chapter explores how you can deploy containerized Quarkus applications in Cloud platforms using Kubernetes.
There are many different approaches to achieve these deployments.
In this chapter, we are focusing on deploying our containers in Kubernetes.

== Deploying on Kubernetes

This section is going to deploy our microservices on Kubernetes.
It is required to have access to a Kubernetes or OpenShift cluster.

[IMPORTANT]
====
To deploy your microservices, push the built container images to an image registry accessible by your cluster, such as Quay.io or DockerHub.
====

We recommend using a specific namespace to deploy your system.
In the following sections, we use the `quarkus-workshop` namespace.

=== Deploying the infrastructure

The first thing to deploy is the required infrastructure:

* 3 PostgreSQL instances
* Kafka brokers (3 brokers with 3 Zookeeper to follow the recommended approach)

There are many ways to deploy this infrastructure.
Here, we are going to use two operators:

* PostgreSQL Operator by Dev4Ddevs.com
* Strimzi Apache Kafka Operator by Red Hat

[example, role="cta"]
--

With these operators installed, you can create the required infrastructure with the following custom resource definition (CRD):

[source,yaml]
----
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
    name: heroes-database
    namespace: quarkus-workshop
spec:
    databaseCpu: 30m
    databaseCpuLimit: 60m
    databaseMemoryLimit: 512Mi
    databaseMemoryRequest: 128Mi
    databaseName: heroes-database
    databaseNameKeyEnvVar: POSTGRESQL_DATABASE
    databasePassword: superman
    databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
    databaseStorageRequest: 1Gi
    databaseUser: superman
    databaseUserKeyEnvVar: POSTGRESQL_USER
    image: centos/postgresql-96-centos7
    size: 1
----
--

[example, role="cta"]
--

This CRD creates the database for the Hero microservice.
Duplicate this CRD for the fight and villain databases.

For the Kafka broker, create the following CRD:

[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-kafka
  namespace: quarkus-workshop
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.3'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
----
--

This CRD creates the brokers and the Zookeeper instances.

It's also recommended to create the topic.

[example, role="cta"]
--

For this, create the following CRD:

[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: fights
  labels:
    strimzi.io/cluster: my-kafka
  namespace: quarkus-workshop
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
----

Once everything is created, you should have the following resources:

[source,shell]
----
$ kubectl get database
NAME                AGE
fights-database     16h
heroes-database     16h
villains-database   16h

$ kubectl get kafka
NAME       DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS
my-kafka   3
----
--

=== Deploying the Hero & Villain microservices

Now that the infrastructure is in place, we can deploy our microservices.
Let's start with the hero and villain microservices.

For each, we need to override the port and data source URL.

[example, role="cta"]
--

Create a config map with the following content:

[source,yaml]
.config-hero.yaml
----
apiVersion: v1
data:
    port: "8080"
    database: "jdbc:postgresql://heroes-database:5432/heroes-database"
kind: ConfigMap
metadata:
    name: hero-config
----
--

[example, role="cta"]
--

Do the same for the villain microservice.
Then, apply these resources:

[source,shell]
----
$ kubectl apply -f config-hero.yaml
$ kubectl apply -f config-villain.yaml
----
--

Once the config maps are created, we can deploy the microservices.

[example, role="cta"]
--

Create a `deployment-hero.yaml` file with the following content:

[source,yaml]
----
apiVersion: "v1"
kind: "List"
items:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
          labels:
              app: "quarkus-workshop-hero"
              version: "01"
              group: "$ORG"
          name: "quarkus-workshop-hero"
      spec:
          ports:
              - name: "http"
                port: 8080
                targetPort: 8080
          selector:
              app: "quarkus-workshop-hero"
              version: "01"
              group: "$ORG"
          type: "ClusterIP"
    - apiVersion: "apps/v1"
      kind: "Deployment"
      metadata:
          labels:
              app: "quarkus-workshop-hero"
              version: "01"
              group: "$ORG"
          name: "quarkus-workshop-hero"
      spec:
          replicas: 1
          selector:
              matchLabels:
                  app: "quarkus-workshop-hero"
                  version: "01"
                  group: "$ORG"
          template:
              metadata:
                  labels:
                      app: "quarkus-workshop-hero"
                      version: "01"
                      group: "$ORG"
              spec:
                  containers:
                      - image: "$ORG/quarkus-workshop-hero:latest"
                        imagePullPolicy: "IfNotPresent"
                        name: "quarkus-workshop-hero"
                        ports:
                            - containerPort: 8080
                              name: "http"
                              protocol: "TCP"
                        env:
                            - name: "KUBERNETES_NAMESPACE"
                              valueFrom:
                                  fieldRef:
                                      fieldPath: "metadata.namespace"

                            - name: QUARKUS_DATASOURCE_URL
                              valueFrom:
                                  configMapKeyRef:
                                      name: hero-config
                                      key: database

                            - name: QUARKUS_HTTP_PORT
                              valueFrom:
                                  configMapKeyRef:
                                      name: hero-config
                                      key: port


----
--

This descriptor declares:

1. A service to expose the HTTP endpoint
2. A deployment that instantiates the application

The deployment declares one container using the container image we built earlier.
It also overrides the configuration for the HTTP port and database URL.

[example, role="cta"]
--
Don't forget to create the equivalent files for the villain microservice.

Then, deploy the microservice with:

[source,shell]
----
$ kubectl apply -f deployment-hero.yaml
$ kubectl apply -f deployment-villain.yaml
----
--

=== Deploying the Fight microservice

Follow the same approach for the fight microservice.
Note that there are more properties to configure from the config map:

* The location of the hero and villain microservice
* The location of the Kafka broker

Once everything is configured and deployed, your system is now running on Kubernetes.
























= From Container to Kubernetes

[NOTE]
====
This section is optional and demonstrates how to ask Quarkus to create a container and deploy it to Kubernetes.
We will need a running Kubernetes.
We will use Rancher Desktop as indicated in the prerequisites.
====

== Prerequisites

1. Make sure that Docker Desktop (if installed) is turned off
2. Make sure Rancher Desktop is started. The container runtime must be _dockerd_ (Preferences -> Container Runtime -> dockerd (moby)).

== Deploying to Kubernetes

Quarkus can also run our application in Kubernetes and compute the Kubernetes descriptor.
In addition to allow customizing any part of the descriptor, it is possible to configure config maps, secrets...

[IMPORTANT]
====
As mentioned above, we will use Rancher Desktop.
Adapt the instructions for your Kubernetes:

1. Make sure you are logged in
2. Make sure you use the correct namespace
====

[example, role="cta"]
--

Edit the `src/main/resources/application.properties` to add the following lines:

[source, properties]
----
quarkus.kubernetes.namespace=default # Added
quarkus.kubernetes.image-pull-policy=IfNotPresent # Added

%prod.quarkus.http.port=8080 # Added
%prod.quarkus.datasource.username=superbad
%prod.quarkus.datasource.password=superbad
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://my-villains-db-postgresql:5432/villains_database # Updated
%prod.quarkus.hibernate-orm.sql-load-script=import.sql
----

Add the `quarkus-kubernetes` extension using the following command:

[source, shell]
----
./mvnw quarkus:add-extension -Dextensions="kubernetes"
----
--

TIP: If you are behind a proxy, check the https://quarkus.io/guides/extension-registry-user#how-to-register-as-a-nexus-repository-proxy[Quarkus Registry] proxy documentation.

Alternatively, you can add the following dependency to the `pom.xml` file directly:

[source, xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-kubernetes</artifactId>
</dependency>
----

Rancher Desktop authentication use elliptic algorithms not supported by default in Java.
So, we also need to add the following dependency to the project:

[source, xml]
----
<dependency>
  <groupId>org.bouncycastle</groupId>
  <artifactId>bcpkix-jdk18on</artifactId>
  <version>1.71</version>
</dependency>
----

Before deploying our application, we need to deploy the database.
To achieve this, we are going to use https://helm.sh/[helm] (installed alongside Rancher Desktop) and the following https://artifacthub.io/packages/helm/bitnami/postgresql[postgresql package].

Run the following commands:
[source, shell]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-villains-db \
    --set auth.postgresPassword=superbad \
    --set auth.username=superbad \
    --set auth.password=superbad \
    --set auth.database=villains_database bitnami/postgresql
----

Finally, deploy the application using:

[source, shell]
----
./mvnw clean package -Dquarkus.kubernetes.deploy=true -DskipTests
----

Check the pods with the following command:

[source, shell]
----
kubectl get pods
----

You should see something like:

[source, shell]
----
NAME                             READY   STATUS    RESTARTS   AGE
my-villains-db-postgresql-0      1/1     Running   0          28m
rest-villains-7c7479b959-7fn64   1/1     Running   0          12m
----

Make sure you wait for the `rest-villains` pod to be ready (1/1).

Enable port-forwarding to port 8080 either from the rancher desktop UI (Preferences -> Port Forwarding -> default / rest-villains / http), or using the following command line:

[source, shell]
----
kubectl port-forward pods/rest-villains-7c7479b959-7fn64 8080:8080
----

Now, you can access the application from your browser using: http://localhost:8080/api/villains
