= Sending Messages to Kafka

In this section, you are going to see how you can send messages to a Kafka topic.footnote:[Kafka Topic https://kafka.apache.org/intro#intro_topics]

== Directory Structure

In this section we are going to extend the **Fight microservice**.
In the following tree, we are going to edit the marked classes

[plantuml]
----
@startsalt
{
{
T
super-heroes
+  rest-fight
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  fight
++++++++++  Fight.java
++++++++++  FightResource.java
++++++++++  FightService.java <--
++++++++++  Fighters.java
+++++++++++ client
++++++++++++ Hero.java
++++++++++++ HeroProxy.java
++++++++++++ Villain.java
++++++++++++ VillainProxy.java
+++++++++++ kafka
++++++++++++ KafkaWriter.java <--
++  pom.xml
}
}
@endsalt
----

== Adding the Reactive Messaging Dependency

[example, role="cta"]
--

The Kafka extension was already imported during the project creation.
In doubt, you can run in the Fight microservice:

[source,shell]
----
./mvnw quarkus:add-extension -Dextensions=" io.quarkus:quarkus-smallrye-reactive-messaging-kafka"
----
--

The previous command adds the following dependency:

[source,xml,indent=0]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
</dependency>
----

If not yet started, start the microservice using `./mvnw quarkus:dev`.

[NOTE]
====
Quarkus starts a Kafka broker automatically.
====

// TODO HERE

== Connecting Imperative and Reactive Using an Emitter

[example, role="cta"]
--

Now edit the `FightService` class.
First, add the following field:

[source,indent=0]
----
@Channel("fights") Emitter<Fight> emitter;
----
--

[NOTE]
====
You will also need to add the following imports:
```
import org.eclipse.microprofile.reactive.messaging.Channel;
import org.eclipse.microprofile.reactive.messaging.Emitter;
```
====

This field is an _emitter_, and lets you send events or messages (here, we are sending fights) to the _channel_ specified with the `@Channel` annotation.
A _channel_ is a _virtual_ destination.

In the `persistFight` method, add the following line just before the `return` statement:

[source,indent=0]
----
emitter.send(fight).toCompletableFuture().join();
----

With this in place, every time the application persists a `fight`, it also sends the `fight` to the `fights` _channel_.
You may wonder why we need `.toCompletableFuture().join()`.
Sending a message to Kafka is an asynchronous operation, and we need to be sure that the fight is not accessed outside the transaction.
Thus, we wait until Kafka confirms the reception before returning.

== Connecting to Kafka

At this point, the serialized fights are sent to the `fights` channel.
You need to connect this `channel` to a Kafka topic.

[example, role="cta"]
--
For this, edit the `application.properties` file and add the following properties:

[source,properties]
----
mp.messaging.outgoing.fights.connector=smallrye-kafka
mp.messaging.outgoing.fights.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
----
--

These properties are structured as follows:

[source,properties]
----
mp.messaging.[incoming|outgoing].channel.attribute=value
----

For example, `mp.messaging.outgoing.fights.connector` configures the connector used for the `outgoing` channel `fights`.

The `mp.messaging.outgoing.fights.value.serializer` configures the serializer used to write the message in Kafka.
When omitted, the Kafka topic reuses the channel name (`fights`).

Now, you have connected the fight microservice to Kafka, and you are sending new fights to the Kafka topic.
Let's see how you can read these messages in the `stats` microservice.
