= Receiving Messages from Kafka

In this section, you are going to see how you can receive messages from a Kafka topic.
For this, you are going to create a new microservice, named `stats`.
This microservice computes statistics based on the results of the fights.
For example, it determines if villains win more battle than heroes, and who is the superhero or super-villain having won the most fights.

== Directory Structure

In this section, we are going to develop the following structure:

[plantuml]
--
@startsalt
{
{
T
super-heroes
+  event-statistics
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  statistics
++++++++++ Fight.java
++++++++++ FightDeserializer.java
++++++++++ Ranking.java
++++++++++ Score.java
++++++++++ SuperStats.java
++++++++++ TeamStats.java
++  pom.xml
}
}
@endsalt
--

== Bootstrapping the Statistics REST Endpoint

Like for the other microservice, the easiest way to create this new Quarkus project is to use a Maven command.
Under the `quarkus-workshop-super-heroes/super-heroes` root directory where you have all your code.

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

Open a terminal and run the following command:

[source,shell,subs="attributes+"]
----
mvn io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=io.quarkus.workshop.super-heroes \
    -DprojectArtifactId=event-statistics \
    -DclassName="io.quarkus.workshop.superheroes.statistics.StatisticResource" \
    -Dpath="api/stats" \
    -Dextensions="kafka, resteasy-reactive-jackson, websockets"
----

If you want your IDE to manage this new Maven project, you can declare it in the parent POM by adding this new module in the `<modules>` section:

[source,xml]
----
<module>super-heroes/event-statistics</module>
----

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

Delete all the classes under the `io.quarkus.workshop.superheroes.statistics` package as well as the associated test classes.
There are just examples.

== Consuming Fight

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

This service receives the `Fight` from the fight microservice.
So, naturally, we need a fight class.

Create the `io.quarkus.workshop.superheroes.statistics.Fight` class with the following content:

[source,java]
----
package io.quarkus.workshop.superheroes.statistics;

import java.time.Instant;


public class Fight {

    public Instant fightDate;
    public String winnerName;
    public int winnerLevel;
    public String winnerPicture;
    public String loserName;
    public int loserLevel;
    public String loserPicture;
    public String winnerTeam;
    public String loserTeam;
}
----

We also need to a deserializer that will receive the Kafka record and create the `Fight` instances.
Create the `io.quarkus.workshop.superheroes.statistics.FightDeserializer` class with the following content:

[source,java]
----
package io.quarkus.workshop.superheroes.statistics;

import io.quarkus.kafka.client.serialization.ObjectMapperDeserializer;

public class FightDeserializer extends ObjectMapperDeserializer<Fight> {

    public FightDeserializer() {
        super(Fight.class);
    }
}
----

== Computing Statistics

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

Now, create the `io.quarkus.workshop.superheroes.statistics.SuperStats` class with the following content.
This class contains two methods annotated with `@Incoming` and `@Outgoing`, both consuming the `Fight` coming from Kafka.

The `computeTeamStats` method transforms the fight stream into a stream of ratio indicating the amount of victories for heroes and villains.
It calls `onItem().transform` method for each received fight.
It sends the computed ratios on the channel `team-stats`.

The `computeTopWinners` method uses more advanced reactive programming constructs such as `group` and `scan`:

[source,java]
----
package io.quarkus.workshop.superheroes.statistics;

import io.smallrye.mutiny.Multi;
import org.eclipse.microprofile.reactive.messaging.Incoming;
import org.eclipse.microprofile.reactive.messaging.Outgoing;
import org.jboss.logging.Logger;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

@ApplicationScoped
public class SuperStats {

    @Inject
    Logger logger;

    private final Ranking topWinners = new Ranking(10);
    private final TeamStats stats = new TeamStats();

    @Incoming("fights")
    @Outgoing("team-stats")
    public Multi<Double> computeTeamStats(Multi<Fight> results) {
        return results
            .onItem().transform(stats::add)
            .invoke(() -> logger.info("Fight received. Computed the team statistics"));
    }

    @Incoming("fights")
    @Outgoing("winner-stats")
    public Multi<Iterable<Score>> computeTopWinners(Multi<Fight> results) {
        return results
            .group().by(fight -> fight.winnerName)
            .onItem().transformToMultiAndMerge(group ->
                group
                    .onItem().scan(Score::new, this::incrementScore))
            .onItem().transform(topWinners::onNewScore)
            .invoke(() -> logger.info("Fight received. Computed the top winners"));
    }

    private Score incrementScore(Score score, Fight fight) {
        score.name = fight.winnerName;
        score.score = score.score + 1;
        return score;
    }

}
----

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

In addition, create the `io.quarkus.workshop.superheroes.statistics.Ranking`, `io.quarkus.workshop.superheroes.statistics.Score` and `io.quarkus.workshop.superheroes.statistics.TeamStats` classes with the following contents:


Then, create the `Ranking` class, used to compute a floating top 10, with the following content:

[source,java]
----
package io.quarkus.workshop.superheroes.statistics;

import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;

public class Ranking {

    private final int max;

    private final Comparator<Score> comparator = Comparator.comparingInt(s -> -1 * s.score);

    private final LinkedList<Score> top = new LinkedList<>();

    public Ranking(int size) {
        max = size;
    }

    public Iterable<Score> onNewScore(Score score) {
        // Remove score if already present,
        top.removeIf(s -> s.name.equalsIgnoreCase(score.name));
        // Add the score
        top.add(score);
        // Sort
        top.sort(comparator);

        // Drop on overflow
        if (top.size() > max) {
            top.remove(top.getLast());
        }

        return Collections.unmodifiableList(top);
    }
}
----

The `Score` class is a simple structure storing the name of a hero or villain and its actual score, _i.e._ the number of won battles.

[source,java]
----
package io.quarkus.workshop.superheroes.statistics;

import io.quarkus.runtime.annotations.RegisterForReflection;

@RegisterForReflection
public class Score {
    public String name;
    public int score;

    public Score() {
        this.score = 0;
    }
}
----

The `TeamStats` class is an object keeping track of the number of battles won by heroes and villains.

[source,java]
----
package io.quarkus.workshop.superheroes.statistics;

class TeamStats {

    private int villains = 0;
    private int heroes = 0;

    double add(Fight result) {
        if (result.winnerTeam.equalsIgnoreCase("heroes")) {
            heroes = heroes + 1;
        } else {
            villains = villains + 1;
        }
        return ((double) heroes / (heroes + villains));
    }

}
----

[TIP]
====
The `@RegisterForReflection` annotation instructs the native compilation to allow reflection access to the class.
Without, the serialization/deserialization would not work when running the native executable.
====

== Reading Messages from Kafka

It's now time to connect the `fights` channel with the Kafka topic.

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

Edit the `application.properties` file and add the following content:

[source,properties]
----
quarkus.http.port=8085

## Kafka configuration
mp.messaging.incoming.fights.connector=smallrye-kafka
mp.messaging.incoming.fights.auto.offset.reset=earliest
mp.messaging.incoming.fights.broadcast=true
----

As for the writing side, it configures the Kafka connector.
The `mp.messaging.incoming.fights.auto.offset.reset=earliest` property indicates that the topic is read from the earliest available record.
Check the Kafka configuration to see all the available settings.

