= Workshop Super Heroes

== Generate the documentation

You can either generate the documentation for each exercise or for the entire workshop.
For that, you just run the Maven command `mvn clean generate-resources` under an `docs` directory.

== Start the infrastructure

This workshop requires a couple of extra _technical_ services (databases, kafka...).
Start them using the `docker-compose.yaml` file located in the `containers` directory:

```
cd containers
docker-compose up
```

Stop them using:

```
CTRL+C
docker-compose down
docker-compose rm
```

== Build

```bash
mvn clean install -f pom-extensions.xml
mvn clean install
```

== Running the full system

* Run the infrastructure as explained above.
* In a new terminal, run the heroes microservice
```bash
cd api-hero
mvn clean compile quarkus:dev
```
* In a new terminal, run the villains microservice
```bash
cd api-villain
mvn clean compile quarkus:dev
```
* In a new terminal, run the fights microservice
```bash
cd api-fight
mvn clean compile quarkus:dev
```

== Ports

* heroes microservice -> 8083
* villains microservice -> 8084
* fights microservice -> 8082, ui on http://localhost:8082/super-heroes
* stats microservice -> 8085

== References

* https://github.com/cescoffier/quarkus-todo-app
* https://github.com/agoncal/baking-microservice-pie
* https://forge.jboss.org/document/hands-on-lab
* https://bit.ly/forge-hol
