= Workshop Super Heroes

== Instructions

Check https://quarkus.io/quarkus-workshops/super-heros/ to get the workshop instructions.

== Generate the documentation

You can either generate the documentation for each exercise or for the entire workshop.
For that, you just run the Maven command `mvn clean generate-resources` under the `docs` directory.
You can then open the `docs/target/generated-asciidoc/spine.html` page and read the entire documentation of the workshop.

== Generate the zip files

To generate the zip files, execute the following command from the root of the project:

```bash
$ mvn assembly:single -N
```

This generates the following zip files

* `dist/quarkus-super-heroes-workshop.zip`: contains the bare minimum code to follow up the workshop
* `dist/quarkus-super-heroes-workshop-complete.zip`: contains all the code (useful if you get lost or want to jump a section of the workshop)

== Start the infrastructure

This workshop requires a couple of extra _technical_ services (databases, kafka...).
Start them using the `docker-compose.yaml` file located in the `infrastructure` directory:

```
$ cd infrastructure
$ docker compose up
```

Stop them using:

```
CTRL+C
$ docker compose down
$ docker compose rm
```

== Build

To build the entire code, you need to activate the `complete` profile:

```bash
$ mvn clean install -Pcomplete

```

== Running the complete system

* Run the infrastructure and build the complete system as explained above.
* In a new terminal, run the heroes microservice
```bash
$ cd rest-heroes
$ mvn clean compile quarkus:dev
```
* In a new terminal, run the villains microservice
```bash
$ cd rest-villains
$ mvn clean compile quarkus:dev
```
* In a new terminal, run the fights microservice
```bash
$ cd rest-fights
$ mvn clean compile quarkus:dev
```
* In a new terminal, run the fights microservice
```bash
$ cd event-statistics
$ mvn clean compile quarkus:dev
```

== Ports

* heroes microservice -> 8083
* villains microservice -> 8084
* fights microservice -> 8082
* ui -> http://localhost:8080
* stats microservice -> 8085, ui on http://localhost:8085/
* Prometheus -> 9090

== References

* https://github.com/cescoffier/quarkus-todo-app
* https://github.com/agoncal/baking-microservice-pie
* https://forge.jboss.org/document/hands-on-lab
* https://bit.ly/forge-hol
