
= Consumer tests

Pact is a consumer-driven contract testing framework,
which means that we begin by writing tests for the API consumer.

== Writing the first contract test

[example, role="cta"]
--

Add the Pact Quarkus extension to the `pom.xml` of the Fights service:

[source,xml,subs="attributes+"]
----
        <dependency>
            <groupId>io.quarkiverse.pact</groupId>
            <artifactId>quarkus-pact-consumer</artifactId>
            <version>{quarkus-pact-version}</version>
            <scope>test</scope>
        </dependency>
----
--

The Pact framework will stand up a server which listens on a port.
To avoid port conflicts between the real services and the Pact stubs, let's use a different port for the contract instances.
Open the fight service's `application.properties` and add the following

----
%test.io.quarkus.workshop.superheroes.fight.client.HeroProxy/mp-rest/url=http://localhost:8093
----

The `%test` scopes the updated property to only apply in the test mode.

We will be using the https://docs.pact.io/implementation_guides/jvm/consumer/junit5[junit 5 pact libraries].

Create a class called `FightResourceConsumerTest.java`.

[source,java]
----
include::../../../../../super-heroes/rest-fights/src/test/java/io/quarkus/workshop/superheroes/fight/FightResourceConsumerTest.java[tags=skeleton]
}
----

Here we are setting up a test to run with Pact and telling Pact what ports it should stand up the mock server on.
We also define how the mock should behave.

[WARNING]
Because of the complexities of Kotlin classloading, Pact does not work with continuous testing.
This limitation is resolved with Quarkus 3 and 1.x versions of the Pact extension.

You will need to run tests the old-fashioned way, with

[source,bash]
----
./mvnw verify
----


Run the build (using `./mvnw verify`).
You should see a failure, because we have a mock, but nothing is using it.


Add in a test method.
You'll notice this is very similar to the one in `FightResourceTest`; you could even copy and paste from that class.

[source,java]
----
include::../../../../../super-heroes/rest-fights/src/test/java/io/quarkus/workshop/superheroes/fight/FightResourceConsumerTest.java[tags=randomHeroFound]
----

Run the tests.
They should all pass.

Note that we're only setting up contracts for heroes here. If we were to make contracts for getting villains, the test would fail. Can you think why that might be?

[TIP]
When we use Pact, the Pact framework stands up a server which acts as a mock.
Remember that we defined a global `@Mock` for the `VillainProxy`.
Because `@Mocks` are global, that mock would be used instead of the Pact mock service we want the class under test to be talking to.
This is an example of why a local `@InjectMock` is often preferable to a global `@Mock`.

== The contract
Look in `target/pacts`.
You should find a json contract, `rest-fights-rest-heroes.json`.
Inspect it to see how the contents of the `@Pact` method have been turned into json.

What we want to be testing when we use Pact in our tests is the behaviour of our own code.
Here, although we check the value of the hero fields, we're trying to make sure that the *fights service* is doing the right thing.
Our expectation for the fights service is pretty low: it just has to pass through what it gets from the heroes service.

[WARNING]
This test is just on the edge of falling into a common Pact anti-pattern, testing the mock.
We do *not* need to do detailed validation of what comes back from the pact server, because it's a mock that we define.

A more interesting contract test would exercise some of the more complex fights functionality, while using the mock we've defined.
Can you write one?
(You might also need to define a villain pact.)

If you get stuck, you can look at the consumer contract tests in the https://github.com/quarkusio/quarkus-super-heroes[Quarkus Superheroes sample]
for inspiration. Have a look at https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-fights/src/test/java/io/quarkus/sample/superheroes/fight/service/FightServiceConsumerContractTests.java[FightServiceConsumerContractTests.java].
The code in that application is similar to this workshop, but not exactly the same.

