[[contract-testing]]
= Contract testing

'''

Let's look at where we've done so far.
We have been doing some (some) test-driven development, we have several microservices, and they're even talking to each other.
We have fault tolerance for when services go down.

Clearly, we have an invincible application.
Right?
Right?

In your IDE, have a look to see how many instances of a class called `Hero` you have.
There should be two.
This is by design; one for the consumer of the service, and one for the provider.

The two classes are different, with the provider class having a lot more code in it.
However, the fields in the two classes should be roughly the same.

What happens if we do some refactoring?

icon:hand-point-right[role="red",size=2x] [red big]#Call to action#

In the `rest-heroes` project, let's do some searching and replacing.
(We do search and replace so we catch both Java and SQL in our refactoring.)
Change "level" to "maturity".
Make sure to only do search within the rest-heroes directory.
(Normally this project would be in its own repository, but we've grouped everything together into one repository for convenience.)

Check all of your tests.
The heroes, villains, and fights tests should all be running clean.
A successful refactoring!

Now visit the UI at http://localhost:4200/.
What's going on?
The hero's level is always 0. Why didn't the tests catch this?

Although we changed the provider of an API, no one told the consumer that the API had changed.
The unit tests were (correctly) isolated in scope, so they didn't catch the cross-service misunderstanding.

Feel free to reverse the change now, rather than patching up the service consumer.

This was a slightly contrived example, but uncaught API changes are a common cause of breaks, especially early in project development, before APIs have been locked down.
Tools like OpenAPI validation can catch syntax changes, but they will not catch semantic changes.
(What if we'd changed the level to be normalised against the best fighter, or count down from 100?)

This is where contract testing comes in.
Contract testing is a lightweight way of validating that a service's consumer and provider have the same understanding about what the service does.

There are several contract testing tools available.
The Red Hat App Development Consulting team have an https://appdev.consulting.redhat.com/tracks/contract-first/[excellent tutorial] describing contract first development and a polyglot OpenAPI-based stack for contract testing.

We will be using an all-in-one tool called https://docs.pact.io/[Pact], which is also polyglot, and enables consumer-driven contract testing.
The Pact team have https://pactflow.io/blog/contract-testing-using-json-schemas-and-open-api-part-1/[a good overview] of the advantages and disadvantages of schema-based testing (such as validation based on an OpenAPI spec) and consumer-driven contract testing.
