= States

One of the advantages of Pact over simpler contract verification methods, such as OpenAPI syntax-checking, is that a pact can include a range of expected responses, depending on what was passed in, and external state.

This allows for a richer set of checks.
For example, it can exercise more interesting logic on the consumer side, and it can act as a proper functional test for the provider.

Let's exercise some error-handling.
What happens if no heroes can be found?
In that case, we expect that the heroes server will return a 404. Let's get that into the contract, and exercise the fight service's error handling.

Add a new pact.
We use the `given()` to identify the state.
[source,java]

----
include::../../../../../super-heroes/rest-fights/src/test/java/io/quarkus/workshop/superheroes/fight/FightResourceConsumerTest.java[tags=randomHeroNotFoundPact]
----

Then, we can define another test method, which exercises our service, given this unhappy state.
If the hero service returns 404, we want to check that the fallback instances we defined earlier are used.
We also want to check that things work as normal for the villain part of the response.

[source,java]
----
include::../../../../../super-heroes/rest-fights/src/test/java/io/quarkus/workshop/superheroes/fight/FightResourceConsumerTest.java[tags=randomHeroNotFoundTest]
----

Run the tests. They should pass. Then copy them to the hero service, using `cp -r target/pacts ../rest-heroes/src/test/resources`.
In the hero service, the tests will fail, because we haven't told Pact how to handle the new state.

We would normally do that with a `@State` annotation.
However, for boring JUnit classloading reasons, we don't have access to the CDI context in the `@State` method,
so we'll work around it by handling the state in the `@BeforeEach`.

[source,java]
----
include::../../../../../super-heroes/rest-heroes/src/test/java/io/quarkus/workshop/superheroes/hero/HeroContractVerificationTest.java[tags=states]
}
----

What's going on?
The consumer expects a 404 if there are no heroes, but the provider is returning a 204.
The reasoning from the consumer is that if a caller asks for a resource the server doesn't have, it should be a 404, the same way if a user types in an invalid URL into the browser.
This is a more pure interpretation of REST than what was inplemented by the `HeroResource`.

There are arguments for both 404 (not found) and 204 (no content).
Feel free to debate with your neighbour about which you prefer – but it doesn't really matter which is correct.
What matters is that the provider and consumer had different preferences.
If the provider returns 204 rather than 404, the fallback logic on the provider (as implemented) is not triggered.
(You can try this out for yourself by changing the contract in the `FightResourceConsumerTest`.)

At this point, the consumer and provider need to have a conversation to decide whether the expectations or implementation should be updated.
To make the fallback logic simplest, we will update the provider.
Edit the `HeroResource` and update the `getRandomHere` method to explicitly handle the null case.


[source,java]
----
    @Operation(summary = "Returns a random hero")
    @GET
    @Path("/random")
    @APIResponse(responseCode = "200", content = @Content(mediaType = APPLICATION_JSON, schema = @Schema(implementation = Hero.class, required = true)))
    public Uni<Response> getRandomHero() {
        return Hero.findRandom()
            .onItem().ifNotNull().transform(h -> {
                this.logger.debugf("Found random hero: %s", h);
                return Response.ok(h).build();
            })
            .onItem().ifNull().continueWith(() -> {
                this.logger.debug("No random villain found");
                return Response.status(Response.Status.NOT_FOUND).build();
            });
    }
----

The tests should now pass.
