## HTTP configuration
quarkus.http.port=8086

## Custom banner file path
quarkus.banner.path=banner.txt

## CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*

## OpenAI configuration
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY:demo}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.openai.chat-model.temperature=0.9
quarkus.langchain4j.openai.timeout=30s
