@startuml
!include style.puml

left to right direction

node "Hero" as hero {
    agent "Quarkus (reactive)" <<application>> as heroQuarkus
    database "Postgresql" as heroPostgresql
    heroQuarkus .up> heroPostgresql
}

REST ()-- heroQuarkus

@enduml
