[[native]]
= Building Native Executables

'''

Let's now produce native executables for our application.
Thanks to its GraalVM integration, Quarkus can easily generate native executables.
Just like Go, native executables don't need a VM to run; they contain the whole application, like an `.exe` file on Windows.

== Building Native Executables with Quarkus

Having native executables for our microservices improves their startup time and produces a minimal disk footprint.
This can be a big plus if your microservices run in a serverless environment where scaling from zero is important.
The produced binary has everything to run the application, including the needed parts of the "JVM" (shrunk to be just enough to run the application), and the application itself.

[NOTE]
--
Choosing JVM execution vs. native executable execution depends on your application needs and environment. There are some trade-offs to consider.
--

To be able to build native executables, you need GraalVM to be installed.
And make sure you have the `GRAALVM_HOME` environment variable defined and pointing to where you installed GraalVM.
ifdef::use-maven[]
Then, if you look at all the `pom.xml` files, you will find the following profile.
This allows you to build a native executable just by invoking `./mvnw package -Pnative`.

[source,xml,indent=0]
----
include::{projectdir}/rest-heroes/pom.xml[tag=adocNative]
----
endif::use-maven[]
ifdef::use-gradle[]
With Gradle, building a native executable is done by passing `-Dquarkus.native.enabled=true` to the build command, e.g. `./gradlew build -Dquarkus.native.enabled=true`.
endif::use-gradle[]

== Building Native Executables for our Microservices

Let's create native executables for all our microservices.
Well, maybe not all of them.
Let's see.

[role="cta"]
====
ifdef::use-maven[]
From the root `super-heroes` directory, run the following commands (to speed up the compilation you can also skip the tests by adding `-Dmaven.test.skip=true`):

[source,shell]
----
./mvnw --file rest-fights/pom.xml package -Pnative
./mvnw --file rest-heroes/pom.xml package -Pnative
./mvnw --file rest-villains/pom.xml package -Pnative
./mvnw --file ui-super-heroes/pom.xml package -Pnative
ifdef::use-messaging[]
./mvnw --file event-statistics/pom.xml package -Pnative
endif::use-messaging[]
----
endif::use-maven[]
ifdef::use-gradle[]
From the root `super-heroes` directory, run the following commands (to speed up the compilation you can also skip the tests by adding `-x test`):

[source,shell]
----
./gradlew -p rest-fights build -Dquarkus.native.enabled=true
./gradlew -p rest-heroes build -Dquarkus.native.enabled=true
./gradlew -p rest-villains build -Dquarkus.native.enabled=true
./gradlew -p ui-super-heroes build -Dquarkus.native.enabled=true
ifdef::use-messaging[]
./gradlew -p event-statistics build -Dquarkus.native.enabled=true
endif::use-messaging[]
----
endif::use-gradle[]
====

[WARNING]
====
Creating a native executable requires a lot of memory and CPU.
It also takes a few minutes, even for a simple application like the Villain microservice.
Most of the time is spent during the dead code elimination, as it traverses the whole (closed) world.
====

During the compilation of each microservice, you see a lot of information about the native compilation.
Below is a summary of the output for that you will get.

[source,shell]
----
========================================================================================================================
GraalVM Native Image: Generating 'rest-heroes-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
[1/8] Initializing...                                                                                    (5.3s @ 0.28GB)
 Java version: 25.0.2+10, vendor version: GraalVM CE 25.0.2+10.1
 Graal compiler: optimization level: 2, target machine: armv8.1-a
 C compiler: cc (apple, arm64, 21.0.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 11 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature
 - io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
 - io.quarkus.hibernate.orm.runtime.graal.RegisterServicesForReflectionFeature: Makes methods of reachable Hibernate services accessible through Class#getMethods()
 - io.quarkus.hibernate.validator.runtime.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.hibernate.validator.internal.util.Version] categories
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Adapts logging during the analysis phase
 - io.quarkus.runtime.graal.JVMChecksFeature
 - io.quarkus.runtime.graal.SkipConsoleServiceProvidersFeature: Skip unsupported console service providers when quarkus.native.auto-service-loader-registration is false
 - org.eclipse.angus.activation.nativeimage.AngusActivationFeature
 - org.hibernate.graalvm.internal.GraalVMStaticFeature: Hibernate ORM's static reflection registrations for GraalVM
------------------------------------------------------------------------------------------------------------------------
 5 experimental option(s) unlocked:
 - '-H:+AllowFoldMethods' (origin(s): command line)
 - '-H:BuildOutputJSONFile' (origin(s): command line)
 - '-H:-UseServiceLoaderFeature' (origin(s): command line)
 - '-H:+GenerateBuildArtifactsFile' (origin(s): command line)
 - '-H:AddOpens' (alternative API option(s): --add-opens java.base/java.lang=ALL-UNNAMED; origin(s): command line)
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 25.68GB of memory (37.4% of system memory, using available memory)
 - 16 thread(s) (100.0% of 16 available processor(s), determined at start)
[2/8] Performing analysis...  [******]                                                                   (9.3s @ 2.60GB)
   23,519 types,  30,251 fields, and 105,346 methods found reachable
    7,460 types,     129 fields, and   6,950 methods registered for reflection
       63 types,      68 fields, and      55 methods registered for JNI access
        0 downcalls and 0 upcalls registered for foreign access
        5 native libraries: -framework CoreServices, -framework Foundation, dl, pthread, z
[3/8] Building universe...                                                                               (2.8s @ 2.55GB)
[4/8] Parsing methods...      [*]                                                                        (0.9s @ 2.78GB)
[5/8] Inlining methods...     [***]                                                                      (0.6s @ 2.96GB)
[6/8] Compiling methods...    [***]                                                                      (8.6s @ 2.10GB)
[7/8] Laying out methods...   [***]                                                                      (5.3s @ 2.81GB)
[8/8] Creating image...       [**]                                                                       (4.0s @ 3.17GB)
  39.70MB (46.41%) for code area:    69,386 compilation units
  44.83MB (52.39%) for image heap:  485,408 objects and 78 resources
   1.03MB ( 1.20%) for other data
  85.56MB in total image size, 85.56MB in total file size
----

ifdef::use-messaging[]
[NOTE]
====
Do you remember the `@RegisterForReflection` annotation that we used in the Statistics microservice?
Well, this annotation instructs the native compilation to allow reflection access to the class.
Without it, the serialization/deserialization would not work when running the native executable.
This information is required when running the application as a native executable.
====
endif::use-messaging[]

== Running the Application in Native mode

The native compilation takes a while.
ifdef::use-maven[]
In addition to the regular files, the build also produces `target/xxx-yyy-1.0.0-SNAPSHOT-runner` files.
endif::use-maven[]
ifdef::use-gradle[]
In addition to the regular files, the build also produces `build/xxx-yyy-1.0.0-SNAPSHOT-runner` files.
endif::use-gradle[]
Notice that there is no `.jar` file extension.
It's just a binary file that you can execute directly like any other binary.
Let's execute the entire application in native mode.

[role="cta"]
====
Native mode is using the `prod` profile, meaning that the infrastructure needs to be up and running (`docker compose -f docker-compose.yaml up -d`).
ifdef::use-maven[]
Then, from the root `super-heroes` directory, run the following commands (to speed up the compilation you can also skip the tests by adding `-Dmaven.test.skip=true`):

[source,shell]
----
./rest-fights/target/rest-fights-1.0.0-SNAPSHOT-runner
./rest-heroes/target/rest-heroes-1.0.0-SNAPSHOT-runner
./rest-villains/target/rest-villains-1.0.0-SNAPSHOT-runner
./ui-super-heroes/target/ui-super-heroes-1.0.0-SNAPSHOT-runner
ifdef::use-messaging[]
./event-statistics/target/event-statistics-1.0.0-SNAPSHOT-runner
endif::use-messaging[]
ifdef::use-ai[]
./rest-narration/target/quarkus-app/quarkus-run.jar
endif::use-ai[]
----
endif::use-maven[]
ifdef::use-gradle[]
Then, from the root `super-heroes` directory, run the following commands (to speed up the compilation you can also skip the tests by adding `-x test`):

[source,shell]
----
./rest-fights/build/rest-fights-1.0.0-SNAPSHOT-runner
./rest-heroes/build/rest-heroes-1.0.0-SNAPSHOT-runner
./rest-villains/build/rest-villains-1.0.0-SNAPSHOT-runner
./ui-super-heroes/build/ui-super-heroes-1.0.0-SNAPSHOT-runner
ifdef::use-messaging[]
./event-statistics/build/event-statistics-1.0.0-SNAPSHOT-runner
endif::use-messaging[]
ifdef::use-ai[]
./rest-narration/build/quarkus-app/quarkus-run.jar
endif::use-ai[]
----
endif::use-gradle[]

You can then go to http://localhost:8080 and start new fights.
====

// == Testing the Native Executables

// Producing a native executable can lead to a few issues, and so it’s also a good idea to run some tests against the application running in the native file. In the pom.xml file, the native profile contains:
//
// <plugin>
//   <artifactId>maven-failsafe-plugin</artifactId>
//   <version>${surefire-plugin.version}</version>
//   <executions>
//     <execution>
//       <goals>
//         <goal>integration-test</goal>
//         <goal>verify</goal>
//       </goals>
//       <configuration>
//         <systemProperties>
//           <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
//         </systemProperties>
//       </configuration>
//     </execution>
//   </executions>
// </plugin>
//
// This instructs the failsafe-maven-plugin to run integration-test and indicates the location of the produced native executable.
//
// Then, open the src/test/java/io/quarkus/workshop/superheroes/hero/NativeHeroResourceIT.java and update it with the following:
//
// Instead of using @QuarkusTest, it uses the @SubstrateTest test runner that starts the application from the native file before the tests. The executable is retrieved using the native.image.path system property configured in the Failsafe Maven Plugin. We extend our previous tests, but you can also implement your own tests.
//
// Notice that NativeHeroResourceIT does not extend HeroResourceTest. It is a good practice to share the same tests for native and JVM mode that way but in our case the behavior is a bit different. For example, we do not want Swagger UI exposed in our native image.
//
// Before running the test, we need to configure in which profile they run. If you look at the test class, it starts a database on a specific port (5499). We need to configure the application to connect on this port. For this edit the application.properties and add:
//
// The first line configure the profile to use in the native integration tests. Here we use a custom profile named it. Note that by default prod is used. The second line overrides the JDBC url to use the right port. Now we can run the tests.
//
// To see the NativeHeroResourceIT run against the native executable, use ./mvnw verify -Pnative:

