[[container]]
= Building Containers

'''

In this chapter we will build containers out of our Quarkus microservices and execute them locally thanks to Docker Compose.
Thanks to Quarkus Cloud Native capabilities, we will be able to build and execute containers easily.
ifdef::use-native[]
We will also produce Linux 64 bits native executables and runs them in a container.
The native compilation uses the OS and architecture of the host system.
endif::use-native[]

== Building Containers with Quarkus

ifdef::use-maven[]
When we bootstrapped our microservices with the Maven Quarkus plugin, a set of `Dockerfiles` have been generated under `src/main/docker`:
endif::use-maven[]
ifdef::use-gradle[]
When we bootstrapped our microservices with the Quarkus CLI, a set of `Dockerfiles` have been generated under `src/main/docker`:
endif::use-gradle[]

* `Dockerfile.jvm`: Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode.
* `Dockerfile.legacy-jar`: Deprecated Dockerfile building a container in JVM mode.
* `Dockerfile.native`: Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
* `Dockerfile.native-micro`: Same as above but it uses a micro base image, tuned for Quarkus native executables.

Quarkus is able to build a container image automatically.
The `quarkus-container-image-docker` extension is already included in our projects for this purpose.
It uses Docker and the generated `Dockerfiles` to build container images.

== Building Containers for our Microservices in JVM Mode

ifdef::use-maven[]
The `Dockerfile.jvm` file is for running the application in JVM mode.
It looks like this:

[source,text]
----
include::{projectdir}/rest-heroes/src/main/docker/Dockerfile.jvm[tag=adocSnippet]
----
endif::use-maven[]
ifdef::use-gradle[]
The `Dockerfile.jvm-gradle` file is for running the application in JVM mode.
It looks like this:

[source,text]
----
include::{projectdir}/rest-heroes/src/main/docker/Dockerfile.jvm-gradle[tag=adocSnippet]
----
endif::use-gradle[]

ifdef::use-gradle[]
By default, the `quarkus-container-image-docker` extension uses `Dockerfile.jvm` which references `target/` (Maven's output directory).
Since Gradle outputs to `build/`, we need to tell Quarkus to use `Dockerfile.jvm-gradle` instead.
Add the following line to the `gradle.properties` file of each microservice:

[source,properties]
----
quarkus.docker.dockerfile-jvm-path=src/main/docker/Dockerfile.jvm-gradle
----
endif::use-gradle[]

[example, role="cta"]
--
ifdef::use-maven[]
From the `super-heroes` directory, execute the following commands to build the applications and create the container images (add `-Dmaven.test.skip=true` if you want to skip the tests):
endif::use-maven[]
ifdef::use-gradle[]
From the `super-heroes` directory, execute the following commands to build the applications and create the container images (add `-x test` if you want to skip the tests):
endif::use-gradle[]
--

ifdef::use-maven[]
[.tab-maven]
--
[source, shell]
----
cd rest-fights
./mvnw clean package -Dquarkus.container-image.build=true
cd ..
cd rest-heroes
./mvnw clean package -Dquarkus.container-image.build=true
cd ..
cd rest-villains
./mvnw clean package -Dquarkus.container-image.build=true
cd ..
cd ui-super-heroes
./mvnw clean package -Dquarkus.container-image.build=true
cd ..
ifdef::use-messaging[]
cd event-statistics
./mvnw clean package -Dquarkus.container-image.build=true
cd ..
endif::use-messaging[]
ifdef::use-ai[]
cd rest-narration
./mvnw clean package -Dquarkus.container-image.build=true
cd ..
endif::use-ai[]
----
--
endif::use-maven[]
ifdef::use-gradle[]
[.tab-gradle]
--
[source, shell]
----
cd rest-fights
./gradlew clean build -Dquarkus.container-image.build=true
cd ..
cd rest-heroes
./gradlew clean build -Dquarkus.container-image.build=true
cd ..
cd rest-villains
./gradlew clean build -Dquarkus.container-image.build=true
cd ..
cd ui-super-heroes
./gradlew clean build -Dquarkus.container-image.build=true
cd ..
ifdef::use-messaging[]
cd event-statistics
./gradlew clean build -Dquarkus.container-image.build=true
cd ..
endif::use-messaging[]
ifdef::use-ai[]
cd rest-narration
./gradlew clean build -Dquarkus.container-image.build=true
cd ..
endif::use-ai[]
----
--
endif::use-gradle[]

[example, role="cta"]
--
Check that you have all the Docker images installed locally:

[source,shell]
----
docker image ls
----

The output should look like this:

[source,shell]
----
REPOSITORY                      TAG                  IMAGE ID       SIZE
<org>/rest-fights             1.0.0-SNAPSHOT       adb8a546a66b   419MB
<org>/rest-heroes             1.0.0-SNAPSHOT       d9e6ae6e3e23   402MB
<org>/rest-villains           1.0.0-SNAPSHOT       60a5c813f59a   402MB
<org>/ui-super-heroes         1.0.0-SNAPSHOT       82fce62c11a5   379MB
ifdef::use-messaging[]
<org>/event-statistics        1.0.0-SNAPSHOT       a5472c5bd576   395MB
endif::use-messaging[]
ifdef::use-ai[]
<org>/rest-narration          1.0.0-SNAPSHOT       fcfe334594f3   390MB
endif::use-ai[]
----
--

== Running JVM Mode Containers Locally

Now that we have all our Docker images created, let's execute them all to be sure that everything is working.

[example, role="cta"]
--
Under `super-heroes/infrastructure` you will find the `docker-compose-app-local.yaml` file.
It declares all the needed infrastructure (databases, Kafka) as well as our microservices.

[WARNING]
====
In the `docker-compose-app-local.yaml` file, you need to update the `image` property of each microservice to match the name of the image you just built.
For example, replace `quarkus/rest-villains` by `<org>/rest-villains` (<`org`> being your DockerHub / Quay.io username).
====

Execute it with:

[source,shell]
----
docker compose -f docker-compose-app-local.yaml up
----

To know that all your containers are started, you can use the following command:

[source,shell]
----
docker compose -f docker-compose-app-local.yaml ps
----

You should get something similar to the following list.
Make sure all your containers are in _running_ status:

[source,shell]
----
NAME               IMAGE                                         STATUS         PORTS
ui-super-heroes    agoncal<org/ui-super-heroes:1.0.0-SNAPSHOT    Up             0.0.0.0:8080->8080/tcp
rest-fights        agoncal<org/rest-fights:1.0.0-SNAPSHOT        Up             0.0.0.0:8082->8082/tcp
rest-heroes        agoncal<org/rest-heroes:1.0.0-SNAPSHOT        Up             0.0.0.0:8083->8083/tcp
rest-villains      agoncal<org/rest-villains:1.0.0-SNAPSHOT      Up             0.0.0.0:8084->8084/tcp
ifdef::use-messaging[]
event-statistics   agoncal<org/event-statistics:1.0.0-SNAPSHOT   Up             0.0.0.0:8085->8085/tcp
endif::use-messaging[]
ifdef::use-ai[]
rest-narration     agoncal<org/rest-narration:1.0.0-SNAPSHOT     Up             0.0.0.0:8086->8086/tcp
endif::use-ai[]
super-database     postgres:14                                   Up (healthy)   0.0.0.0:5432->5432/tcp
super-kafka        quay.io/strimzi/kafka:0.28.0-kafka-3.1.0      Up             0.0.0.0:9092->9092/tcp
----

Once all the containers are started, you can:

* Go to http://localhost:8080 to check the main UI
* Go to http://localhost:8085 to check the statistics UI
* curl http://localhost:8084/api/villains | jq
* curl http://localhost:8083/api/heroes | jq
* curl http://localhost:8082/api/fights/randomfighters | jq

Then, make sure you shut down the entire application with:

[source,shell]
----
docker compose -f docker-compose-app-local.yaml down
----
--

ifdef::use-native[]
== Building Containers for our Microservices in Native Mode


And... Linux Containers are ... _Linux_.
So before being able to build a container with our native executable, we need to produce compatible native executables.
If you are using a Linux 64 bits machine, you are good to go.
If not, Quarkus comes with a trick to produce these executable:

ifdef::use-maven[]
The `Dockerfile.native` file is for running the application in native mode.
It looks like this:

[source,text]
----
include::{projectdir}/rest-heroes/src/main/docker/Dockerfile.native[tag=adocSnippet]
----
endif::use-maven[]
ifdef::use-gradle[]
The `Dockerfile.native-gradle` file is for running the application in native mode.
It looks like this:

[source,text]
----
include::{projectdir}/rest-heroes/src/main/docker/Dockerfile.native-gradle[tag=adocSnippet]
----
endif::use-gradle[]

ifdef::use-maven[]
[.tab-maven]
--
[source,shell]
----
./mvnw clean package -Pnative -Dquarkus.native.container-build=true -DskipTests
----
--
endif::use-maven[]
ifdef::use-gradle[]
[.tab-gradle]
--
[source,shell]
----
./gradlew clean build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -x test
----
--
endif::use-gradle[]

The `-Dquarkus.native.container-build=true` allows running the native compilation inside a container (provided by Quarkus).

ifdef::use-mac[]
The result is a macOS 64-bit executable.
endif::use-mac[]
ifdef::use-linux[]
The result is a Linux 64-bit executable.
endif::use-linux[]
ifdef::use-windows[]
The result is a Windows 64-bit executable.
endif::use-windows[]

[TIP]
====
Building a native executable takes time, CPU, and memory.
It's even more accurate in the container.
So, first, be sure that your container system has enough memory to build the executable.
It requires at least 6Gb of memory, 8Gb is recommended.
====

[example, role="cta"]
--

Execute the above command for all our microservices.
We also copy the UI into the fight service, to simplify the process:
--

ifdef::use-maven[]
[.tab-maven]
--
[source,shell]
----
cd rest-heroes
./mvnw clean package -Pnative -Dquarkus.native.container-build=true -DskipTests
cd ..
cd rest-villains
./mvnw clean package -Pnative -Dquarkus.native.container-build=true -DskipTests
cd ..
cd rest-fights
cp -R ../ui-super-heroes/dist/* src/main/resources/META-INF/resources
./mvnw clean package -Pnative -Dquarkus.native.container-build=true -DskipTests
cd ..
cd event-statistics
./mvnw clean package -Pnative -Dquarkus.native.container-build=true -DskipTests
cd ..
----
--
endif::use-maven[]
ifdef::use-gradle[]
[.tab-gradle]
--
[source,shell]
----
cd rest-heroes
./gradlew clean build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -x test
cd ..
cd rest-villains
./gradlew clean build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -x test
cd ..
cd rest-fights
cp -R ../ui-super-heroes/dist/* src/main/resources/META-INF/resources
./gradlew clean build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -x test
cd ..
cd event-statistics
./gradlew clean build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -x test
cd ..
----
--
endif::use-gradle[]

== Building native containers

Now that we have the native executables, we can build containers.
When you create projects, Quarkus generates two `Dockerfiles`:

1. `Dockerfile.jvm` - A `Dockerfile` for running the application in JVM mode
2. `Dockerfile.native` - A `Dockerfile` for running the application in native mode

We are interested in this second file.
Open one of these `Dockerfile.native` files:

ifdef::use-maven[]
[.tab-maven]
--
[source,text]
----
include::{projectdir}/rest-heroes/src/main/docker/Dockerfile.native[tag=adocSnippet]
----
--
endif::use-maven[]
ifdef::use-gradle[]
[.tab-gradle]
--
[source,text]
----
include::{projectdir}/rest-heroes/src/main/docker/Dockerfile.native-gradle[tag=adocSnippet]
----
--
endif::use-gradle[]

It's a pretty straightforward `Dockerfile` taking a minimal base image and copying the generated native executable.
It also exposes the port 8080.
Wait, our microservices are not configured to run on the port 8080.
We need to override this property as well as a few other such as the HTTP client endpoints, and database locations.

To build the containers, use the following scripts:

ifdef::use-maven[]
[.tab-maven]
--
[source,shell]
----
export ORG=xxxx
cd rest-heroes
docker build -f src/main/docker/Dockerfile.native -t $ORG/quarkus-workshop-hero .
cd ..
cd rest-villains
docker build -f src/main/docker/Dockerfile.native -t $ORG/quarkus-workshop-villain .
cd ..
cd rest-fights
docker build -f src/main/docker/Dockerfile.native -t $ORG/quarkus-workshop-fight .
cd ..
cd event-statistics
docker build -f src/main/docker/Dockerfile.native -t $ORG/quarkus-workshop-stats .
cd ..
----
--
endif::use-maven[]
ifdef::use-gradle[]
[.tab-gradle]
--
[source,shell]
----
export ORG=xxxx
cd rest-heroes
docker build -f src/main/docker/Dockerfile.native-gradle -t $ORG/quarkus-workshop-hero .
cd ..
cd rest-villains
docker build -f src/main/docker/Dockerfile.native-gradle -t $ORG/quarkus-workshop-villain .
cd ..
cd rest-fights
docker build -f src/main/docker/Dockerfile.native-gradle -t $ORG/quarkus-workshop-fight .
cd ..
cd event-statistics
docker build -f src/main/docker/Dockerfile.native-gradle -t $ORG/quarkus-workshop-stats .
cd ..
----
--
endif::use-gradle[]

[NOTE]
====
Replace `ORG` with your DockerHub / Quay.io username.
====

== Running Native Mode Containers Locally


== Building a container running a native executable

We've just created a container that embeds the Java application and a JVM.
But you can also build and use the native executable.
To do this, runs the following command:

ifdef::use-maven[]
[.tab-maven]
--
[source, shell]
----
./mvnw clean package -Dquarkus.container-image.build=true -Pnative -Dquarkus.native.container-build=true
----
--
endif::use-maven[]
ifdef::use-gradle[]
[.tab-gradle]
--
[source, shell]
----
./gradlew clean build -Dquarkus.container-image.build=true -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true
----
--
endif::use-gradle[]

`-Dquarkus.native.container-build=true` is indicating that we need a Linux 64bits executable.
This option is not required if you use Linux.
endif::use-native[]
