[[installing-cli]]

= Quarkus CLI

The Quarkus CLI lets you create projects, manage extensions and do essential build and dev commands using the underlying project build tool.footnote:[Quarkus CLI https://quarkus.io/guides/cli-tooling]

== Installing the Quarkus CLI

The Quarkus CLI is available in several developer-oriented package managers such as:

* https://sdkman.io[SDKMAN!]
* https://brew.sh[Homebrew]
* https://community.chocolatey.org/packages/quarkus[Chocolatey]

For example, to install the Quarkus CLI using SDKMAN!.
You first need to have a JDK installed before installing the Quarkus CLI.
Then, run the following command:

[source,shell]
----
sdk install quarkus
----

== Checking for Quarkus CLI Installation

Once installed `quarkus` will be in your `$PATH` and if you run `quarkus --version` it will print the installed version:

[source,shell,subs="attributes+"]
----
quarkus --version
{quarkus-version}
----

=== Some Quarkus CLI Commands

Quarkus CLI is a command-line tool where you can use several parameters and options to create, build, or execute your Quarkus project.
Use `--help` to display help information with all the available commands:

[source,shell]
----
$ quarkus --help
Usage: quarkus [-ehv] [--verbose] [-D=<String=String>]... [COMMAND]

Options:
  -D=<String=String>    Java properties
  -e, --errors          Display error messages.
  -h, --help            Show this help message and exit.
  -v, --version         Print version information and exit.
      --verbose         Verbose mode.

Commands:
  create                  Create a new project.
    app                   Create a Quarkus application project.
    cli                   Create a Quarkus command-line project.
    extension             Create a Quarkus extension project
  build                   Build the current project.
  dev                     Run the current project in dev (live coding) mode.
  extension, ext          Configure extensions of an existing project.
    list, ls              List platforms and extensions.
    categories, cat       List extension categories.
    add                   Add extension(s) to this project.
    remove, rm            Remove extension(s) from this project.
  registry                Configure Quarkus registry client
    list                  List enabled Quarkus registries
    add                   Add a Quarkus extension registry
    remove                Remove a Quarkus extension registry
  version                 Display version information.
----
