[[introduction-installing-rancher]]

= Rancher Desktop

.NOTE
----
You only need Rancher Desktop if you didn't install Docker or if you want to deploy the applications to a local
Kubernetes instance. You can also use https://minikube.sigs.k8s.io/docs/start/[minikube] for the latter.
----

Rancher Desktop runs Kubernetes and container management on your desktop.
You can choose the version of Kubernetes you want to run.
You can build, push, pull, and run container images using either _containerd_ or _Moby (dockerd)_.
The container images you build can be run by Kubernetes immediately without the need for a registry.

== Installing Rancher Desktop

To install Rancher Desktop, follows the https://docs.rancherdesktop.io/getting-started/installation[instructions].
Rancher Desktop is available on MacOS, Windows and various Linux distributions.

== Checking for Rancher Desktop Installation

Once installed, check that both `docker` and `kubectl` are available in your `PATH`:

[source,shell]
----
$ docker version
Docker version 20.10.16, build aa7e414

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3+k3s1", GitCommit:"5fb370e53e0014dc96183b8ecb2c25a61e891e76", GitTreeState:"clean", BuildDate:"2022-01-27T02:12:21Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
----

TIP: Rancher Desktop installs its own _docker_ CLI too in `±/.rd/bin

Finally, run your first container as follows:

[source,shell]
----
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
1. The Docker client contacted the Docker daemon.
2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
(amd64)
3. The Docker daemon created a new container from that image which runs the
executable that produces the output you are currently reading.
4. The Docker daemon streamed that output to the Docker client, which sent it
to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
$ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
----

== Some Docker Commands

Docker is a command-line utility where you can use several parameters and options to start/stop a container.
You invoke `docker` with zero, one, or several command-line options with the container or image ID you want to work with.
Docker comes with several options that are described in the documentation if you need more help.footnote:[Docker commands https://docs.docker.com/engine/reference/commandline/cli]
To get some help on the commands and options, you can type, use the following command:

[source,shell]
----
$ docker help

Usage:  docker [OPTIONS] COMMAND

$ docker help attach

Usage:  docker attach [OPTIONS] CONTAINER

Attach local standard input, output, and error streams to a running container
----

Here are some commands that you will be using to start/stop containers in this workshop.

* `docker container ls`: Lists containers.
* `docker container start CONTAINER`: Starts one or more stopped containers.
* `docker compose -f docker-compose.yaml up -d`: Starts all containers defined in a Docker Compose file.
* `docker compose -f docker-compose.yaml down`: Stops all containers defined in a Docker Compose file.

== Checking for Rancher Desktop Kubernetes support

IMPORTANT: If you use Kubernetes already, make sure that `kubectl` uses the `rancher-desktop` context.
This can be done from the Rancher Desktop UI.

[source, shell]
----
$ kubectl run hello-ngnix --image=nginx:alpine --port=80
$ kubectl port-forward pods/hello-ngnix 8080:80
----

If you open a browser to http://localhost:8080, you should see the "Welcome to nginx!" page.

Stop the port forwarding using `CTRL+C`, and delete the pod:

[source,shell]
----
(CTRL+C)
$ kubectl delete pod hello-ngnix
----
