[[introduction-preparing]]
= Preparing for the Workshop

In this workshop, you will be developing an application dealing with Super Heroes (and Super-Villains 🦹) as well as Quarkus extensions.
The code will be separated into two different directories:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes         | The entire Super Hero application
}
}
@endsalt
----

== Download the workshop scaffolding

[example, role="cta"]
--

We've done some of the layout for you. First, download the zip file  {github-raw}/dist/quarkus-super-heroes-workshop.zip, and unzip it wherever you want.
This zip file contains _some_ of the code of the workshop, along with assets you will need to complete it.

--

=== Super Heroes Application

Under the `super-heroes` directory you will find the entire Super Hero application spread throughout a set of subdirectories, each one containing a microservice or some tooling.
The final structure will be the following (don't worry if you don't have all this yet, this is what we're aiming towards):

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes
++ event-statistics        | UI and application dealing with fight statistics (you will create it)
++ infrastructure          | All the needed infrastructure (Postgres, Kafka...)
++ kubernetes              | All the files required to deploy on Kubernetes
++ load-super-heroes       | Stress tool loading heroes, villains and fights
++ rest-fights             | REST API allowing super heroes to fight (you will create it)
++ rest-heroes             | Reactive REST API for CRUD operations on Heroes (you will create it)
++ rest-narration          | REST API invoking an AI to narrate the fight (you will create it)
++ rest-villains           | REST API for CRUD operations on Villains (you will create it)
++ ui-super-heroes         | Angular application so we can fight visually
}
}
@endsalt
----

Most of these subdirectories are Maven projects and follow the Maven directory structure:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  super-heroes
++ rest-villains
+++ src
++++  main
+++++  docker
+++++  java
+++++  resources
++++  test
+++++  java
}
}
@endsalt
----

include::introduction-preparing-checking-ports.adoc[leveloffset=+1]

== Ready?

After the prerequisites have been installed and the environment has been checked,  it's now time to write some code!

