[[introduction-installing-ai]]

= OpenAI or AzureAI Subscriptions

The Narration microservice needs to access an AI service to generate the text narrating the fight.
You can choose between OpenAI or AzureAI.

== OpenAI

TODO
TODO
TODO
TODO
TODO
TODO
TODO
TODO

== AzureAI

If you already have an Azure subscription, you can use it to create an AzureAI resource.
Otherwise, you can create a https://azure.microsoft.com/free[free Azure subscription] and use it to create an AzureAI resource.
Then, you need to use the AzureAI service to generate the API key and endpoint URL.
You can either do that using the https://portal.azure.com/[Azure Portal] or the https://learn.microsoft.com/cli/azure/[Azure CLI].

The easiest being use the Azure CLI, we recommend that you https://learn.microsoft.com/cli/azure/install-azure-cli[install it] and use it to create the AzureAI resource and generate the API key and endpoint URL.
Once Azure CLI is installed and you have your Azure subscription, sign in to your Azure account:

[source,shell]
----
az login
----

[NOTE]
====
If you have several Azure subscription, make sure you are using the right one.
For that, you can execute the following command to list all your subscriptions and set the one you want to use:

[source,shell]
----
az account list --output table
az account set --subscription <subscription-id>
az account show
----
====

Then, execute the following command to create the AzureAI resources:

[source,bash]
----
include::../../../../../super-heroes/infrastructure/ai-azure-openai-create.sh[tags=adocSetup;!adocSkip]
----

This script will create the AzureAI resource and deploy the model.
Once the script has executed, you can use the following command to get the API key and endpoint URL.
You will need these properties later one when you will configure the Narration microservice:

[source,bash]
----
include::../../../../../super-heroes/infrastructure/ai-azure-openai-create.sh[tag=adocProperties]
----

Once you've finished the workshop, remember to delete the AzureAI resources to avoid being charged for it:

[source,bash]
----
include::../../../../../super-heroes/infrastructure/ai-azure-openai-delete.sh[tag=adocDelete]
----
