[[introduction-installing-graalvm]]

= GraalVM {graalvm-version}

GraalVM extends the _Java Virtual Machine_ (JVM) to support more languages and several execution modes.footnote:[GraalVM https://www.graalvm.org]
It supports a large set of languages:
Java of course, other JVM-based languages (such as Groovy, Kotlin etc.) but also JavaScript, Ruby, Python, R and C/C++.
It includes a high-performance Java compiler, which can be used in a _Just-In-Time_ (JIT) configuration on the HotSpot VM or in an _Ahead-Of-Time_ (AOT) configuration with the GraalVM native compiler.
One objective of GraalVM is to improve the performance of Java virtual machine-based languages to match the performance of native languages.

== Prerequisites for GraalVM

ifdef::use-linux[]
On Linux, you need GCC and the Glibc and zlib headers.
Examples for common distributions:

[source,shell]
----
# dnf (rpm-based)
sudo dnf install gcc glibc-devel zlib-devel
# Debian-based distributions:
sudo apt-get install build-essential libz-dev zlib1g-dev
----
endif::use-linux[]

ifdef::use-mac[]
On macOS X, XCode provides the required dependencies to build native executables:

[source,shell]
----
xcode-select --install
----
endif::use-mac[]

ifdef::use-windows[]
On Windows, you need the _Developer Command Prompt for Microsoft Visual C++_.
Check the https://www.graalvm.org/docs/getting-started/windows/#prerequisites-for-using-native-image-on-windows[Windows prerequisites page] for details.
endif::use-windows[]

== Installing GraalVM

GraalVM is installed from the GraalVM project.footnote:[GraalVM Download https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-{graalvm-version}].

Version {graalvm-version} is required.
Select the {jdk-version} version.

Follow the installation instructions:

ifdef::use-linux[]
- Linux - https://www.graalvm.org/docs/getting-started/linux/
endif::use-linux[]
ifdef::use-windows[]
- Windows - https://www.graalvm.org/docs/getting-started/windows/
endif::use-windows[]
ifdef::use-mac[]
- MacOS - https://www.graalvm.org/docs/getting-started/macos/
endif::use-mac[]

Once installed, define the `GRAALVM_HOME` environment variable to point to the directory where GraalVM is installed (eg. on Mac OS X it could be `/Library/Java/JavaVirtualMachines/graalvm-ce-{graalvm-version}/Contents/Home`).

The `native-image` tool must be installed.
It can be done by running

[source,shell]
----
gu install native-image
----

from your GraalVM `bin` directory.

ifdef::use-mac[]
[NOTE]
.Mac OS X - Catalina
====
On Mac OS X Catalina, the installation of the `native-image` executable may fail.
GraalVM binaries are not (yet) notarized for Catalina.
To bypass the issue, it is recommended to run the following command instead of disabling macOS Gatekeeper entirely:

[source,shell]
-----
xattr -r -d com.apple.quarantine ${GRAAL_VM}
-----
====
endif::use-mac[]

== Checking for GraalVM Installation

Once installed and set up, you should be able to run the following command and get the following output.

[source,shell]
----
$ $GRAALVM_HOME/bin/native-image --version
GraalVM 22.0.0.2 Java 17 CE (Java Version 17.0.15+10-jvmci-22.0-b05)
----

