[[introduction-installing-docker]]

= Docker

[NOTE]
====
Instead of Docker, you can use Rancher Desktop which provide the same capabilities but also lets you run Kubernetes locally.
If you plan to deploy your applications to Kubernetes, we recommend Rancher Desktop.

Instructions to install Rancher Desktop are available in <<introduction-installing-rancher>>.
====

Docker is a set of utilities that use OS-level virtualization to deliver software in packages called containers.
Containers are isolated from one another and bundle their software, libraries, and configuration files;
they can communicate with each other through well-defined channels.

== Installing Docker

Our infrastructure will use Docker to ease the installation of the different technical services (database, monitoring...).
So for this, we need to install `docker` and `docker compose`
Installation instructions are available on the following page:

ifdef::use-mac[]
* Mac OS X - https://docs.docker.com/docker-for-mac/install/ (version 20+)
endif::use-mac[]
ifdef::use-windows[]
* Windows - https://docs.docker.com/docker-for-windows/install/ (version 20+)
endif::use-windows[]
ifdef::use-linux[]
* CentOS - https://docs.docker.com/install/linux/docker-ce/centos/
* Debian - https://docs.docker.com/install/linux/docker-ce/debian/
* Fedora - https://docs.docker.com/install/linux/docker-ce/fedora/
* Ubuntu - https://docs.docker.com/install/linux/docker-ce/ubuntu/

On Linux, don't forget the post-execution steps described on https://docs.docker.com/install/linux/linux-postinstall/.
endif::use-linux[]

NOTE: If you do not have a Docker licence, you might prefer `podman` (https://podman.io/) instead of `docker`. To install `podman` and `podman-compose` on Fedora please follow the instructions at https://fedoramagazine.org/manage-containers-with-podman-compose/. You will also need to configure testcontainers library used in Dev Services later in the workshop like mentioned in https://quarkus.io/blog/quarkus-devservices-testcontainers-podman/#tldr.

== Checking for Docker Installation

Once installed, check that both `docker` and `docker compose` are available in your `PATH`:

[source,shell]
----
$ docker version
Docker version 20.10.8, build 3967b7d
Cloud integration: v1.0.24
Version:           20.10.14
API version:       1.41

$ docker compose version
Docker Compose version v2.5.0
----

Finally, run your first container as follows:

[source,shell]
----
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
1. The Docker client contacted the Docker daemon.
2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
(amd64)
3. The Docker daemon created a new container from that image which runs the
executable that produces the output you are currently reading.
4. The Docker daemon streamed that output to the Docker client, which sent it
to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
$ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
----

== Some Docker Commands

Docker is a command-line utility where you can use several parameters and options to start/stop a container.
You invoke `docker` with zero, one, or several command-line options with the container or image ID you want to work with.
Docker comes with several options that are described in the documentation if you need more help.footnote:[Docker commands https://docs.docker.com/engine/reference/commandline/cli]
To get some help on the commands and options, you can type, use the following command:

[source,shell]
----
$ docker help

Usage:  docker [OPTIONS] COMMAND

$ docker help attach

Usage:  docker attach [OPTIONS] CONTAINER

Attach local standard input, output, and error streams to a running container
----

Here are some commands that you will be using to start/stop containers in this workshop.

* `docker container ls`: Lists containers.
* `docker container start CONTAINER`: Starts one or more stopped containers.
* `docker compose -f docker-compose.yaml up -d`: Starts all containers defined in a Docker Compose file.
* `docker compose -f docker-compose.yaml down`: Stops all containers defined in a Docker Compose file.
