quarkus.tls.trust-all=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p %s%e%n
quarkus.rest-client.fight.url=http://localhost:8082
quarkus.rest-client.hero.url=http://localhost:8083
quarkus.rest-client.villain.url=http://localhost:8084
quarkus.rest-client.logging.scope=request-response

