[[conclusion]]
= Conclusion

'''

This is the end of the Super Hero workshop.
We hope you liked it, learnt a few things, and more importantly, will be able to take this knowledge back to your projects.

This workshop started making sure your development environment was ready to develop the entire application.
Then, there was some brief terminology to help you in understanding some concepts around Quarkus.
If you find it was too short and need more details on Quarkus, Microservices, MicroProfile, Cloud Native, or GraalVM, check the Quarkus website for more references.footnote:[Quarkus https://quarkus.io]


Then, we focused on developing several isolated microservices.
Some written in pure JAX-RS (such as the Villain) others with Reactive JAX-RS and Reactive Hibernate (such as the Hero).
These microservices return data in JSON, validate data thanks to Bean Validation, store and retrieve data from a relational database with the help of JPA, Panache and JTA.

You then installed an already coded Angular application on another instance of Quarkus.
At this stage, the Angular application couldn't access the microservices because of CORS issues that we quickly fixed.

Then, we made the microservices communicate with each other in HTTP thanks to REST Client.
But HTTP-related technologies usually use synchronous communication and therefore need to deal with invocation failure.
With Fault Tolerance, it was just a matter of using a few annotations and we can get some fallback when the communication fails.

That's also why we introduced Reactive Messaging with Kafka: so we don't have a temporal coupling between the microservices.

// TODO
//With so many microservices, observability becomes mandatory.
//That's why we added some health checks and metrics to our microservices.
//
//Then, comes production time.
//We had to build executable JARs and executable binaries (thanks to GraalVM), and package our microservices into Docker containers.

Remember that you can find all the code for this fascicle at {github-url}.
If some parts were not clear enough, or if you found something missing, a bug, or you just want to leave a note or suggestion, please use the GitHub issue tracker at {github-issue}.
