:plantDir: ../plantuml
:code-root: ../../../../../super-heroes

[[extension]]
= Writing a Quarkus Extension

'''

Most of the Quarkus magic happens inside extensions.
The goal of an extension is to compute _just enough bytecode_ to start the services that the application requires and drop everything else.

So, when writing an extension, you need to distinguish the action that:

* Can be done at build time - following the build time principle of Quarkus
* Must be done at runtime

Because of this distinction, extensions are divided into two parts: a build time augmentation and a runtime.
The augmentation part is responsible for all the metadata processing, annotation scanning, XML parsing...
The output of this augmentation is **recorded bytecode**, which, then, is executed at runtime to instantiate the relevant services.

In this chapter, you are going to implement a _version_ extension.
It prints the version of the application in the log of the application when this application starts.
It is a straightforward application, but it highlights the distinction between build time and runtime.
Instead of extracting the version at runtime and printing it, we find the version at build time and record the print instruction to when the application starts it prints the version.

== The extension framework

Quarkus's mission is to transform your entire application, including the libraries it uses, into an artifact that uses significantly fewer resources than traditional approaches.
These can then be used to build JVM applications and native executables using the GraalVM `native-image` compiler.

To do this, you need to analyze and understand the application's "closed world".
Without the full context, the best that can be achieved is partial and limited generic support.

To build an extension, Quarkus provides a framework to:

* Read the configuration from the `application.properties` file and map it to objects,
* Read metadata from classes without having to load them; this includes classpath and annotation scanning,
* Generate bytecode if needed (for proxies, for instance),
* Pass sensible defaults to the application,
* Make the application compatible with GraalVM (resources, reflection, substitutions),
* Implement hot-reload

== Structure of an extension

As stated above, an extension is divided into two parts, called `deployment` (augmentation) and `runtime`.

[plantuml,align=center]
----
include::{plantDir}/8-extension-architecture.puml[]
----

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

From the directory `super-heroes` execute the following commands:

[source,shell,subs="attributes+"]
----
mvn io.quarkus.platform:quarkus-maven-plugin:{quarkus-version}:create-extension -N \
    -DwithoutTests \
    -DextensionId=extension-version \
    -DgroupId=io.quarkus.workshop.super-heroes \
    -DpackageName=io.quarkus.workshop.superheroes.version
----

This command creates the structure for the banner extension:

* One parent `pom.xml` importing the `quarkus-bom`
* A module for the runtime
* A module for the deployment, with a dependency on the runtime artifact

The final structure of the extension developed in this section is the following:

[plantuml]
----
@startsalt
{
{
T
extension-version
+  deployment
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  version
++++++++++  deployment
+++++++++++  VersionConfig.java
+++++++++++  ExtensionVersionProcessor.java
++  pom.xml
+  runtime
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  version
++++++++++  runtime
+++++++++++  VersionRecorder.java
++++  resources
+++++  META-INF
++++++  quarkus-extension.yaml
++  pom.xml
+  pom.xml
}
}
@endsalt
----

== The version extension

The goal of this chapter is to implement an extension that displays the application version on startup.
For this, what do we need:

1. A way to extract the version (we're lucky, Quarkus provided it)
2. Some code that would print the version when the application starts; so some runtime code,
3. Some build steps that extracts the version and records the runtime invocations

== The runtime module

The _runtime_ part of an extension contains only the classes and resources required at runtime.
For the version extension, it would be a single class that prints the version.

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

In the runtime module, create the `src/main/java` directory, and, in this directory, the `io.quarkus.workshop.superheroes.version.runtime.VersionRecorder` class with the following content:

[source,java]
----
include::{code-root}/extension-version/runtime/src/main/java/io/quarkus/workshop/superheroes/version/runtime/VersionRecorder.java[]
----

Simple right?
But how does it work?
Look at the `@Recorder` annotation.
It indicates that this class is a _recorder_ used to record actions executed later at runtime.
Indeed, these actions are replayed at runtime.
We will see how this recorder is used from the _deployment_ module.

== The deployment module

This module contains _build steps_, i.e., methods called during the augmentation phase and computing just enough bytecode to serve the services the application requires.
The version extension consists of a single build step that extracts the version and uses the `VersionRecorder`.

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

First, let's create the configuration class that will allow users to dynamically configure whether the version should be printed:

Create new class `io.quarkus.workshop.superheroes.version.deployment.VersionConfig` with the following content:

[source,java]
----
include::{code-root}/extension-version/deployment/src/main/java/io/quarkus/workshop/superheroes/version/deployment/VersionConfig.java[]
----

The `@ConfigRoot` annotation declares `VersionConfig` as a configuration class which configuration properties are prefixed with `quarkus.` prefix.

The `@ConfigItem` is used to declare individual configuration properties. By default, the name of the property is derived from the name of the field. In our case, the user-configured property will be `quarkus.version.enabled`.

Next, open the `ExtensionVersionProcessor` class, and update the content to be:

[source, java]
----
include::{code-root}/extension-version/deployment/src/main/java/io/quarkus/workshop/superheroes/version/deployment/ExtensionVersionProcessor.java[]
----

This class is the core of the extension.
It contains a set of methods annotated with `@BuildStep`.

The command generated the first one we used to set up the project.
It just produces a `FeatureBuildItem`.
When the application starts, Quarkus lists the enabled features.
So, when this extension is present, `extension-version` will be printed.

The `recordVersion` method is responsible for recording the actions that will happen at runtime.
In addition to the `@BuildStep` annotation, it also has the `@Record` annotation allowing to receive a _recorder_ object (`VersionRecorder`) and indicating when the recorded bytecode is replayed.
Here we are replaying during the runtime initialization, _i.e.,_ equivalent to the `public static void main(String... args)` method.

The method also receives the `ApplicationInfoBuildItem`.
Quarkus provides many _build items_ which can be reused.
`ApplicationInfoBuildItem` contains the version.

The last parameter of the `recordVersion` method is the `VersionConfig` which provides access to the user configuration we created in the previous step.

The code is straightforward: if `enabled` is `true`, the code calls the recorder which prints the version.

[NOTE]
.Recorder at deployment time
====
At deployment time, proxies of recorders are injected into `@BuildStep` methods that have been annotated with `@Record`.
Any invocations made on these proxies will be recorded, and bytecode will be written out to be executed at runtime to make the same sequence of invocations with the same parameters on the actual recorder objects.
====

== Packaging the extension

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

From the root directory of the extension, run:

[source,shell]
----
mvn clean install
----

== Using the extension

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

Go back to the _villain_ microservice, and add the following dependency to the `pom.xml` file:

[source,xml,indent=0]
----
include::{code-root}/rest-villains/pom.xml[tags=extension-version]
----

If not yet started, start the microservice with:

[source,shell]
----
./mvnw quarkus:dev
----

And the version will be displayed:

[source, text]
----
10:16:58 INFO  [io.qu.wo.su.ve.ru.VersionRecorder] (Quarkus Main Thread) Version: 1.0.0-SNAPSHOT
...
10:17:00 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, extension-version, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-postgresql, narayana-jta, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, smallrye-openapi, swagger-ui, vertx]
----

== Conclusion

In this section, you have seen how to develop a simple extension for Quarkus.
Quarkus offers a complete toolbox to implement extensions, from configuration support, tests, bytecode generation...
The mindset to implement an extension is crucial.
The distinction between build time and runtime is what makes Quarkus so efficient.
To go further, check https://quarkus.io/guides/extension-authors-guide.


