[[introduction-installing]]
= Installing Software

== JDK {jdk-version}

Essential for the development and execution of this workshop is the _Java Development Kit_ (JDK).footnote:[Java http://www.oracle.com/technetwork/java/javase]
The JDK includes several tools such as a compiler (`javac`), a virtual machine, a documentation generator (`JavaDoc), monitoring tools (Visual VM) and so onfootnote:[Visual VM https://visualvm.github.io].
The code in this workshop uses JDK {jdk-version}.

=== Installing the JDK

To install the JDK {jdk-version}, follows the instructions from https://adoptium.net/installation.html to download and install the JDK for your platform.

There is also an easier way to download and install Java if you are on Mac OS X.
You can use Homebrew to install OpenJDK {jdk-version} using the following commands.footnote:[Homebrew https://brew.sh]

[source, shell]
----
$ brew install java11
----

For Linux distributions, there are also packaged java installations.
[source, shell]
----
# dnf (rpm-based)
dnf install java-11-openjdk
# Debian-based distributions:
$ apt-get install openjdk-11-jdk
----

=== Checking for Java Installation

Once the installation is complete, it is necessary to set the `JAVA_HOME` variable and the `$JAVA_HOME/bin` directory to the `PATH` variable.
Check that your system recognizes Java by entering `java -version` and the Java compiler with `javac -version`.

[source, shell]
----
$ java -version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
$ javac -version
javac 11.0.11
----

== GraalVM {graalvm-version}

GraalVM extends the _Java Virtual Machine_ (JVM) to support more languages and several execution modes.footnote:[GraalVM https://www.graalvm.org]
It supports a large set of languages:
Java of course, other JVM-based languages (such as Groovy, Kotlin etc.) but also JavaScript, Ruby, Python, R and  C/C++.
It includes a high-performance Java compiler, which can be used in a _Just-In-Time_ (JIT) configuration on the HotSpot VM or in an _Ahead-Of-Time_ (AOT) configuration with the GraalVM native compiler.
One objective of GraalVM is to improve the performance of Java virtual machine-based languages to match the performance of native languages.

=== Prerequisites for GraalVM

On Linux, you need GCC and the Glibc and zlib headers. Examples for common distributions:

[source, shell]
----
# dnf (rpm-based)
sudo dnf install gcc glibc-devel zlib-devel
# Debian-based distributions:
sudo apt-get install build-essential libz-dev zlib1g-dev
----

On macOS X, XCode provides the required dependencies to build native executables:

[source, shell]
----
xcode-select --install
----

On Windows, you need the _Developer Command Prompt for Microsoft Visual C++_.
Check the https://www.graalvm.org/docs/getting-started/windows/#prerequisites-for-using-native-image-on-windows[Windows prerequisites page] for details.

=== Installing GraalVM

GraalVM installed from the GraalVM project.footnote:[GraalVM Download https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-{graalvm-version}].

Version {graalvm-version} is required.
Select the {java-version} version.

Follows the installation instructions:

- Linux - https://www.graalvm.org/docs/getting-started/linux/
- Windows - https://www.graalvm.org/docs/getting-started/windows/
- MacOS - https://www.graalvm.org/docs/getting-started/macos/

Once installed, define the `GRAALVM_HOME` environment variable to point to the directory where GraalVM is installed (eg. on Mac OS X it will be /Library/Java/JavaVirtualMachines/graalvm-ce-{graalvm-version}/Contents/Home).

The `native-image` tool must be installed.
It can be done by running `gu install native-image` from your GraalVM `bin` directory.

[NOTE]
.Mac OS X - Catalina
====
On Mac OS X Catalina, the installation of the `native-image` executable may fail.
GraalVM binaries are not (yet) notarized for Catalina.
To bypass the issue, it is recommended to run the following command instead of disabling macOS Gatekeeper entirely:
[source, shell]
-----
xattr -r -d com.apple.quarantine ${GRAAL_VM}
-----
====

=== Checking for GraalVM Installation

Once installed and set up, you should be able to run the following command and get the following output.

[source, shell]
----
$ $GRAALVM_HOME/bin/native-image --version
GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08)
----

== Apache Maven {maven-version}

All the examples of this workshop are built and tested using Maven.footnote:[Maven https://maven.apache.org]
Maven offers a building solution, shared libraries, and a plugin platform for your projects, allowing you to do quality control, documentation, teamwork, and so forth.
Based on the "convention over configuration" principle, Maven brings a standard project description and a number of conventions such as a standard directory structure.
With an extensible architecture based on plugins, Maven can offer many different services.

=== Installing Maven

The examples of this workshop have been developed with Apache Maven {maven-version}.
Once you have installed JDK {jdk-version}, make sure the `JAVA_HOME` environment variable is set.
Then, download Maven from http://maven.apache.org/, unzip the file on your hard drive and add the `apache-maven/bin` directory to your `PATH` variable.
More details about the installation process are available on https://maven.apache.org/install.html.

But of course, if you are on Mac OS X and use Homebrew, install Maven with the following command:

[source, shell]
----
$ brew install maven
----

=== Checking for Maven Installation

Once you've got Maven installed, open a command line and enter `mvn -version` to validate your installation.
Maven should print its version and the JDK version it uses (which is handy as you might have different JDK versions installed on the same machine).

[source, shell]
----
$ mvn -version
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /usr/local/Cellar/maven/3.8.2/libexec
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Users/clement/.sdkman/candidates/java/11.0.11.hs-adpt
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
----

Be aware that Maven needs Internet access to download plugins and project dependencies from the Maven Central and other remote repositories.footnote:[Maven Central https://search.maven.org]

=== Some Maven Commands

Maven is a command-line utility where you can use several parameters and options to build, test, or package your code.
To get some help on the commands, you can type, use the following command:

[source, shell]
----
$ mvn --help

usage: mvn [options] [<goal(s)>] [<phase(s)>]
----

Here are some commands that you will be using to run the examples in the workshop.
Each invokes a different phase of the project life cycle (clean, compile, install, etc.) and use the `pom.xml` to download libraries, customize the compilation, or extend some behaviors with plugins:

* `mvn clean`: Deletes all generated files (compiled classes, generated code, artifacts etc.).
* `mvn compile`: Compiles the main Java classes.
* `mvn test-compile`: Compiles the test classes.
* `mvn test`: Compiles the main Java classes as well as the test classes and executes the tests.
* `mvn package`: Compiles, executes the tests, and packages the code into an archive.
* `mvn install`: Builds and installs the artifacts in your local repository.
* `mvn clean install`: Cleans and installs (note that you can add several commands separated by a space, like `mvn clean compile test`).

== cURL

To invoke the REST Web Services described in this workshop, we often use cURL.footnote:[cURL https://curl.haxx.se]
cURL is a command-line tool and library to do reliable data transfers with various protocols, including HTTP.
It is free, open-source (available under the MIT Licence), and has been ported to several operating systems.

=== Installing cURL

If you are on Mac OS X and have installed Homebrew, then installing cURL is just a matter of a single command.footnote:[Homebrew https://brew.sh]
Open your terminal and install cURL with the following command:

[source, shell]
----
$ brew install curl
----

For Windows, download and install curl from https://curl.se/download.html.

=== Checking for cURL Installation

Once installed, check for cURL by running `curl --version` in the terminal.
It should display cURL version:

[source, shell]
----
$ curl --version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
----

=== Some cURL Commands

cURL is a command-line utility where you can use several parameters and options to invoke URLs.
You invoke `curl` with zero, one, or several command-line options to accompany the URL (or set of URLs) you want the transfer to be about.
cURL supports over two hundred different options, and I would recommend reading the documentation for more help.footnote:[cURL commands https://ec.haxx.se/cmdline.html]
To get some help on the commands and options, you can type, use the following command:

[source,shell]
----
$ curl --help

Usage: curl [options...] <url>
----

You can also opt to use `curl --manual`, which will output the entire man page for cURL plus an appended tutorial for the most common use cases.

Here are some commands you will use to invoke the RESTful web service examples in this workshop.

* `curl http://localhost:8083/api/heroes/hello`: HTTP GET on a given URL.
* `curl -X GET http://localhost:8083/api/heroes/hello`: Same effect as the previous command, an HTTP GET on a given URL.
* `curl -v http://localhost:8083/api/heroes/hello`: HTTP GET on a given URL with verbose mode on.
* `curl -H 'Content-Type: application/json' http://localhost:8083/api/heroes/hello`: HTTP GET on a given URL passing the JSON Content Type in the HTTP Header.
* `curl -X DELETE http://localhost:8083/api/heroes/1`: HTTP DELETE on a given URL.

=== Formatting the cURL JSON Output

Very often, when using cURL to invoke a RESTful web service, we get some JSON payload.
cURL does not format this JSON so that you will get a flat String such as:

[source, shell]
----
$ curl http://localhost:8083/api/heroes
[{"id":"1","name":"Chewbacca","level":"14"},{"id":"2","name":"Wonder Woman","level":"15"},{"id":"3","name":"Anakin Skywalker","level":"8"}]
----

But what we want is to format the JSON payload, so it is easier to read.
For that, there is a neat utility tool called `jq` that we could use.
`jq` is a tool for processing JSON inputs, applying the given filter to its JSON text inputs, and producing the filter's results as JSON on standard output.footnote:[jq https://stedolan.github.io/jq]
You can install it on Mac OSX with a simple `brew install jq`.
Once installed, it's just a matter of piping the cURL output to jq like this:

[source, shell]
----
$ curl http://localhost:8083/api/heroes | jq
[
  {
    "id": "1",
    "name": "Chewbacca",
    "lastName": "14"
  },
  {
    "id": "2",
    "name": "Wonder Woman",
    "lastName": "15"
  },
  {
    "id": "3",
    "name": "Anakin Skywalker",
    "lastName": "8"
  }
]
----

== Docker

Docker is a set of utilities that use OS-level virtualization to deliver software in packages called containers.
Containers are isolated from one another and bundle their software, libraries, and configuration files;
they can communicate with each other through well-defined channels.

=== Installing Docker

Our infrastructure will use Docker to ease the installation of the different technical services (database, monitoring...).
So for this, we need to install `docker` and `docker-compose`
Installation instructions are available on the following page:

* Mac OS X - https://docs.docker.com/docker-for-mac/install/ (version 20+)
* Windows - https://docs.docker.com/docker-for-windows/install/ (version 20+)
* CentOS - https://docs.docker.com/install/linux/docker-ce/centos/
* Debian - https://docs.docker.com/install/linux/docker-ce/debian/
* Fedora - https://docs.docker.com/install/linux/docker-ce/fedora/
* Ubuntu - https://docs.docker.com/install/linux/docker-ce/ubuntu/

On Linux, don't forget the post-execution steps described on https://docs.docker.com/install/linux/linux-postinstall/.

=== Checking for Docker Installation

Once installed, check that both `docker` and `docker-compose` are available in your `PATH`:

[source, shell]
----
$ docker version
Docker version 20.10.8, build 3967b7d

$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

# Alternatively, on recent Docker versions:
$ docker compose version
Docker Compose version v2.0.0-rc.3
----

Finally, run your first container as follows:

[source, shell]
----
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
1. The Docker client contacted the Docker daemon.
2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
(amd64)
3. The Docker daemon created a new container from that image which runs the
executable that produces the output you are currently reading.
4. The Docker daemon streamed that output to the Docker client, which sent it
to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
$ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
----

=== Some Docker Commands

Docker is a command-line utility where you can use several parameters and options to start/stop a container.
You invoke `docker` with zero, one, or several command-line options with the container or image ID you want to work with.
Docker comes with several options that are described in the documentation if you need more help.footnote:[Docker commands https://docs.docker.com/engine/reference/commandline/cli]
To get some help on the commands and options, you can type, use the following command:

[source, shell]
----
$ docker help

Usage:  docker [OPTIONS] COMMAND

$ docker help attach

Usage:  docker attach [OPTIONS] CONTAINER

Attach local standard input, output, and error streams to a running container
----

Here are some commands that you will be using to start/stop containers in this workshop.

* `docker container ls`: Lists containers.
* `docker container start CONTAINER`: Starts one or more stopped containers.
* `docker-compose -f docker-compose.yaml up -d`: Starts all containers defined in a Docker Compose file.
* `docker-compose -f docker-compose.yaml down`: Stops all containers defined in a Docker Compose file.

== Recap

Just make sure the following commands work on your machine.

[source, shell]
----
$ java -version
$ $GRAALVM_HOME/bin/native-image --version
$ mvn -version
$ curl --version
$ docker version
$ docker-compose version
----
