[[azure-intro-preparing]]
= Preparing for the Workshop

This workshop needs internet to access Azure of course, but also to download all sorts of Maven artifacts, Docker images, and even pictures.
Some of these artifacts are large, and because we have to share internet connexions at the workshop, it is better to download them before the workshop.
Here are a few commands that you can execute before the workshop.

== Clone the GitHub repository of the application

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

First, clone the GitHub repository of the Super Heroes application located at https://github.com/quarkusio/quarkus-workshops by executing the following command:

[source,shell]
----
git clone https://github.com/quarkusio/quarkus-workshops.git
----

You can set the `WORKSHOP_HOME` variable pointing at the root of the code directory.
The code of this Super Heroes application is separated into two different directories:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes         | The entire Super Hero application
}
}
@endsalt
----

Under the `super-heroes` directory you will find the entire Super Hero application spread throughout a set of subdirectories, each one containing a microservice or some tooling.
The final structure will be the following:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes
++ event-statistics        | UI and application dealing with fight statistics (you will create it)
++ infrastructure          | All the needed infrastructure (Postgres, Kafka...)
++ kubernetes              | All the files required to deploy on Kubernetes
++ load-super-heroes       | Stress tool loading heroes, villains and fights
++ rest-fight              | REST API allowing super heroes to fight (you will create it)
++ rest-hero               | Reactive REST API for CRUD operations on Heroes (you will create it)
++ rest-villains            | REST API for CRUD operations on Villains (you will create it)
++ ui-super-heroes         | Angular application so we can fight visually
}
}
@endsalt
----

include::../0-introduction/introduction-preparing-checking-ports.adoc[leveloffset=+1]

== Warming up the Java dependencies

Now that you have the initial structure in place, navigate to the root directory and run:

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

[source,shell]
----
quarkus build
----

By running this command, it downloads all the required Java dependencies.

include::../0-introduction/introduction-preparing-warming-docker.adoc[leveloffset=+1]

== Setting Up Azure

First of all, you need an Azure subscription.
If you don't have one, go to https://signup.azure.com and register.
Also make sure you have [Azure CLI installed](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) on your machine, as well as [curl](https://curl.se) and [jq](https://stedolan.github.io/jq).

Once everything is installed, sign in to Azure from the CLI:

```shell
az login
```

=== Setting Up the Azure Environment

You only have to setup this once.
Install the Azure Container Apps and Database extensions for the Azure CLI:

```shell
az extension add --name containerapp
az extension add --name rdbms-connect
```

Register the Microsoft.App namespace

```shell
az provider register --namespace Microsoft.App --wait
```



== The completed workshop

You can find the completed code on {github-url}.
So, if you are stuck, feel free to check the solution.

In addition, you can {github-raw}/dist/quarkus-super-heroes-workshop-complete.zip[download] the full code of the workshop .

To build the completed workshop, you need to run the following commands from the root project:

[source, shell]
----
> mvn clean install -f super-heroes/extension-version
> mvn clean install -Pcomplete
----

== Ready?

After the prerequisites have been installed and the different components have been warmed up,  it's now time to write some code!

