[[introduction-preparing]]
= Preparing for the Workshop

This workshop needs internet access to download all sorts of Maven artifacts, Docker images, and even pictures.
Some of these artifacts are large, and because we have to share internet connexions at the workshop, it is better to download them before the workshop.
Here are a few commands that you can execute before the workshop.

== Download the workshop scaffolding

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

First, download the zip file  {github-raw}/dist/quarkus-super-heroes-workshop.zip, and unzip it wherever you want.
This zip file contains _some_ of the code of the workshop, and you will need to complete it.

In this workshop, you will be developing an application dealing with Super Heroes (and Super-Villains 🦹) as well as Quarkus extensions.
The code will be separated into two different directories:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes         | The entire Super Hero application
}
}
@endsalt
----

=== Super Heroes Application

Under the `super-heroes` directory you will find the entire Super Hero application spread throughout a set of subdirectories, each one containing a microservice or some tooling.
The final structure will be the following:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes
++ event-statistics        | UI and application dealing with fight statistics (you will create it)
++ infrastructure          | All the needed infrastructure (Postgres, Kafka...)
++ kubernetes              | All the files required to deploy on Kubernetes
++ load-super-heroes       | Stress tool loading heroes, villains and fights
++ rest-fight              | REST API allowing super heroes to fight (you will create it)
++ rest-hero               | Reactive REST API for CRUD operations on Heroes (you will create it)
++ rest-villains            | REST API for CRUD operations on Villains (you will create it)
++ ui-super-heroes         | Angular application so we can fight visually
}
}
@endsalt
----

Most of these subdirectories are Maven projects and follow the Maven directory structure:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  super-heroes
++ rest-villains
+++ src
++++  main
+++++  docker
+++++  java
+++++  resources
++++  test
+++++  java
}
}
@endsalt
----

== Checking Ports

During this workshop, we will use several ports.

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

Just make sure the following ports are free, so you don't run into any conflicts.

[source,shell]
----
$ lsof -i tcp:8080    // UI
$ lsof -i tcp:8082    // Fight REST API
$ lsof -i tcp:8084    // Villain REST API
$ lsof -i tcp:8083    // Hero REST API
$ lsof -i tcp:5432    // Postgres
$ lsof -i tcp:9090    // Prometheus
$ lsof -i tcp:2181    // Zookeeper
$ lsof -i tcp:9092    // Kafka
----

== Warming up Maven

Now that you have the initial structure in place, navigate to the root directory and run:

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#


[source,shell]
----
mvn clean install
----

By running this command, it downloads all the required dependencies.

== Warming up Docker

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

To warm up your Docker image repository, navigate to the `quarkus-workshop-super-heroes/super-heroes/infrastructure` directory.

Here, you will find a `docker-compose.yaml`/`docker-compose-linux.yaml` files which define all the needed Docker images.
Notice that there is a `db-init` directory with an `initialize-databases.sql` script which sets up our databases, and a `monitoring` directory (all that will be explained later).

Then execute `docker compose -f docker-compose.yaml up -d`.
It will download all the Docker images and start the containers.

[WARNING]
.Linux Users beware
====
If you are on Linux, use `docker-compose-linux.yaml` instead of `docker-compose.yaml`. This Linux specific file will allow Prometheus to fetch metrics from the services running on the host machine.
====

[WARNING]
====
If you have an issue creating the roles for the database with the `initialize-databases.sql` file, you have to execute the following commands:

[source,shell]
----
docker exec -it --user postgres super-database psql -c "CREATE ROLE superman LOGIN PASSWORD 'superman' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
docker exec -it --user postgres super-database psql -c "CREATE ROLE superbad LOGIN PASSWORD 'superbad' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
docker exec -it --user postgres super-database psql -c "CREATE ROLE superfight LOGIN PASSWORD 'superfight' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
----
====

After this, verify the containers are running using the following command:

[source,shell]
----
docker compose -f docker-compose.yaml ps
----

The output should resemble something like this:

[source,shell]
----
     Name                   Command               State           Ports
--------------------------------------------------------------------------------
kafka            sh -c bin/kafka-server-sta ...   Up      0.0.0.0:9092->9092/tcp
super-database   docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp
super-visor      /bin/prometheus --config.f ...   Up      0.0.0.0:9090->9090/tcp
zookeeper        sh -c bin/zookeeper-server ...   Up      0.0.0.0:2181->2181/tcp
----

Once all the containers are up and running, you can shut them down and remove their volumes with the commands:

[source,shell]
----
docker compose -f docker-compose.yaml down
docker compose -f docker-compose.yaml rm
----

[NOTE]
====
.What's this infra?
Any microservice system is going to rely on a set of technical services.
In our context, we are going to use PostgreSQL as the database, Prometheus as the monitoring tool, and Kafka as the event/message bus.
This infrastructure starts all these services, so you don't have to worry about them.

This infra will only be used when we run our services in _prod_ mode. In _dev_ mode, Quarkus will start everything for us.
====

== Setting Up Azure

First of all, you need an Azure subscription.
If you don't have one, go to https://signup.azure.com and register.
Also make sure you have [Azure CLI installed](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) on your machine, as well as [curl](https://curl.se) and [jq](https://stedolan.github.io/jq).

Once everything is installed, sign in to Azure from the CLI:

```shell
az login
```

=== Setting Up the Azure Environment

You only have to setup this once.
Install the Azure Container Apps and Database extensions for the Azure CLI:

```shell
az extension add --name containerapp
az extension add --name rdbms-connect
```

Register the Microsoft.App namespace

```shell
az provider register --namespace Microsoft.App --wait
```



== The completed workshop

You can find the completed code on {github-url}.
So, if you are stuck, feel free to check the solution.

In addition, you can {github-raw}/dist/quarkus-super-heroes-workshop-complete.zip[download] the full code of the workshop .

To build the completed workshop, you need to run the following commands from the root project:

[source, shell]
----
> mvn clean install -f super-heroes/extension-version
> mvn clean install -Pcomplete
----

== Ready?

After the prerequisites have been installed and the different components have been warmed up,  it's now time to write some code!

