[[appendix-preparing-warming-docker]]

= Warming up Docker images

To warm up your Docker image repository, navigate to the `quarkus-workshop-super-heroes/super-heroes/infrastructure` directory.
ifdef::use-mac,use-windows[]
Here, you will find a `docker-compose.yaml` file which defines all the needed Docker images.
endif::use-mac,use-windows[]
ifdef::use-linux[]
Here, you will find a `docker-compose-linux.yaml` file which defines all the needed Docker images.
endif::use-linux[]
ifndef::use-mac+use-windows+use-linux[]
Here, you will find a `docker-compose.yaml` or `docker-compose-linux.yaml` file which defines all the needed Docker images.
endif::use-mac+use-windows+use-linux[]
Notice that there is a `db-init` directory with an `initialize-databases.sql` script which sets up our databases, and a `monitoring` directory (all that will be explained later).

// NOTE: Inlined from common-no-zip-infrastructure.adoc to work around Roq's lack of base-dir support for nested includes.
// Once Roq 2.1.10+ is released, restore to: include::../common-no-zip-infrastructure.adoc[]
ifdef::use-no-zip[]
[TIP]
.Working without the zip
====
The workshop zip provides a `super-heroes/infrastructure` directory.
If downloading it isn't an option for you, create that directory yourself and add the files below.
They are exactly the files the zip would have given you, so you can copy and paste them.

.super-heroes/infrastructure/docker-compose.yaml
[source,yaml]
----
include::{projectdir}/infrastructure/docker-compose.yaml[]
----

ifdef::use-linux[]
.super-heroes/infrastructure/docker-compose-linux.yaml
[source,yaml]
----
include::{projectdir}/infrastructure/docker-compose-linux.yaml[]
----
endif::use-linux[]

ifdef::use-messaging[]
.super-heroes/infrastructure/docker-compose-kafka.yaml
[source,yaml]
----
include::{projectdir}/infrastructure/docker-compose-kafka.yaml[]
----
endif::use-messaging[]

.super-heroes/infrastructure/db-init/initialize-databases.sql
[source,sql]
----
include::{projectdir}/infrastructure/db-init/initialize-databases.sql[]
----

.super-heroes/infrastructure/monitoring/prometheus.yml
[source,yaml]
----
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

include::{projectdir}/infrastructure/monitoring/prometheus.yml[tags=adocPrometheus]
----

ifdef::use-linux[]
.super-heroes/infrastructure/monitoring/prometheus-linux.yml
[source,yaml]
----
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

include::{projectdir}/infrastructure/monitoring/prometheus-linux.yml[tags=adocPrometheus]
----
endif::use-linux[]

Once these files are in place, the `docker compose` commands below will work exactly as they would have with the zip.
====
endif::use-no-zip[]

[role="cta"]
====

Then execute the following command which will download all the Docker images and start the containers:

[source,shell]
----
docker compose -f docker-compose.yaml up -d
----
ifdef::use-messaging[]

If you are doing the optional messaging section, also start the Kafka infrastructure:

[source,shell]
----
docker compose -f docker-compose-kafka.yaml up -d
----
endif::use-messaging[]
====

ifdef::use-linux[]
[WARNING]
.Linux Users beware
====
If you are on Linux, use `docker-compose-linux.yaml` instead of `docker-compose.yaml`. This Linux specific file will allow Prometheus to fetch metrics from the services running on the host machine.
====
endif::use-linux[]

[WARNING]
====
If you have an issue creating the roles for the database with the `initialize-databases.sql` file, you have to execute the following commands:

[source,shell]
----
docker exec -it --user postgres super-database psql -c "CREATE ROLE superman LOGIN PASSWORD 'superman' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
docker exec -it --user postgres super-database psql -c "CREATE ROLE superbad LOGIN PASSWORD 'superbad' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
docker exec -it --user postgres super-database psql -c "CREATE ROLE superfight LOGIN PASSWORD 'superfight' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
----
====

After this, verify the containers are running using the following command:

[source,shell]
----
docker compose -f docker-compose.yaml ps
----

The output should resemble something like this:

[source,shell]
----
     Name                   Command               State           Ports
--------------------------------------------------------------------------------
super-database   docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp
super-visor      /bin/prometheus --config.f ...   Up      0.0.0.0:9090->9090/tcp
----

Once all the containers are up and running, you can shut them down and remove their volumes with the commands:

[source,shell]
----
docker compose -f docker-compose.yaml down
docker compose -f docker-compose.yaml rm
----
ifdef::use-messaging[]

If you started the Kafka infrastructure, also shut it down:

[source,shell]
----
docker compose -f docker-compose-kafka.yaml down
docker compose -f docker-compose-kafka.yaml rm
----
endif::use-messaging[]

[NOTE]
====
.What's this infra?
Any microservice system is going to rely on a set of technical services.
ifndef::use-messaging[]
In our context, we are going to use PostgreSQL as the database and Prometheus as the monitoring tool.
endif::use-messaging[]
ifdef::use-messaging[]
In our context, we are going to use PostgreSQL as the database, Prometheus as the monitoring tool, and Kafka as the event/message bus.
endif::use-messaging[]
This infrastructure starts all these services, so you don't have to worry about them.

This infra will only be used when we run our services in _prod_ mode. In _dev_ mode, Quarkus will start everything for us.
====
