== Appendix: Installing extra software

include::appendix-installing-maven.adoc[leveloffset=+2]

include::appendix-installing-curl.adoc[leveloffset=+2]

// NOTE: This section is flattened to work around Roq's lack of base-dir support for nested includes.
// Once Roq 2.1.10+ is released with base-dir support, this can be restored to:
//   include::appendix-preparing-warming-caches.adoc[leveloffset=+2]
// and appendix-preparing-warming-caches.adoc can be recreated with its original nested structure.
=== Warming the caches

ifdef::use-maven[]
This workshop needs internet access to download all sorts of Maven artifacts, Docker images, and even pictures.
endif::use-maven[]
ifdef::use-gradle[]
This workshop needs internet access to download all sorts of Gradle dependencies, Docker images, and even pictures.
endif::use-gradle[]
Some of these artifacts are large, and because we have to share internet connexions at the workshop, it is better to download them before the workshop.

If you're getting ready for a workshop, you might find it helpful to pre-download some Docker images.
This can save strain on shared bandwidth. If, however, you're already attending a workshop, don't
worry about warming anything up.

include::appendix-preparing-warming-maven.adoc[leveloffset=+3]

include::appendix-preparing-warming-docker.adoc[leveloffset=+3]
