[[rest-openapi]]
= Open API

A Quarkus application can expose its API description through an OpenAPI specification.
Quarkus also lets you test it via a user-friendly UI named Swagger UI.

In this section, we will see how to use OpenAPI with Quarkus and introduce the dev console.

== Directory Structure

In this module we will add extra class (`VillainApplication`) to the Villain API project.
You will end-up with the following directory structure:

[plantuml]
----
@startsalt
{
{
T
super-heroes
+  rest-villain
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  villain
++++++++++  Villain.java
++++++++++  VillainApplication.java // We will add it
++++++++++  VillainResource.java
++++++++++  VillainService.java
++  pom.xml
}
}
@endsalt
----

== Installing the OpenAPI extension

Quarkus proposes a `smallrye-openapi` extension compliant with the MicroProfile OpenAPI specification in order to generate your API OpenAPI v3 specification.footnote:[MicroProfile OpenAPI https://github.com/eclipse/microprofile-open-api]

[example, role="cta"]
--

To install the OpenAPI dependency, just run the following command:

[source,shell]
----
./mvnw quarkus:add-extension -Dextensions="smallrye-openapi"
----
--

This will add the following dependency in the `pom.xml` file:

[source,xml,indent=0]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-smallrye-openapi</artifactId>
</dependency>
----

== Open API

Now, _curl_ `http://localhost:8084/q/openapi` endpoint with the command `curl http://localhost:8084/q/openapi` and you will see the following OpenAPI contract:

[source,yaml]
----
include::{projectdir}/rest-villains/openapi.yml[]
----

This contract lacks documentation.
The Eclipse MicroProfile OpenAPI allows you to customize the methods of your REST endpoint as well as the application.

[example, role="cta"]
--

While having the OpenAPI specification is great, it can't be consumed easily by humans.
In your browser, go to http://localhost:8084/q/dev.
This is the dev console.
It provides all the tools you need to develop your Quarkus application.
We will use it several times in this workshop.
Note that the dev console is only available in dev mode.

The Dev Console integrates Swagger, a UI to invoke your endpoints from the comfort of your browser.
Click on the "_Swagger UI_" button located in the "SmallRye OpenAPI" widget (http://localhost:8084/q/swagger-ui).

You will see all your endpoints listed.
Click on the "_GET_" button for the "/api/villains" path, then click on "_Try it out_" and finally on "Execute".
You can see the result immediately.
--

When developing REST APIs, this UI is very convenient.
You can test your endpoint and immediately see the outcome.
If something does not please you, edit the code, go back to the browser, re-execute, and voilà!


=== Customizing Methods

The MicroProfile OpenAPI has a set of annotations to customize each REST endpoint method so the OpenAPI contract is richer and clearer for consumers:

* `@Operation`: Describes a single API operation on a path.
* `@APIResponse`: Corresponds to the OpenAPI Response model object which describes a single response from an API Operation
* `@Parameter`: The name of the parameter.
* `@RequestBody`: A brief description of the request body.

[example, role="cta"]
--
This is what the `VillainResource` endpoint should look like once you have annotated it:

[source,java]
----
include::{projectdir}/rest-villains/src/main/java/io/quarkus/workshop/superheroes/villain/VillainResource.java[tag=!adocJavadoc]
----

With this new code, go back to the Swagger UI at http://localhost:8084/q/swagger-ui and refresh.
Your endpoints are organized by tags, and each annotated endpoint is documented.
--

Documenting REST API is essential when working with different teams.
You can see OpenAPI as the JavaDoc for REST.

=== Customizing the Application

The previous annotations allow you to customize the contract for a given REST Endpoint.
But it's also important to document the entire application.

The Microprofile OpenAPI also has a set of annotation to do so.
The difference is that these annotations cannot be used on the endpoint methods, but instead on another Java class configuring the entire application.

[example, role="cta"]
--

For this, you need to create the `src/main/java/io/quarkus/workshop/superheroes/villain/VillainApplication` class with the following content:

[source,java,subs="attributes+"]
----
include::{projectdir}/rest-villains/src/main/java/io/quarkus/workshop/superheroes/villain/VillainApplication.java[]
----

Go back to the Swagger UI and refresh again.
At the top of the document, you can see the version and the global API documentation.
--

=== Customized Contract

[example, role="cta"]
--

If you go back to the `http://localhost:8084/q/openapi` endpoint you will see the following OpenAPI contract:

[source,yaml]
----
include::{projectdir}/rest-villains/openapi-custom.yml[]
----

You can expose or exchange this contract to the API consumers, so they now what to expect when using your API.
--

== OpenAPI Tests in VillainResourceTest

[example, role="cta"]
--

Let's add an extra test method in `VillainResourceTest` ensuring that the OpenAPI specification is packaged with the application:

[source,java,indent=0]
----
include::{projectdir}/rest-villains/src/test/java/io/quarkus/workshop/superheroes/villain/VillainResourceTest.java[tag=adocMethodPingOpenAPI]
----

Run the test:

 - From the dev mode, or
 - By executing the test using `./mvnw test`.
--

include::../common-solution.adoc[]

