[[rest-bootstrapping]]
= Villain Microservice

First thing first, we need a project.
That's what you are going to see in this section.

== Bootstrapping the Villain REST Endpoint

The easiest way to create a new Quarkus project is to use the Quarkus Maven plugin.
Open a terminal and run the following command:

[example, role="cta"]
--

[source,shell,subs="attributes+"]
----
cd quarkus-workshop-super-heroes/super-heroes

./mvnw io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DplatformVersion={quarkus-version} \
    -DprojectGroupId=io.quarkus.workshop.super-heroes \
    -DprojectArtifactId=rest-villains \
    -DclassName="io.quarkus.workshop.superheroes.villain.VillainResource" \
    -Dpath="api/villains" \
    -Dextensions="resteasy-reactive-jackson"
----

[NOTE]
====
Notice that we scaffold the project with a reactive implementation of RestEasy (`resteasy-reactive-jackson`).
This is the recommended way to develop REST applications with Quarkus even if we use the imperative programming model in the Villain microservice.
====

Remember that `mvnw` is the maven wrapper. It behaves like `mvn`,
but allows a project's build dependencies to be encapsulated.

The last line selects the extension we want to use.
As a start, we only select `resteasy-reactive-jackson`, which will also import `resteasy-reactive`.

If you want your IDE to manage this new Maven project, you can declare it in the parent POM by adding this new module in the `<modules>` section:

[source,xml]
----
<module>super-heroes/rest-villains</module>
----
--
[TIP]
.Prefer a Web UI?
====
Instead of the Maven command, you can use https://code.quarkus.io and select the `resteasy-reactive-jackson` extension.
====

== Directory Structure

Once you bootstrap the project, you get the following directory structure with a few Java classes and other artifacts :

[plantuml]
----
@startsalt
{
{
T
super-heroes
+  rest-villains
++  .mvn
++  src
+++  main
++++  docker
+++++  Dockerfile.jvm
+++++  Dockerfile.legacy-jar
+++++  Dockerfile.native
+++++  Dockerfile.native-micro
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  villain
++++++++++  VillainResource.java
++++  resources
+++++  META-INF
++++++  resources
+++++++  index.html
+++++  application.properties
+++  test
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  villain
++++++++++  VillainResourceIT.java
++++++++++  VillainResourceTest.java
++  .dockerignore
++  .gitignore
++  mvnw
++  mvnw.cmd
++  pom.xml
++  README.md
}
}
@endsalt
----

The Maven archetype generates the following `rest-villains` sub-directory:

* The Maven structure with a `pom.xml`
* An `io.quarkus.workshop.superheroes.villain.VillainResource` resource exposed on `/api/villains`
* An associated unit test `VillainResourceTest`
* The landing page `index.html` that is accessible on http://localhost:8080 after starting the application
* Example `Dockerfile` files for both native and JVM modes in `src/main/docker`
* The `application.properties` configuration file

Once generated, look at the `pom.xml`.
You will find the import of the Quarkus BOM, allowing you to omit the version on the different Quarkus dependencies.
In addition, you can see the `quarkus-maven-plugin` responsible for the packaging of the application and providing the development mode.

[source,xml,indent=0,subs="attributes+"]
----
<project>
  <!-- ... -->
  <properties>
    <compiler-plugin.version>{compiler-plugin-version}</compiler-plugin.version>
    <maven.compiler.release>{jdk-version}</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>{quarkus-version}</quarkus.platform.version>
    <skipITs>true</skipITs>
    <surefire-plugin.version>{surefire-plugin-version}</surefire-plugin.version>
  </properties>
  <!-- ... -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <!-- ... -->
  <build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
     <!-- ... -->
    </plugins>
  </build>
<!-- ... -->
</project>
----

If we focus on the dependencies section, you can see the extensions allowing the development of REST applications (resteasy-reactive and resteasy-reactive-jackson)

[source,xml,indent=0]
----
<dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <!-- ... -->
</dependencies>
----

`quarkus-arc` is the dependency injection framework integrated into Quarkus.
It's designed to perform build-time injections.
We will see later why this is essential for Quarkus.

`resteasy-reactive` is the framework we will use to implement our REST API.
It uses JAX-RS annotations such as `@Path`, `@GET`...
`reasteasy-reactive-jackson` adds JSON object mapping capabilities to RESTEasy reactive.

== The Villain Resource

During the project creation, the `VillainResource.java` file has been created with the following content:

[source,java]
----
package io.quarkus.workshop.superheroes.villain;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/api/villains")
public class VillainResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from RESTEasy Reactive";
    }
}
----

It's a very simple REST endpoint returning a "Hello World" to requests on `/api/villains`.
It uses JAX-RS annotations:

- `@Path` indicates the HTTP path handled by the resource,
- `@GET` indicates that the method should be called when receiving a `GET` request on `/api/villains`.

NOTE: Methods can also have their own `@Path` annotation suffixed to the class one (if any).

== Running the Application

[example, role="cta"]
--

Now we are ready to run our application.

Use: `./mvnw quarkus:dev` in the `rest-villains` directory:

[source,shell,,subs="attributes+"]
----
$ ./mvnw quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] -----------< io.quarkus.workshop.super-heroes:rest-villains >-----------
[INFO] Building rest-villains 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:{quarkus-version}:dev (default-cli) @ rest-villains ---
[INFO] Invoking resources:{quarkus-version}:resources (default-resources) @ rest-villains
[INFO] Copying 2 resources from src/main/resources to target/classes
[INFO] Invoking quarkus:{quarkus-version}:generate-code (default) @ rest-villains
[INFO] Invoking compiler:{compiler-plugin-version}:compile (default-compile) @ rest-villains
[INFO] Nothing to compile - all classes are up to date
[INFO] Invoking resources:{quarkus-version}:testResources (default-testResources) @ rest-villains
[INFO] skip non existing resourceDirectory /Users/agoncal/Documents/Code/Temp/quarkus-super-heroes/super-heroes/rest-villains/src/test/resources
[INFO] Invoking quarkus:{quarkus-version}:generate-code-tests (default) @ rest-villains
[INFO] Invoking compiler:{compiler-plugin-version}:testCompile (default-testCompile) @ rest-villains
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 5005

__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-11-15 14:05:29,414 INFO  [io.quarkus] (Quarkus Main Thread) rest-villains 1.0.0-SNAPSHOT on JVM (powered by Quarkus {quarkus-version}) started in 1.093s. Listening on: http://localhost:8080

2022-11-15 14:05:29,423 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-11-15 14:05:29,423 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]

Tests paused
Press [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>
----

Then check that the endpoint returns `hello` as expected:

[source,shell]
----
curl http://localhost:8080/api/villains

Hello from RESTEasy Reactive
----

Alternatively, you can open http://localhost:8080/api/villains in your browser.
--

== Development Mode

`quarkus:dev` runs Quarkus in development mode.
It enables hot deployment with background compilation, which means that when you modify your Java files or your resource files and invoke a REST endpoint (i.e., cURL command or refresh your browser), these changes will automatically take effect.
It works too for resource files like the configuration property and HTML files.
Refreshing the browser triggers a scan of the workspace, and if any changes are detected, the Java files are recompiled and the application is redeployed; your request is then serviced by the redeployed application.
If there are any issues with compilation or deployment an error page will let you know.

The development mode also allows debugging and listens for a debugger on port 5005.
If you want to wait for the debugger to attach before running, you can pass `-Dsuspend=true` on the command line.
If you don't want the debugger at all, you can use `-Ddebug=false`.

Alright, time to change some code.
Open your favorite IDE and import the project.
To check that the hot reload is working, update the `VillainResource.hello()` method by returning the String "_Hello Villain Resource_".

Now, execute the cURL command again:

[example, role="cta"]
--

[source,shell]
----
curl http://localhost:8080/api/villains

Hello Villain Resource
----

The output has changed without you having to stop and restart Quarkus!
--

== Testing the Application

All right, so far, so good, but wouldn't it be better with a few tests, just in case.

In the generated `pom.xml` file, you can see two test dependencies:

[source,xml,indent=0]
----
<dependencies>
    <!-- ... -->
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-junit5</artifactId>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rest-assured</groupId>
        <artifactId>rest-assured</artifactId>
        <scope>test</scope>
    </dependency>
</dependencies>
----

So, we will use Junit 5 combined with RESTAssured, which eases the testing of REST applications.

If you look at the `maven-surefire-plugin` configuration in the `pom.xml`, you will see that we set the `java.util.logging` system property to ensure tests will use the correct method log manager.

[source,xml]
----
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${surefire-plugin.version}</version>
    <configuration>
      <systemPropertyVariables>
        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
        <maven.home>${maven.home}</maven.home>
      </systemPropertyVariables>
    </configuration>
</plugin>
----

The generated project contains a simple test in `VillainResourceTest.java`.

[source,java]
----
package io.quarkus.workshop.superheroes.villain;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
public class VillainResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/api/villains")
          .then()
             .statusCode(200)
             .body(is("Hello from RESTEasy Reactive"));
    }

}
----

By using the `QuarkusTest` runner, the `VillainResourceTest` class instructs JUnit to start the application before the tests.
Then, the `testHelloEndpoint` method checks the HTTP response status code and content.
Notice that these tests use RestAssured, but feel free to use your favorite library.footnote:[RestAssured http://rest-assured.io]

[NOTE]
====
Quarkus provides a RestAssured integration that updates the default port used by RestAssured before the tests are run.
So in your RestAssured tests, you don't have to specify the default test port 8081 used by Quarkus.
You can also configure the ports used by tests by configuring the `quarkus.http.test-port` property in the application.properties.
====

[example, role="cta"]
--

In the terminal running the application in _dev mode_, you should see at the bottom:

[source,text]
----
Tests paused
Press [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>
----

--

Hit the `r` key, and watch Quarkus execute your tests automatically and even continuously.
Unfortunately, this first run didn't end well:

[source,text]
----
2022-11-15 14:13:17,924 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #1 ====================
2022-11-15 14:13:17,925 ERROR [io.qua.test] (Test runner thread) Test VillainResourceTest#testHelloEndpoint() failed
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: is "Hello from RESTEasy Reactive"
  Actual: Hello Villain Resource

        at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
        at io.quarkus.workshop.superheroes.villain.VillainResourceTest.testHelloEndpoint(VillainResourceTest.java:18)


2022-11-15 14:13:17,927 ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> Summary: <<<<<<<<<<<<<<<<<<<<
io.quarkus.workshop.superheroes.villain.VillainResourceTest#testHelloEndpoint(VillainResourceTest.java:18) VillainResourceTest#testHelloEndpoint() 1 expectation failed.
Response body doesn't match expectation.
Expected: is "Hello from RESTEasy Reactive"
  Actual: Hello Villain Resource

2022-11-15 14:13:17,929 ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> 1 TEST FAILED <<<<<<<<<<<<<<<<<<<<

2022-11-15 14:13:18,155 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #2 ====================
2022-11-15 14:13:18,155 ERROR [io.qua.test] (Test runner thread) Test VillainResourceTest#testHelloEndpoint() failed
: java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: is "Hello from RESTEasy Reactive"
  Actual: Hello Villain Resource

        at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
        at io.quarkus.workshop.superheroes.villain.VillainResourceTest.testHelloEndpoint(VillainResourceTest.java:18)


2022-11-15 14:13:18,156 ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> Summary: <<<<<<<<<<<<<<<<<<<<
io.quarkus.workshop.superheroes.villain.VillainResourceTest#testHelloEndpoint(VillainResourceTest.java:18) VillainResourceTest#testHelloEndpoint() 1 expectation failed.
Response body doesn't match expectation.
Expected: is "Hello from RESTEasy Reactive"
  Actual: Hello Villain Resource

2022-11-15 14:13:18,157 ERROR [io.qua.test] (Test runner thread) >>>>>>>>>>>>>>>>>>>> 1 TEST FAILED <<<<<<<<<<<<<<<<<<<<
----

It fails! It's expected, you changed the output of `VillainResource.hello()` earlier.
Adjust the test body condition accordingly:

[source,java]
----
package io.quarkus.workshop.superheroes.villain;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
public class VillainResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/api/villains")
          .then()
             .statusCode(200)
             .body(is("Hello Villain Resource"));
    }

}
----

Save the file, and watch the dev mode automatically rerunning your test (and passing)

[source,text]
----
--
2022-11-15 14:15:22,997 INFO  [io.qua.test] (Test runner thread) All tests are now passing
--
All 1 test is passing (0 skipped), 1 test was run in 186ms. Tests completed at 14:15:23.
Press [r] to re-run, [o] Toggle test output, [:] for the terminal, [h] for more options>
----

Continuous testing is a big part of Quarkus development.
Quarkus detects and runs the tests for you.

You can also run the tests from a terminal using:

[source,shell]
----
./mvnw test
----

== Packaging and Running the Application

[example, role="cta"]
--

The application is packaged using the `./mvnw package` command (it also runs the tests).
That command generates:

* `target/rest-villains-1.0.0-SNAPSHOT.jar`: containing just the classes and resources of the projects, it's the regular artifact produced by the Maven build (it is not an executable jar);
* `target/quarkus-app/` : this directory uses the _fast jar_ packaging. It contains an executable jar (`quarkus-run.jar`), and all the dependencies (structured into `app`, `lib` and `quarkus`).

This _fast jar_ takes advantage of the build-time principle of Quarkus (we discuss it soon) to improve the application performances and which can be easily transposed to container layers.

Stop the application running in dev mode (by hitting `q` or `CTRL+C`), and run the application using: `java -jar target/quarkus-app/quarkus-run.jar`.
--

[NOTE]
====
Before running the application, don't forget to stop the hot reload mode (hit CTRL+C), or you will have a port conflict.
====

[WARNING]
====
.Troubleshooting

You might come across the following error while developing:

[source,shell]
----
WARN  [io.qu.ne.ru.NettyRecorder] (Thread-48) Localhost lookup took more than one second; you need to add a /etc/hosts entry to improve Quarkus startup time. See https://thoeni.io/post/macos-sierra-java/ for details.
----

If this is the case, it's just a matter of adding the node name of your machine to the /etc/hosts.
For that, first, get the name of your node with the following command:

[source,shell]
----
$ uname -n
my-node.local
----

Then `sudo vi /etc/hosts` so you have the right to edit the file and add the following entry:

[source,shell]
----
127.0.0.1 localhost my-node.local
----

====

In another terminal, check that the application runs using:

[source,shell]
----
curl http://localhost:8080/api/villains
Hello Villain Resource
----
