@startuml
!include style.puml

left to right direction

node "Super Hero UI" as ui {
    agent "Quarkus" <<frontend>> as uiQuarkus
}

node "Hero" as hero {
    agent "Quarkus (reactive)" <<application>> as heroQuarkus
    database "Postgresql" as heroPostgresql
    heroQuarkus .up> heroPostgresql
}

node "Villain" as villain {
    agent "Quarkus (imperative)" <<application>> as villainQuarkus
    database "Postgresql" as villainPostgresql
    villainQuarkus .up> villainPostgresql
}

node "Fight" as fight {
    agent "Quarkus" <<application>> as fightQuarkus
    database "Postgresql" as fightPostgresql
    fightQuarkus .up> fightPostgresql
}

uiQuarkus -[hidden]-> fightQuarkus : HTTP
fightQuarkus -[hidden]-> heroQuarkus : HTTP
fightQuarkus -[hidden]-> villainQuarkus : HTTP
@enduml
