@startuml
!include style.puml

skinparam RankSep 20

left to right direction

node "Villain" as villain {
    agent "Quarkus" as villainQuarkus <<application>>
    database "Postgresql" as villainPostgresql
    villainQuarkus .up> villainPostgresql
}

REST ()-- villainQuarkus

@enduml
