[[cloud]]
= Containers & Cloud (optional)

:icons: font

'''

This chapter explores how you can deploy Quarkus applications in containers and Cloud platforms.
There are many different approaches to achieve these deployments.
In this chapter, we are focusing on the creation of containers using Quarkus java executables and the deployment of our system in OpenShift using the https://quarkus.io/guides/deploying-to-openshift[Quarkus OpenShift extension].

== Build and Deploy (in a single step)

Add the OpenShift extension running the following command in the rest-heroes directory:

[source, shell]
----
./mvnw quarkus:add-extension -Dextensions="openshift"
----

Some properties need to be added to the `application.properties` file of each microservice. Edit the file and add:

[source, properties]
--
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-client.namespace=${PROJECT_NAME:USERNAME-heroes}

quarkus.openshift.expose=true
--

The expose parameter’s purpose is to expose the service to clients outside the cluster via `Route`.

[NOTE]
--
Make sure you change USERNAME with your own
--

To trigger the build and deployment in a single step, run the following command. Make sure that you are logged and using the `USERNAME-heroes` project.

[source, shell]
----
$ oc login
$ oc project USERNAME-heroes
$ ./mvnw clean package -Dquarkus.kubernetes.deploy=true
----

The aforementioned command will build a jar file locally, trigger a container image build and then apply the generated OpenShift resources.
To confirm the above command has created an image stream, a service resource and has deployed the application (has a pod running), you can run these commands:

[source, shell]
----
oc get is
oc get pods
oc get svc
----

If everything went well the URL of the microservice should be logged in the console where you ran the build&deploy command:

----
[INFO] [io.quarkus.container.image.openshift.deployment.OpenshiftProcessor] Push successful
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Deploying to openshift server: https://api.cluster-2599.2599.example.opentlc.com:6443/ in namespace: user2-heroes.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Service rest-hero.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: ImageStream openjdk-11.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: ImageStream rest-hero.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: BuildConfig rest-hero.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: DeploymentConfig rest-hero.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] Applied: Route rest-hero.
[INFO] [io.quarkus.kubernetes.deployment.KubernetesDeployer] The deployed application can be accessed at: http://rest-hero-user2-heroes.apps.cluster-2599.2599.example.opentlc.com
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 86106ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:39 min
[INFO] Finished at: 2020-11-11T12:57:24Z
[INFO] ------------------------------------------------------------------------
----

=== Deploying the others microservices

For villain microservice follow the same approach.

==== Fight microservice

* Add the OpenShift extension running the following command in the rest-fights directory:

[source, shell]
----
./mvnw quarkus:add-extension -Dextensions="openshift"
----

* Add the following properties in the rest-fights `application.properties` file:

[source, properties]
--
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-client.namespace=${PROJECT_NAME:USERNAME-heroes}

quarkus.openshift.expose=true
--

* Also, we need to configure the new locations of the hero and villain microservice.
Edit the `application.properties` file and modify the following properties:

[source,properties]
----
include::{github-raw}/super-heroes/rest-fight/src/main/resources/application.properties[tag=adocOpenShiftRestClient]
----

Trigger the build and deployment, run the following command. Make sure that you are logged and using the `USERNAME-heroes` project.

[source, shell]
----
$ oc login
$ oc project USERNAME-heroes
$ ./mvnw clean package -Dquarkus.kubernetes.deploy=true
----

==== UI microservice

* Add the OpenShift extension running the following command in the rest-fights directory:

[source, shell]
----
./mvnw quarkus:add-extension -Dextensions="openshift"
----

* Add the following properties in the ui-super-heroes `application.properties` file:

[source, properties]
--
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-client.namespace=${PROJECT_NAME:USERNAME-heroes}

quarkus.openshift.expose=true
quarkus.openshift.env.vars.BASE_PATH=${FIGHT_ROUTE}
--

The `` property make the UI able to contact the fight microservice. As it depends on an env var, consider to define it using the following command:

[source, properties]
--
$ export FIGHT_ROUTE=http://$(oc get route -n USERNAME-heroes | grep fight | awk '{ print $2 }')
--
[NOTE]
--
Don't forget use your own user
--

Trigger the build and deployment, run the following command. Make sure that you are logged and using the `USERNAME-heroes` project.

[source, shell]
----
$ oc login
$ oc project USERNAME-heroes
$ ./mvnw clean package -Dquarkus.kubernetes.deploy=true
----


Once everything is configured and deployed, your system is now running on OpenShift.
