[[cloud]]
= Containers & Cloud (optional)

:icons: font

'''

This chapter explores how you can deploy Quarkus applications in containers and Cloud platforms.
There are many different approaches to achieve these deployments.
In this chapter, we are focusing on the creation of containers using Quarkus native executables and the deployment of our system in Kubernetes/OpenShift.

== From bare metal to containers

In this section, we are going to package our microservices into containers.
In particular, we are going to produce Linux 64 bits native executables and runs them in a container.
The native compilation uses the OS and architecture of the host system.

And... Linux Containers are ... _Linux_.
So before being able to build a container with our native executable, we need to produce compatible native executables.
If you are using a Linux 64 bits machine, you are good to go.
If not, Quarkus comes with a trick to produce these executable:

[source, shell]
----
$ mvn clean package -Pnative -Dnative-image.docker-build=true -DskipTests
----

The `-Dnative-image.docker-build=true` allows running the native compilation inside a container (provided by Quarkus).
The result is a Linux 64 bits executable.

[TIP]
====
Building a native executable takes time, CPU, and memory.
It's even more accurate in the container.
So, first, be sure that your container system has enough memory to build the executable.
It requires at least 6Gb of memory, 8Gb is recommended.
====

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Execute the above command for all our microservices.
We also copy the UI into the fight service, to simplify the process:

[source, shell]
----
cd rest-hero
mvn clean package -Pnative -Dnative-image.docker-build=true -DskipTests
cd ..
cd rest-villain
mvn clean package -Pnative -Dnative-image.docker-build=true -DskipTests
cd ..
cd rest-fight
cp -R ../ui-super-heroes/dist/* src/main/resources/META-INF/resources
mvn clean package -Pnative -Dnative-image.docker-build=true -DskipTests
cd ..
cd event-statistics
mvn clean package -Pnative -Dnative-image.docker-build=true -DskipTests
cd ..
----

== Building containers

Now that we have the native executables, we can build containers.
When you create projects, Quarkus generates two `Dockerfiles`:

1. `Dockerfile.jvm` - A `Dockerfile` for running the application in JVM mode
2. `Dockerfile.native` - A `Dockerfile` for running the application in native mode

We are interested in this second file.
Open one of these `Dockerfile.native` files:

[source, text]
----
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
----

It's a pretty straightforward `Dockerfile` taking a minimal base image and copying the generated native executable.
It also exposes the port 8080.
Wait, our microservices are not configured to run on the port 8080.
We need to override this property as well as a few other such as the HTTP client endpoints, and database locations.

To build the containers, use the following scripts:

[source, shell]
----
export ORG=xxxx
cd rest-hero
docker build -f src/main/docker/Dockerfile.native -t $ORG/quarkus-workshop-hero .
cd ..
cd rest-villain
docker build -f src/main/docker/Dockerfile.native -t $ORG/quarkus-workshop-villain .
cd ..
cd rest-fight
docker build -f src/main/docker/Dockerfile.native -t $ORG/quarkus-workshop-fight .
cd ..
cd event-statistics
docker build -f src/main/docker/Dockerfile.native -t $ORG/quarkus-workshop-stats .
cd ..
----

[NOTE]
====
Replace `ORG` with your DockerHub / Quay.io username.
====

== Deploying on Kubernetes

This section is going to deploy our microservices on Kubernetes.
It is required to have access to a Kubernetes or OpenShift cluster.

[IMPORTANT]
====
To deploy your microservices, push the built container images to an image registry accessible by your cluster, such as Quay.io or DockerHub.
====

We recommend using a specific namespace to deploy your system.
In the following sections, we use the `quarkus-workshop` namespace.

=== Deploying the infrastructure

The first thing to deploy is the required infrastructure:

* 3 PostgreSQL instances
* Kafka brokers (3 brokers with 3 Zookeeper to follow the recommended approach)

There are many ways to deploy this infrastructure.
Here, we are going to use two operators:

* PostgreSQL Operator by Dev4Ddevs.com
* Strimzi Apache Kafka Operator by Red Hat

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

With these operators installed, you can create the required infrastructure with the following custom resource definition (CRD):

[source,yaml]
----
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
    name: heroes-database
    namespace: quarkus-workshop
spec:
    databaseCpu: 30m
    databaseCpuLimit: 60m
    databaseMemoryLimit: 512Mi
    databaseMemoryRequest: 128Mi
    databaseName: heroes-database
    databaseNameKeyEnvVar: POSTGRESQL_DATABASE
    databasePassword: superman
    databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
    databaseStorageRequest: 1Gi
    databaseUser: superman
    databaseUserKeyEnvVar: POSTGRESQL_USER
    image: centos/postgresql-96-centos7
    size: 1
----

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

This CRD creates the database for the Hero microservice.
Duplicate this CRD for the fight and villain databases.

For the Kafka broker, create the following CRD:

[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-kafka
  namespace: quarkus-workshop
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.3'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
----

This CRD creates the brokers and the Zookeeper instances.

It's also recommended to create the topic.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

For this, create the following CRD:

[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: fights
  labels:
    strimzi.io/cluster: my-kafka
  namespace: quarkus-workshop
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
----

Once everything is created, you should have the following resources:

[source,shell]
----
$ kubectl get database
NAME                AGE
fights-database     16h
heroes-database     16h
villains-database   16h

$ kubectl get kafka
NAME       DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS
my-kafka   3
----

=== Deploying the Hero & Villain microservices

Now that the infrastructure is in place, we can deploy our microservices.
Let's start with the hero and villain microservices.

For each, we need to override the port and data source URL.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Create a config map with the following content:

[source,yaml]
.config-hero.yaml
----
apiVersion: v1
data:
    port: "8080"
    database: "jdbc:postgresql://heroes-database:5432/heroes-database"
kind: ConfigMap
metadata:
    name: hero-config
----

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Do the same for the villain microservice.
Then, apply these resources:

[source,shell]
----
$ kubectl -f config-hero.yaml
$ kubectl -f config-villain.yaml
----

Once the config maps are created, we can deploy the microservices.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Create a `deployment-hero.yaml` file with the following content:

[source,yaml]
----
---
apiVersion: "v1"
kind: "List"
items:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
          labels:
              app: "quarkus-workshop-hero"
              version: "01"
              group: "$ORG"
          name: "quarkus-workshop-hero"
      spec:
          ports:
              - name: "http"
                port: 8080
                targetPort: 8080
          selector:
              app: "quarkus-workshop-hero"
              version: "01"
              group: "$ORG"
          type: "ClusterIP"
    - apiVersion: "apps/v1"
      kind: "Deployment"
      metadata:
          labels:
              app: "quarkus-workshop-hero"
              version: "01"
              group: "$ORG"
          name: "quarkus-workshop-hero"
      spec:
          replicas: 1
          selector:
              matchLabels:
                  app: "quarkus-workshop-hero"
                  version: "01"
                  group: "$ORG"
          template:
              metadata:
                  labels:
                      app: "quarkus-workshop-hero"
                      version: "01"
                      group: "$ORG"
              spec:
                  containers:
                      - image: "$ORG/quarkus-workshop-hero:latest"
                        imagePullPolicy: "IfNotPresent"
                        name: "quarkus-workshop-hero"
                        ports:
                            - containerPort: 8080
                              name: "http"
                              protocol: "TCP"
                        env:
                            - name: "KUBERNETES_NAMESPACE"
                              valueFrom:
                                  fieldRef:
                                      fieldPath: "metadata.namespace"

                            - name: QUARKUS_DATASOURCE_URL
                              valueFrom:
                                  configMapKeyRef:
                                      name: hero-config
                                      key: database

                            - name: QUARKUS_HTTP_PORT
                              valueFrom:
                                  configMapKeyRef:
                                      name: hero-config
                                      key: port


----

This descriptor declares:

1. A service to expose the HTTP endpoint
2. A deployment that instantiates the application

The deployment declares one container using the container image we built earlier.
It also overrides the configuration for the HTTP port and database URL.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Don't forget to create the equivalent files for the villain microservice.

Then, deploy the microservice with:

[source,shell]
----
$ kubectl apply -f deployment-hero.yaml
$ kubectl apply -f deployment-villain.yaml
----

=== Deploying the Fight microservice

Follow the same approach for the fight microservice.
Note that there are more properties to configure from the config map:

*  the location of the hero and villain microservice
* the location of the Kafka broker.

Once everything is configured and deployed, your system is now running on Kubernetes.
