[[fault-tolerance-rest-client]]
= REST Client

:icons: font

This chapter explains how to use the MicroProfile REST Client in order to interact with REST APIs with very little effort.footnote:[MicroProfile REST Client https://github.com/eclipse/microprofile-rest-client]

== Directory Structure

Remember the structure of the Fight microservice:

[plantuml]
----
@startsalt
{
{
T
.
+ src
++ main
+++ docker
+++ java
++++ io
+++++ quarkus
++++++ workshop
+++++++ superheroes
++++++++ fight
+++++++++ Fight.java
+++++++++ FightApplication.java
+++++++++ FightResource.java
+++++++++ FightService.java
+++++++++ Fighters.java
+++++++++ client
+++++++++++ Hero.java
+++++++++++ Villain.java
+++ resources
++++ META-INF
+++++ resources
++++++ index.html
+++++ application.properties
+++++ import.sql
++ test
+++ java
++++ io
+++++ quarkus
++++++ workshop
++++++++ superheroes
+++++++++ fight
++++++++++ FightResourceTest.java
+ pom.xml
}
}
@endsalt
----

We are going to rework the:

* `FightService` class
* `FightResourceTest` class
* `application.properties`

== Installing the REST Client Dependency

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

To install the MicroProfile REST Client dependency, just run the following command:

[source,shell]
----
$ ./mvnw quarkus:add-extension -Dextensions="rest-client"
----

This will add the following dependency in the `pom.xml` file:

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/rest-fight/pom.xml[tags=adocRestClientDependency]
----

== FightService Invoking External Microservices

Remember that in the previous sections we left the `FightService.findRandomFighters()` method returns `null`.
We have to fix this.
What we actually want is to invoke both the Hero and Villain APIs, asking for a random hero and a random villain.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

For that, replace the `findRandomFighters` method with the following code to the `FightService` class:

[source,indent=0]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/FightService.java[tags=adocRestClient;!adocFallback]
----

Note that in addition to the standard CDI `@Inject` annotation, we also need to use the MicroProfile `@RestClient` annotation to inject `HeroService` and `VillainService`.

[NOTE]
--
If not done automatically by your IDE, add the following import statement: `import org.eclipse.microprofile.rest.client.inject.RestClient;`
--

== Creating the Interfaces

Using the MicroProfile REST Client is as simple as creating an interface using the proper JAX-RS and MicroProfile annotations.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

In our case both interfaces should be created under the `client` subpackage and have the following content:

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/client/HeroService.java[tag=adocRestClient]
----

The `findRandomHero` method gives our code the ability to query a random hero from the Hero REST API.
The client will handle all the networking and marshalling leaving our code clean of such technical details.

The purpose of the annotations in the code above is the following:

* `@RegisterRestClient` allows Quarkus to know that this interface is meant to be available for CDI injection as a REST Client
* `@Path` and `@GET` are the standard JAX-RS annotations used to define how to access the service
* `@Produces` defines the expected content-type

The `VillainService` is very similar and looks like this:

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/client/VillainService.java[tag=adocRestClient]
----

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Once created, go back to the `FightService` class and add the following import statements:

[source]
--
import io.quarkus.workshop.superheroes.fight.client.HeroService;
import io.quarkus.workshop.superheroes.fight.client.VillainService;
--

== Configuring REST Client Invocation

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

In order to determine the base URL to which REST calls will be made, the REST Client uses configuration from `application.properties`.
The name of the property needs to follow a certain convention which is best displayed in the following code:

[source,properties]
----
include::{github-raw}/super-heroes/rest-fight/src/main/resources/application.properties[tag=adocRestClient]
----

Having this configuration means that all requests performed using `HeroService` will use http://localhost:8083 as the base URL.
Using this configuration, calling the `findRandomHero` method of `HeroService` would result in an HTTP GET request being made to http://localhost:8083/api/heroes/random.

Having this configuration means that the default scope of `HeroService` will be `@Singleton`.
Supported scope values are `@Singleton`, `@Dependent`, `@ApplicationScoped` and `@RequestScoped`.
The default scope is `@Dependent`.
The default scope can also be defined on the interface.

Now, go back in the UI and refresh, you should see some pictures!

== Updating the Test with Mock Support

But, now we have another problem.
To run the tests of the Fight API we need the Hero and Villain REST APIs to be up and running.
To avoid this, we need to Mock the `HeroService` and `VillainService` interfaces.

Quarkus supports the use of mock objects using the CDI `@Alternative` mechanism.footnote:[Alternatives https://docs.jboss.org/weld/reference/latest/en-US/html/beanscdi.html#_alternatives]

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

To use this simply override the bean you wish to mock with a class in the `src/test/java` directory, and put the `@Alternative` and `@Priority(1)` annotations on the bean.
Alternatively, a convenient `io.quarkus.test.Mock` stereotype annotation could be used.
This built-in stereotype declares `@Alternative`, `@Priority(1)` and `@Dependent`.
So, to mock the `HeroService` interface we just need to implement the following `MockHeroService` class:

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/test/java/io/quarkus/workshop/superheroes/fight/client/MockHeroService.java[tag=adocTest]
----

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Do the same for the `MockVillainService`:

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/test/java/io/quarkus/workshop/superheroes/fight/client/MockVillainService.java[tag=adocTest]
----

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Finally, edit the `FightResourceTest` and add the following method:

[source]
--
include::{github-raw}/super-heroes/rest-fight/src/test/java/io/quarkus/workshop/superheroes/fight/FightResourceTest.java[tag=adocRandom]
--

[NOTE]
====
You would need the following import statements:
```
import io.quarkus.workshop.superheroes.fight.client.MockHeroService;
import io.quarkus.workshop.superheroes.fight.client.MockVillainService;
```
====

== Running and Testing the Application

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

First, make sure the tests pass by executing the command `./mvnw test` (or from your IDE).

Now that the tests are green, we are ready to run our application.
Use `./mvnw compile quarkus:dev` to start it.
Once the application is started, go to http://localhost:8080 and start fighting (finally !).
