[[introduction-preparing]]
= Preparing for the Workshop

This workshop needs internet access to download all sorts of Maven artifacts, Docker images and even pictures.
Some of these artifacts are large, and because we have to share internet connexions at the workshop, it is better to download them prior to the workshop.
Here are a few commands that you can execute before the workshop.

== Creating the Directories Structure

In this workshop you will be developing an application dealing with Super Heroes (and Super Villains 🦹) as well as Quarkus extensions.
The code will be separated into two different directories:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ extensions           | The Quarkus extensions
+ super-heroes         | The entire Super Hero application
}
}
@endsalt
----

=== Super Heroes Application

Under the `super-heroes` directory you will find the entire Super Hero application spread throughout a set of subdirectories, each one containing a microservice or some tooling.

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes
++ infrastructure          | All the needed infrastructure (Postgres, Kafka...)
++ event-statistics        | UI and application dealing with fight statistics
++ load-super-heroes       | Stress tool loading heroes, villains and fights
++ rest-fight              | REST API allowing super heroes to fight
++ rest-hero               | REST API for CRUD operations on Heroes
++ rest-villain            | REST API for CRUD operations on Villains
++ ui-super-heroes         | Angular application so we can fight visually
}
}
@endsalt
----

Most of thses subdirectories are Maven projects and follow the Maven directory structure:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  super-heroes
++ rest-hero
+++ src
++++  main
+++++  docker
+++++  java
+++++  resources
++++  test
+++++  java
}
}
@endsalt
----

=== Quarkus Extensions

Under the `extensions` directory you will find quarkus extensions.

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  extensions
++  extension-banner           | Extension displaying a startup banner
++  extension-fault-injector   | Injects network latency and HTTP faults
}
}
@endsalt
----

=== Script Creating the Directory Structure

So, before starting to code, make sure you create the right directory structure.

[source,shell]
----
include::{github-raw}/create-directory-structure.sh[tags=adocSnippet]
----

== Warming up Maven

To warm up your Maven repository, first bootstrap a Quarkus project using the following command:

[source,shell]
----
include::{github-raw}/super-heroes/rest-hero/bootstrap.sh[tag=adocSnippet]
----

Then, make sure to run a `mvn install` in the directory where the `pom.xml` file is located.

== Warming up Docker

To warm up your Docker repository, download the zip file {github-raw}/super-heroes/infrastructure/infrastructure.zip and unzip the entire code into the `quarkus-workshop-super-heroes/super-heroes/infrastructure` directory.
Here, you will find a `docker-compose.yaml` file which defines all the needed Docker images.
Notice that there is a `db-init` directory with a `initialize-databases.sql` script which sets up our databases and a `monitoring` directory (all that will be explained later).

Then execute `docker-compose -f docker-compose.yaml up -d`.
This will download all the Docker images and start the containers.

[WARNING]
====
If you have an issue creating the roles for the database with the `initialize-databases.sql` file, you have to execute the following commands:

```
docker exec -it --user postgres super-database psql -c "CREATE ROLE superman LOGIN PASSWORD 'superman' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
docker exec -it --user postgres super-database psql -c "CREATE ROLE superbad LOGIN PASSWORD 'superbad' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
docker exec -it --user postgres super-database psql -c "CREATE ROLE superfight LOGIN PASSWORD 'superfight' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION"
```
====

Once all the containers are up and running, you can shut them down with the command `docker-compose -f docker-compose.yaml down`.

[NOTE]
====
.What's this infra?
Any microservice system is going to rely on a set of technical services.
In our context, we are going to use PostgreSQL as the database, Prometheus as the monitoring tool, and Kafka as the event/message bus.
This infrastructure starts all these services, so you don't have to worry about them.
====

== Checking Ports

During this workshop we will use several ports.
Just make sure the following ports are free so you don't run into any conflicts

[source,shell]
----
$ lsof -i tcp:8080    // UI
$ lsof -i tcp:8082    // Fight REST API
$ lsof -i tcp:8083    // Hero REST API
$ lsof -i tcp:8084    // Villain REST API
$ lsof -i tcp:5432    // Postgres
$ lsof -i tcp:9090    // Prometheus
$ lsof -i tcp:2181    // Zookeeper
$ lsof -i tcp:9092    // Kafka
----

== Ready?

Prerequisites has been installed, the different components have been warmed up,  it's now time to write some code!

