[[introduction-preparing]]
= Preparing for the Workshop

:icons: font

This workshop needs internet access to download all sorts of Maven artifacts, Docker images and even pictures.
Some of these artifacts are large, and because we have to share internet connexions at the workshop, it is better to download them prior to the workshop.
Here are a few commands that you can execute before the workshop.

== Download the workshop scaffolding

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

First, download the zip file  {github-raw}/dist/quarkus-workshop-super-heroes.zip, and unzip it wherever you want.

In this workshop you will be developing an application dealing with Super Heroes (and Super Villains 🦹) as well as Quarkus extensions.
The code will be separated into two different directories:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ extensions           | The Quarkus extensions
+ super-heroes         | The entire Super Hero application
}
}
@endsalt
----

=== Super Heroes Application

Under the `super-heroes` directory you will find the entire Super Hero application spread throughout a set of subdirectories, each one containing a microservice or some tooling.
The final structure will be the following:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes
++ infrastructure          | All the needed infrastructure (Postgres, Kafka...)
++ event-statistics        | UI and application dealing with fight statistics (you will create it)
++ load-super-heroes       | Stress tool loading heroes, villains and fights
++ rest-fight              | REST API allowing super heroes to fight (you will create it)
++ rest-hero               | REST API for CRUD operations on Heroes (you will create it)
++ rest-villain            | REST API for CRUD operations on Villains
++ ui-super-heroes         | Angular application so we can fight visually
}
}
@endsalt
----

Most of theses subdirectories are Maven projects and follow the Maven directory structure:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  super-heroes
++ rest-hero
+++ src
++++  main
+++++  docker
+++++  java
+++++  resources
++++  test
+++++  java
}
}
@endsalt
----

=== Quarkus Extensions

Under the `extensions` directory you will find quarkus extensions.
By the end of the workshop, you will get:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  extensions
++  extension-banner           | Extension displaying a startup banner (you will create it)
++  extension-fault-injector   | Injects network latency and HTTP faults
}
}
@endsalt
----

For next steps, you need to be authenticated on OpenShift with your own user

[source,shell]
----
$ oc login ....
$ oc project USERNAME-heroes
----

NOTE: change USERNAME with your own.

== Kafka

You can create the server and topic that will be used during the workshop with the `oc` utility. The OpenShift manifests containing the resources to create can be found under `quarkus-workshop-super-heroes/super-heroes/infrastructure/` directory.

From the CRW terminal where you are authenticated on OpenShift, run:

[source,shell]
----
$ oc apply -f quarkus-workshop-super-heroes/super-heroes/infrastructure/kafka.yaml
----

== Databases

We need to create the 3 databases that we are using. They are described in an OpenShift manifest that can be found under `quarkus-workshop-super-heroes/super-heroes/infrastructure/` directory.

As we did for kafka, we will create the DBs using `oc` utility from the CRW terminal.
Make sure that you are authenticated with your USERNAME and you are using the `USERNAME-heroes` namespace, then apply the databases yaml file:

[source,shell]
----
$ oc apply -f quarkus-workshop-super-heroes/super-heroes/infrastructure/databases.yaml
----

You can verify the availability of databases with the following command:
[source,shell]
----
$ curl http://heroes-database.USERNAME-heroes:5432
----
You should have the following response:

----
curl: (52) Empty reply from server
----


== Warming up Maven

Now that you have the initial structure in place, we just need configure the correct url for the database.

On your CRW, edit the `quarkus-workshop-super-heroes/super-heroes/rest-villain/src/main/resources/application.properties` file and change database configuration:

----
quarkus.datasource.jdbc.url=jdbc:postgresql://villains-database.USERNAME-heroes:5432/villains_database
----

NOTE: Change USERNAME with your own.

Now, you can navigate to the root directory `quarkus-workshop-super-heroes/` and run:

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#


[source,shell]
----
mvn clean install
----

By running this command, it downloads all the required dependencies.

[NOTE]
====
.What's this infra?
Any microservice system is going to rely on a set of technical services.
In our context, we are going to use PostgreSQL as the database, Prometheus as the monitoring tool, and Kafka as the event/message bus.
The infrastructure folder contains the OpenShift manifests to create the OpenShift resources in order to have this techincal service available.
====

== Ready?

Prerequisites has been installed, the different components have been warmed up,  it's now time to write some code!

