[[introduction-presentation]]
= Presentation of the Workshop

== What is this workshop about?

This workshop should give you a good practical introduction to Quarkus.
You will first install all the needed tools to then develop an entire microservice architecture.
You will finish by extending the capabilities of Quarkus.

The idea is that you leave this workshop with a good understanding of what Quarkus is, what it is not, and how it can help you in your projects.
Then, you’ll be prepared to investigate a bit more and, hopefully, contribute.

[NOTE]
====
Get this workshop from https://github.com/quarkusio/quarkus-workshops
====

== What is Quarkus?

== How does this workshop work?

You have this material in your hands (either electronically or printed) and you can now follow it step by step.
The structure of this workshop is as follow :

* Installing all the needed tools:
in this section you will install all the tools and code to be able to develop, compile and execute our application
* Using Quarkus:
in this section you will play with Quarkus so you make sure you understand the basics
* Developing with Quarkus:
in this section you will create a microservice archtiecture by creating several Maven projects, write some Java code, add JPA entities, JAX-RS REST endpoints, write some tests, use an Angular web application, and all that on Quarkus
* Extending Quarkus:
in this section you will create a Quarkus extension

If you already have the tools installed, skip the "Installing all the needed tools" section.
If you already know Quarkus a bit, jump to the sections "Developing with Quarkus" and "Extending Quarkus", and start hacking some code and addons.
This "à la carte" mode allows you to make the most of this 6 hours long hands on lab.

== What do you have to do?

This workshop should be as self explanatory as possible.
So your job is to follow the instructions by yourself, do what you are supposed to do, and do not hesitate to ask for any clarification or assistance, that's why the team is here.
Oh, and be ready to have some fun!

== Software requirements

This workshop will make of the following software, tools, frameworks that you will need to install and now (more or less) how it works.

The following software needs to be downloaded and installed:

* JDK 8
* GraalVM
* Maven 3.3.x
* Docker
* Node JS (optionally)

The next section focuses on how to install and setup the needed software.
You can skip the next section if you
