[[introduction-preparing]]
= Preparing for the Workshop

This workshop needs internet access to download all sorts of Maven artifacts, Docker images and even pictures.
Some of these artifacts are large, and because we have to share internet connexions at the workshop, it is better to download them prior to the workshop.
Here are a few commands that you can execute before the workshop.

== Warming up Maven

To warm up your Maven repository, first bootstrap a Quarkus project using the following command:

[source,shell]
----
include::{github-raw}/super-heroes/rest-hero/bootstrap.sh[tag=adocSnippet]
----

Then, make sure to run a `mvn install` in the directory where the `pom.xml` file is located.

== Warming up Docker

To warm up your Docker repository, create the following `docker-compose.yaml` file :

[source,yaml]
----
include::{github-raw}/super-heroes/infrastructure/docker-compose.yaml[tags=!adocVolumePostgres;!adocVolumePrometheus]
----

Then execute `docker-compose -f docker-compose.yaml up -d`.
This will download all the Docker images and start the containers.
Once all the containers are up and running, you can shut them down with the command `docker-compose -f docker-compose.yaml down`.

[NOTE]
====
.What's this infra?
Any microservice system is going to rely on a set of technical services.
In our context, we are going to use PostgreSQL as the database, Prometheus as the monitoring tool, and Kafka as the event/message bus.
This infrastructure starts all these services, so you don't have to worry about them.
====

== Creating the Directories Structure

In this workshop you will be developing an application dealing with Super Heroes (and Super Villains 🦹) as well as Quarkus extensions.
The code will be separated into two different directories:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ extensions             The Quarkus extensions
+ super-heroes         The entire Super Hero application
}
}
@endsalt
----

=== Super Heroes Application

Under the `super-heroes` directory you will find the entire Super Hero application spread throughout a set of subdirectories, each one containing a microservice or some tooling.

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes
++ infrastructure          All the needed infrastructure (Postgres, Kafka...)
++ event-statistics        UI and application dealing with fight statistics
++ load-super-heroes  Stress tool loading heroes, villains and fights
++ rest-fight                REST API allowing super heroes to fight
++ rest-hero                REST API for CRUD operations on Heroes
++ rest-villain              REST API for CRUD operations on Villains
++ ui-super-heroes     Angular application so we can fight visually
}
}
@endsalt
----

Most of thses subdirectories are Maven projects and follow the Maven directory structure:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  super-heroes
++ rest-hero
+++ src
++++  main
+++++  docker
+++++  java
+++++  resources
++++  test
+++++  java
}
}
@endsalt
----

=== Quarkus Extensions

Under the `extensions` directory you will find quarkus extensions.

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  extensions
++  extension-banner           Extension displaying a startup banner
++  extension-fault-injector   Injects network latency and HTTP faults
}
}
@endsalt
----

=== Script Creating the Directory Structure

So, before starting to code, make sure you create the right directory structure.

[source,shell]
----
include::{github-raw}/create-directory-structure.sh[tags=adocSnippet]
----

== Ready?

Prerequisites has been installed, the different components have been warmed up,  it's now time to write some code!

