[[introduction-installing]]
= Installing Software

== JDK {jdk-version}

Essential for the development and execution of this workshop is the _Java Development Kit_ (JDK).footnote:[Java http://www.oracle.com/technetwork/java/javase]
The JDK includes several tools such as a compiler (`javac`), a virtual machine, a documentation generator (`javadoc`), monitoring tools (Visual VM) and so on.footnote:[Visual VM https://visualvm.github.io]
The code in this workshop uses JDK {jdk-version}.

=== Installing the JDK

To install the JDK {jdk-version}, go to the official website, select the appropriate platform and language, and download the distribution.footnote:[Java Website http://www.oracle.com/technetwork/java/javase/downloads/index.html]
For example, if you are running on Mac OS X, download the DMG file (you should check out the _Accept License Agreement_ check box before hitting the download link to let the download start).
If you are not on Mac, the download steps are still pretty similar.

Instead of the Oracle distribution, you can use AdoptOpenJDK and download the JDK from https://adoptopenjdk.net.
Follows the instructions from https://adoptopenjdk.net/installation.html to download and install the JDK for your platform.

There is also an easier way to download and install Java if you are on Mac OS X.
You can use Homebrew to install JDK jdk-version using the following commands.footnote:[Homebrew https://brew.sh]

[source,shell]
----
$ brew tap caskroom/versions
$ brew cask install java8
----

=== Checking for Java Installation

Once the installation is complete, it is necessary to set the `JAVA_HOME` variable and the `$JAVA_HOME/bin` directory to the `PATH` variable.
Check that your system recognises Java by entering `java -version` as well as the Java compiler with `javac -version`.

[source,shell]
----
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
$ javac -version
javac 1.8.0_201
----

== GraalVM

GraalVM is an extension of the _Java Virtual Machine_ (JVM) to support more languages and several execution modes.footnote:[GraalVM https://www.graalvm.org]
It supports a large set of languages:
Java of course, other JVM-based languages (such as Groovy, Kotlin etc.) but also JavaScript, Ruby, Python, R and  C/C++.
It includes a new high performance Java compiler, itself called _Graal_, which can be used in a _Just-In-Time_ (JIT) configuration on the HotSpot VM, or in an _Ahead-Of-Time_ (AOT) configuration on the Substrate VM.footnote:[SubstrateVM https://github.com/oracle/graal/tree/master/substratevm]
One objective of Graal is to improve the performance of Java virtual machine-based languages to match the performance of native languages.

=== Installing GraalVM

GraalVM installed from the GraalVM web site.footnote:[GraalVM Download https://www.graalvm.org/downloads]
Using the community edition is enough.
Version {graalvm-version} is required.

Once installed, make sure the `GRAALVM_HOME` environment variable configured appropriately and points to the directory where GraalVM is installed (eg. on Mac OS X it will be /Library/Java/JavaVirtualMachines/graalvm-ce-{graalvm-version}/Contents/Home)
The `native-image` tool must be installed;
this can be done by running `gu install native-image` from your GraalVM directory.

[NOTE]
.Mac OS X - Catalina
====
On Mac OS X catalina, the installation of the `native-image` executable may fail.
GraalVM binaries are not (yet) notarized for Catalina.
To bypass the issue, it is recommended to run the following command instead of disabling macOS Gatekeeper entirely:
[source,shell]
-----
xattr -r -d com.apple.quarantine ${GRAAL_VM}
-----
====

=== Checking for GraalVM Installation

Once installed and setup, you should be able to run the following command and get the following output.

[source, shell]
====
$> $GRAALVM_HOME/bin/native-image --version
GraalVM Version 19.2.0.1 CE
====

== Maven 3.3.x

All the examples of this workshop are built and tested using Maven.footnote:[Maven https://maven.apache.org]
Maven offers a building solution, shared libraries, and a plugin platform for your projects, allowing you to do quality control, documentation, teamwork and so forth.
Based on the "convention over configuration" principle, Maven brings a standard project description and a number of conventions such as a standard directory structure.
With an extensible architecture based on plugins, Maven can offer many different services.

=== Installing Maven

The examples of this workshop have been developed with Apache Maven 3.6.x.
Once you have installed JDK {jdk-version}, make sure the `JAVA_HOME` environment variable is set.
Then, download Maven from http://maven.apache.org/, unzip the file on your hard drive, and add the `apache-maven/bin` directory to your `PATH` variable.
More details about the installation process is available on https://maven.apache.org/install.html.

But of course, if you are on Mac OS X and use Homebrew, just install Maven with the following command:

[source,shell]
----
$ brew install maven
----

=== Checking for Maven Installation

Once you've got Maven installed, open a command line and enter mvn `-version` to validate your installation.
Maven should print its version and the JDK version it uses (which is handy as you might have different JDK versions installed on the same machine).

[source,shell]
----
$ mvn -version
Apache Maven 3.6.2
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 1.8.0_201, vendor: Oracle Corporation
OS name: "mac os x", version: "10.14.2", arch: "x86_64", family: "mac"
----

Be aware that Maven needs Internet access so it can download plugins and project dependencies from the Maven Central and/or other remote repositories.footnote:[Maven Central https://search.maven.org]

=== Some Maven Commands

Maven is a command line utility where you can use several parameters and options to build, test or package your code.
To get some help on the commands you can type, use the following command:

[source,shell]
----
$ mvn --help

usage: mvn [options] [<goal(s)>] [<phase(s)>]
----

Here are some commands that you will be using to run the examples in the workshop.
Each invoke a different phase of the project life cycle (clean, compile, install etc.) and use the `pom.xml` to download libraries, customise the compilation, or extend some behaviours with plugins:

* `mvn clean`: Deletes all generated files (compiled classes, generated code, artifacts etc.).
* `mvn compile`: Compiles the main Java classes.
* `mvn test-compile`: Compiles the test classes.
* `mvn test`: Compiles the main Java classes as well as the test classes and executes the tests.
* `mvn package`: Compiles, executes the tests and packages the code into an archive.
* `mvn install`: Builds and installs the artifacts in your local repository.
* `mvn clean install`: Cleans and installs (note that you can add several commands separated by a space, like `mvn clean compile test`).

== cUrl

To invoke the REST Web Services described in this workshop, we often use cURL.footnote:[cURL https://curl.haxx.se]
cURL is a command line tool and library to do reliable data transfers with various protocols, including HTTP.
It is free, open source (available under the MIT Licence) and has been ported to several operating systems.

== Installing cURL

If you are on Mac OS X and if you have installed Homebrew, then installing cURL is just a matter of a single command.footnote:[Homebrew https://brew.sh]
Open your terminal and install cURL with the following command:

[source,shell]
----
$ brew install curl
----

== Checking for cURL Installation

Once installed, check for cURL by running `curl --version` in the terminal.
It should display cURL version:

[source,shell]
----
$ curl --version
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
----

== Some cURL Commands

cURL is a command line utility where you can use several parameters and options to invoke URLs.
You invoke `curl` with zero, one or several command-line options to accompany the URL (or set of URLs) you want the transfer to be about.
cURL supports over two hundred different options and I would recommend reading the documentation for more help.footnote:[cURL commands https://ec.haxx.se/cmdline.html]
To get some help on the commands and options you can type, use the following command:

[source,shell]
----
$ curl --help

Usage: curl [options...] <url>
----

You can also opt to use `curl --manual` which will output the entire man page for cURL plus an appended tutorial for the most common use cases.

Here are some commands that you will be using to invoke the RESTful web service examples in this workshop.

* `curl http://localhost:8083/api/heroes/hello`: HTTP GET on a given URL.
* `curl -X GET http://localhost:8083/api/heroes/hello`: Same effect as the previous command, an HTTP GET on a given URL.
* `curl -v http://localhost:8083/api/heroes/hello`: HTTP GET on a given URL with verbose mode on.
* `curl -H 'Content-Type: application/json' http://localhost:8083/api/heroes/hello`: HTTP GET on a given URL passing the JSON Content Type in the HTTP Header.
* `curl -X DELETE http://localhost:8083/api/heroes/1`: HTTP DELETE on a given URL.

== Formatting the cURL JSON Output

Very often when using cURL to invoke a RESTful web service, we get some JSON payload.
cURL does not format this JSON, so you will get a flat String such as:

[source,shell]
----
$ curl http://localhost:8083/api/heroes
[{"id":"1","name":"Chewbacca","level":"14"},{"id":"2","name":"Wonder Woman","level":"15"},{"id":"3","name":"Anakin Skywalker","level":"8"}]
----

But what we really want is to format the JSON payload so it is easier to read.
For that, there is a neat utility tool called jq that we could use.
jq is a tool for processing JSON inputs, applying the given filter to its JSON text inputs and producing the filter's results as JSON on standard output.footnote:[jq https://stedolan.github.io/jq]
You can install it on Mac OSX with a simple `brew install jq`.
Once installed, it's just a matter of piping the cURL output to jq like this:

[source,shell]
----
$ curl http://localhost:8083/api/heroes | jq
[
  {
    "id": "1",
    "name": "Chewbacca",
    "lastName": "14"
  },
  {
    "id": "2",
    "name": "Wonder Woman",
    "lastName": "15"
  },
  {
    "id": "3",
    "name": "Anakin Skywalker",
    "lastName": "8"
  }
]
----

== Docker

== Recap

Just make sure the following commands work on your machine

[source,shell]
----
$ java -version
$ mvn -version
$ curl --version
$ docker version
$ docker-compose version
----
