[[introduction-preparing]]
= Preparing for the Workshop

This workshop needs internet access to download all sorts of Maven artifacts or Docker images.
Some of these artifacts are large, and because we have to share internet connexions at the workshop, it is better to download them prior to the workshop.
Here are a few commands that you can execute before the workshop.

== Warm up Maven

To warm up your Maven repository, first bootstrap a Quarkus project using the following command:

[source,shell]
----
include::{github-raw}/super-heroes/rest-hero/bootstrap.sh[tag=adocSnippet]
----

Then, make sure to run a `mvn install` in the directory where the `pom.xml` file is located.

== Warm up Docker

To warm up your Docker repository, create the following `docker-compose.yaml` file :

[source,yaml]
----
include::{github-raw}/super-heroes/containers/docker-compose.yaml[tags=!adocVolumePostgres;!adocVolumePrometheus]
----

Then execute `docker-compose -f docker-compose.yaml up -d`.
This will download all the Docker images and start the containers.
Once all the containers are up and running, you can shut them down with the command `docker-compose -f docker-compose.yaml down`.

== Warm up Node JS (optionally)

