= Receiving messages from Kafka

In this section, you are going to see how you can send receives messages from a Kafka topic.
For this, you are going to create a new microservice, named `stats`.
This microservice computes statistics based on the results of the fights.
For example, it determines if villains win more battle than heroes, and who is the superhero or supervillain having won the most fights.

== Creation of the stats microservice

== Bootstrapping the Fight REST Endpoint

Like for the other microservice, the easiest way to create this new Quarkus project is to use a Maven command.
Under the `quarkus-workshop-super-heroes/super-heroes` root directory where you have all your code, create a `event-statistics` sub-directory, open a terminal and run the following command:

[source,shell]
----
include::{github-raw}/super-heroes/event-statistics/bootstrap.sh[tag=adocSnippet]
----

[NOTE]
====
As you can see in the command, you can configure the extensions you want using the `-Dextensions` parameter.
Open the `pom.xml` file to see the result.
====

== Computing statistics

Now, create the `io.quarkus.workshop.superheroes.statistics.SuperStats` class with the following content:

[source,shell]
----
include::{github-raw}/super-heroes/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/SuperStats.java[]
----

In addition, create the `io.quarkus.workshop.superheroes.statistics.FightResult`,  `io.quarkus.workshop.superheroes.statistics.Ranking`, `io.quarkus.workshop.superheroes.statistics.Score` and `io.quarkus.workshop.superheroes.statistics.TeamStats` classes with the following contents:

[source,shell]
.FightResult.java
----
include::{github-raw}/super-heroes/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/FightResult.java[]
----

[source,shell]
.Ranking.java
----
include::{github-raw}/super-heroes/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/Ranking.java[]
----

[source,shell]
.Score.java
----
include::{github-raw}/super-heroes/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/Score.java[]
----

[source,shell]
.TeamStats.java
----
include::{github-raw}/super-heroes/event-statistics/src/main/java/io/quarkus/workshop/superheroes/statistics/TeamStats.java[]
----

The `FightResult` class is used to deserialize the JSON object from the Kafka topic.
Note the `RegisterForReflection` annotation indicating to Quarkus that this class is accessed using reflection.
This information is required when running the application as a native executable.

The `Score` class is a simple structure storing the name of a hero or villain and its actual score, _i.e._ the number of won battles.
The `Ranking` class is used to compute a floating top 10.
The `TeamStats` class is an object keeping track of the number of battles won by heroes and villains.

Let's go back to the `SuperStats` class.
This class contains 3 methods annotated with `@Incoming` and `@Outgoing`.

The first one (`toFightResults`) is responsible for deserializing the JSON content received from Kafka.
It gets items from the `fights` channel and produces items sent to the `results` channel.
It takes a `Flowable` parameter and returns another `Flowable`.
`Flowable` is a class provided by RX Java 2 and represents a stream of data.
So, this method is called only once with a `Flowable` representing the incoming channel, and the returned `Flowable` is the outgoing channel.
In the body of the method, each item from the incoming channel are _mapped_ to `FightResults`.

The `@Broadcast` annotation indicates that several consumers (methods) consume the items produced by the method.

The `computeTeamStats` method follows the same pattern.
It computes the ratio of victories for heroes and villains.

The `computeTopWinners` method uses more advanced reactive programming constructs such as `groupBy`, `flatMap` and `scan`:

[source, java]
----
@Incoming("results")
@Outgoing("winner-stats")
public Flowable<Iterable<Score>> computeTopWinners(Flowable<FightResult> results) {
    return results
        // Create a sub-stream per hero and villain - for each winner, we get a new sub-stream
        .groupBy(FightResult::getWinnerName)
        // For each of these sub-stream
        .flatMap(group ->
            // Compute the new score (increment the score by one)
            group.scan(0, (i, s) -> i + 1)
                // Skip the initial 0, oddity of the scan operator
                .skip(1)
                // Creates the Score object
                .map(i -> new Score(group.getKey(), i)))
        // For every Score emitted by the sub-streams, add it to the
        // ranking object and check if it changes the top 10.
        .flatMapMaybe(score -> topWinners.onNewScore(score));
}
----

== Reading message from Kafka

It's now time to connect the `fights` channel with the Kafka topic.
Edit the `application.properties` file and add the following content:

[source,shell]
----
include::{github-raw}/super-heroes/event-statistics/src/main/resources/application.properties[tag=adocKafka]
----

As for the writing side, it configures the Kafka connector.
The `mp.messaging.incoming.fights.auto.offset.reset=earliest` property indicates that the topic is read from the earliest available record.
Check the Kafka configuration to see all the available settings.

