[[microservices-fight]]
= Fight Microservice

== Bootstrapping the Fight REST Endpoint

Like for the Hero API, the easiest way to create this new Quarkus project is to use a Maven archetype.
Under the `quarkus-workshop-super-heroes/super-heroes` root directory where you have all your code, create a `rest-fight` sub-directory, open a terminal and run the following command:

[source,shell]
----
include::{github-raw}/super-heroes/rest-fight/bootstrap.sh[tag=adocSnippet]
----

== Fight Entity

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/Fight.java[tags=adocEntity;!adocSkip]
----

== Fighters Bean

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/Fighters.java[tags=adocBean;!adocSkip]
----

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/client/Hero.java[tags=adocBean;!adocSkip]
----

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/client/Villain.java[tags=adocBean;!adocSkip]
----

== FightService Transactional Service

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/FightService.java[tags=adocTransactional;!adocRestClient;!adocKafka]
----

[NOTE]
====
For now, just implement two empty methods `villainWon` and `heroWon` which return null.
Later, these methods will invoke the Hello and Villain API to get a random Hello and random Villain
====

== FightResource Endpoint

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/FightResource.java[tags=adocResource;!adocMetrics]
----

== FightApplication for OpenAPI

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/FightApplication.java[tag=adocApplication]
----

[NOTE]
====
Notice that there is no `FightApplicationLifeCycle` class.
We will use a Quarkus extension later on to display a banner for Fight.
====

== FightResourceTest Test Class

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/test/java/io/quarkus/workshop/superheroes/fight/FightResourceTest.java[tags=adocResourceTest;!adocHealth;!adocMetrics]
----

== Configuration

Notice that this instance of Quarkus listens on port 8084

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/resources/application.properties[tags=!adocCORS]
----

== Running, Testing and Packaging the Application

Now we are ready to run our application.
Use: `./mvnw compile quarkus:dev`:

Then check that the endpoint returns `hello` as expected:

[source,shell]
----
$ curl http://localhost:8080/api/heroes
hello
----

http://localhost:8083/swagger-ui` and play with your API.


Execute it with `./mvnw test` or from your IDE.

The application is packaged using `./mvnw package`.
It produces 2 jar files in `/target`:

* `rest-hero-1.0-SNAPSHOT.jar` : containing just the classes and resources of the projects, it’s the regular artifact produced by the Maven build;
* `rest-hero-1.0-SNAPSHOT-runner.jar` : being an executable jar. Be aware that it’s not an über-jar as the dependencies are copied into the `target/lib` directory.

You can run the application using: `java -jar rest-hero-1.0-SNAPSHOT-runner.jar`.

== Directory Structure

At the end you should have the following directory structure:

[source,text]
----
rest-fight/
├── mvnw
├── mvnw.cmd
├── pom.xml
└── src
    ├── main
    │   ├── docker
    │   │   ├── Dockerfile.jvm
    │   │   └── Dockerfile.native
    │   ├── java
    │   │   └── io
    │   │       └── quarkus
    │   │           └── workshop
    │   │               └── superheroes
    │   │                   └── fight
    │   │                       ├── Fight.java
    │   │                       ├── FightApplication.java
    │   │                       ├── FightResource.java
    │   │                       ├── FightService.java
    │   │                       └── Fighters.java
    │   │                           └── KafkaWriter.java
    │   └── resources
    │       ├── META-INF
    │       │   └── resources
    │       │       └── index.html
    │       ├── application.properties
    │       └── import.sql
    └── test
        └── java
            └── io
                └── quarkus
                    └── workshop
                        └── superheroes
                            └── fight
                                └── FightResourceTest.java
----
