[[microservices-villain]]
= Villain Microservice

:icons: font

New microservice, new project!
In this section we will see the counterpart of the Hero microservice: the Villain microservice!
The Villain REST Endpoint is *really* similar to the Hero Endpoint.

The code has already been provided in the `/super-heroes/rest-villain/` directory.
There is almost no differences with the hero microservice, just that it provides super villains instead and uses the port `8084`.

== Directory Structure

As for the hero microservice, you have the following directory structure:

[plantuml]
----
@startsalt
{
{
T
super-heroes
+  rest-villain
++  src
+++  main
++++  docker
+++++  Dockerfile.jvm
+++++  Dockerfile.native
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  villain
++++++++++  Villain.java
++++++++++  VillainApplication.java
++++++++++  VillainApplicationLifeCycle.java
++++++++++  VillainResource.java
++++++++++  VillainService.java
++++  resources
+++++  META-INF
++++++  resources
+++++++  index.html
+++++  application.properties
+++++  import.sql
+++  test
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  villain
++++++++++  VillainResourceTest.java
++  mvnw
++  mvnw.cmd
++  pom.xml
}
}
@endsalt
----

If you look at the code, it's very similar to the hero microservice.

== Running, Testing and Packaging the Application

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

First, make sure the tests pass by executing the command `./mvnw test` (or from your IDE).

Now that the tests are green, we are ready to run our application.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Use `./mvnw quarkus:dev` to start it (notice the nice banner).
Once the application is started, create a new villain with the following cUrl command:

[source,shell]
----
$ curl -X POST -d  '{"level":2, "name":"Darth Vader", "powers":"Darkness, Longevity"}'  -H "Content-Type: application/json" http://localhost:8084/api/villains -v

< HTTP/1.1 201 Created
< Location: http://localhost:8084/api/villains/582
----

The cUrl command returns the location of the newly created villain.
Take this URL and do an HTTP GET on it.

[source,shell]
----
$ curl http://localhost:8084/api/villains/582 | jq

{
  "id": 582,
  "level": 4,
  "name": "Darth Vader",
  "powers": "Darkness, Longevity"
}
----

Remember that you can also check Swagger UI by going to http://localhost:8084/swagger-ui.
