[[microservices-fight]]
= Fight Microservice

Ok, let's develop another microservice.
We have a REST API that returns a random Hero.
Another REST API that returns a randam Villain...
we need a new REST API that invokes those two, gets one random hero and one random villain and makes them fight.
Let's call it the Fight API.

== Bootstrapping the Fight REST Endpoint

Like for the Hero and Villain API, the easiest way to create this new Quarkus project is to use a Maven archetype.
Under the `quarkus-workshop-super-heroes/super-heroes` root directory where you have all your code, create a `rest-fight` sub-directory, open a terminal and run the following command:

[source,shell]
----
include::{github-raw}/super-heroes/rest-fight/bootstrap.sh[tag=adocSnippet]
----

Also add Testcontainers to your `pom.xml`.

[source,xml, indent=0]
--
<dependency>
  <groupId>org.testcontainers</groupId>
  <artifactId>junit-jupiter</artifactId>
  <version>1.12.2</version>
</dependency>
<dependency>
  <groupId>org.testcontainers</groupId>
  <artifactId>postgresql</artifactId>
  <version>1.12.2</version>
</dependency>
<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>org.testcontainers</groupId>
  <artifactId>kafka</artifactId>
  <version>1.12.2</version>
</dependency>
--

[TIP]
.Prefering Web UI
====
Instead of the Maven command, you can use https://code.quarkus.io.
====

You can see that beyond the extensions we have used so far, we added the Kafka support which uses Eclipse MicroProfile Reactive Messaging.
Stay tuned.

== Directory Structure

At the end you should have the following directory structure:

[plantuml]
----
@startsalt
{
{
T
super-heroes
+  rest-fight
++  src
+++  main
++++  docker
+++++  Dockerfile.jvm
+++++  Dockerfile.native
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  fight
++++++++++  Fight.java
++++++++++  FightApplication.java
++++++++++  FightResource.java
++++++++++  FightService.java
++++++++++  Fighters.java
++++++++++  KafkaWriter.java
++++  resources
+++++  META-INF
++++++  resources
+++++++  index.html
+++++  application.properties
+++++  import.sql
+++  test
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  fight
++++++++++  FightResourceTest.java
++  mvnw
++  mvnw.cmd
++  pom.xml
}
}
@endsalt
----

== Fight Entity

A fight is between a hero and a villain.
Each time there is a fight, there is a winner and a loser.
So the `Fight` entity is there to store all these fights.

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/Fight.java[tags=adocEntity;!adocSkip]
----

== Fighters Bean

Now comes a trick.
The Fight REST API will ultimatelly invoke the Hero and Villain APIs (next sections) to get two random fighters.
The `Fighters` class has one `Hero` and one `Villain`.
Notice that `Fighters` is not an entity, it is not persisted in the database, just marshalled and unmarshalled to JSon.

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/Fighters.java[tags=adocBean;!adocSkip]
----

The Fight REST API is just interested in the hero's name, level, picture and powers (not the other name as described in the Hero API).
So the `Hero` bean looks like this (notice the `client` subpackage):

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/client/Hero.java[tags=adocBean;!adocSkip]
----

`Villain` is pretty similar (also in the `client` subpackage):

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/client/Villain.java[tags=adocBean;!adocSkip]
----

So, these classes are just used to map the results from the Hero and Villain microservices.

== FightService Transactional Service

To _transactionnally_ manipulate the `Fight` entity we need a `FightService`.
Notice the `persistFight` method.
This method is the one creating a fight between a hero and a villain.
As you can see the algorithm to determine the winner is a bit random (even though it uses the levels).
If you are not happy about the way the fight operates, choose your own winning algorithm ;o)

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/FightService.java[tags=adocTransactional;!adocRestClient;!adocKafka;!adocKafkaEmitter;!adocFallback]
----

[NOTE]
====
For now, just implement an empty `Fighters findRandomFighters()` method which returns null.
Later, this method will invoke the Hello and Villain API to get a random Hello and random Villain.
So for now something like the following is enough:
[source, java]
--
public Fighters findRandomFighters() {
// Will be implemented later
return null;
}
--
====

== FightResource Endpoint

To expose a REST API we also need a `FightResource` (with OpenAPI annotations of course).

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/FightResource.java[tags=adocResource;!adocMetrics;!adocTimeout]
----

== FightApplication for OpenAPI

The `FightApplication` class is just there to customize the OpenAPI contract.

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/main/java/io/quarkus/workshop/superheroes/fight/FightApplication.java[tag=adocApplication]
----

[NOTE]
====
Notice that there is no `FightApplicationLifeCycle` class.
We will use a Quarkus extension later on to display a banner for Fight.
====

== Adding Data

To load some SQL statements when Hibernate ORM starts, download the SQL file {github-raw}/super-heroes/rest-fight/src/main/resources/import.sql[import.sql] and copy it under `src/main/resources`.

[source,sql]
----
include::{github-raw}/super-heroes/rest-fight/src/main/resources/import.sql[tag=adocSQL]
...
----

== Configuration

As usual, we need to configure the application.
In the `application.properties` file add:

[source,properties]
----
quarkus.http.port=8082

quarkus.datasource.url=jdbc:postgresql://localhost:5432/fights_database

quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=superfight
quarkus.datasource.password=superfight
quarkus.datasource.max-size=8
quarkus.datasource.min-size=2
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

## Logging configuration
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=DEBUG
quarkus.log.console.color=true

## Production configuration
%prod.quarkus.hibernate-orm.log.sql=false
%prod.quarkus.log.console.level=INFO
%prod.quarkus.hibernate-orm.database.generation=update
----

Note that the fight service uses the port 8082.

== FightResourceTest Test Class

We need to test our REST API.
For that, copy the following `FightResourceTest` class under the `src/test/java/io/quarkus/workshop/superheroes/fight` directory.

[source]
----
include::{github-raw}/super-heroes/rest-fight/src/test/java/io/quarkus/workshop/superheroes/fight/FightResourceTest.java[tags=adocResourceTest;!adocHealth;!adocMetrics;!adocRandom]
----

Also, delete the generated `NativeFightResourceIT` class, as we won't run native test for this microservice.

== Running, Testing and Packaging the Application

First, make sure the tests pass by executing the command `./mvnw test` (or from your IDE).

Now that the tests are green, we are ready to run our application.
Use `./mvnw compile quarkus:dev` to start it (notice that there is no banner yet, it will come later).
Once the application is started, just check that it returns the fights from the database with the following cUrl command:

[source,shell]
----
$ curl http://localhost:8082/api/fights
----

Remember that you can also check Swagger UI by going to http://localhost:8082/swagger-ui.
