[[microservices-villain]]
= Villain Microservice

New microservice, new project!
In this section we will develop a Villain REST Endpoint which is *really* similar to the Hero Endpoint (and remember, copy/paste is your best friend).

== Bootstrapping the Villain REST Endpoint

Like for the Hero API, the easiest way to create this new Quarkus project is to use a Maven archetype.
Under the `quarkus-workshop-super-heroes/super-heroes` root directory where you have all your code, create a `rest-villain` sub-directory, open a terminal and run the following command:

[source,shell]
----
include::{github-raw}/super-heroes/rest-villain/bootstrap.sh[tag=adocSnippet]
----

Also add the following dependencies:

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/rest-villain/pom.xml[tag=adocDependencyTest]
----

[TIP]
.Prefering Web UI
====
Instead of the Maven command, you can use https://code.quarkus.io.
====

== Directory Structure

At the end you should have the following directory structure:

[plantuml]
----
@startsalt
{
{
T
super-heroes
+  rest-villain
++  src
+++  main
++++  docker
+++++  Dockerfile.jvm
+++++  Dockerfile.native
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  villain
++++++++++  Villain.java
++++++++++  VillainApplication.java
++++++++++  VillainApplicationLifeCycle.java
++++++++++  VillainResource.java
++++++++++  VillainService.java
++++  resources
+++++  META-INF
++++++  resources
+++++++  index.html
+++++  application.properties
+++++  import.sql
+++  test
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  villain
++++++++++  VillainResourceTest.java
++  mvnw
++  mvnw.cmd
++  pom.xml
}
}
@endsalt
----

== Villain Entity

Villains need to be stored, updated and retrieved from a database.
As you know now, Hibernate with Panache makes the ORM job really easy.
So this is what the `Villain` looks like (notice the `findRandom()` method):

[source]
----
include::{github-raw}/super-heroes/rest-villain/src/main/java/io/quarkus/workshop/superheroes/villain/Villain.java[tags=adocEntity;!adocSkip]
----

== VillainService Transactional Service

To transactionnally manipulate a `Villain` entity we need a `VillainService`.

[source]
----
include::{github-raw}/super-heroes/rest-villain/src/main/java/io/quarkus/workshop/superheroes/villain/VillainService.java[tag=adocTransactional]
----

== VillainResource Endpoint

To expose a REST API we also need a `VillainResource`.
Notice the OpenAPI annotations.

[source]
----
include::{github-raw}/super-heroes/rest-villain/src/main/java/io/quarkus/workshop/superheroes/villain/VillainResource.java[tags=adocResource;!adocMetrics]
----

== VillainApplication for OpenAPI

The `VillainApplication` class is just there to customize the OpenAPI contract.

[source]
----
include::{github-raw}/super-heroes/rest-villain/src/main/java/io/quarkus/workshop/superheroes/villain/VillainApplication.java[tag=adocApplication]
----

== VillainApplicationLifeCycle for Startup Banner

The villain API also needs a nice banner.
Go back to http://patorjk.com/software/taag and pick up your favourite "Villain API" text banner and paste it into the `VillainApplicationLifeCycle` class.

[source]
----
include::{github-raw}/super-heroes/rest-villain/src/main/java/io/quarkus/workshop/superheroes/villain/VillainApplicationLifeCycle.java[tag=adocApplicationLifeCycle]
----

== Adding Data

To load some SQL statements when Hibernate ORM starts, add the following `import.sql` in the root of the `resources` directory.

[source,sql]
----
include::{github-raw}/super-heroes/rest-villain/src/main/resources/import.sql[tag=adocSQL]
----

If you want to add more heroes to the database, download the SQL file {github-raw}/super-heroes/rest-villain/src/main/resources/import.sql[import.sql] and copy it under `src/main/resources`.

== VillainResourceTest Test Class

We need to test our REST API.
For that, copy the following `VillainResourceTest` class under the `src/test/java/io/quarkus/workshop/superheroes/villain` directory.

[source]
----
include::{github-raw}/super-heroes/rest-villain/src/test/java/io/quarkus/workshop/superheroes/villain/VillainResourceTest.java[tags=adocResourceTest;!adocHealth;!adocMetrics]
----

== Configuration

Notice that this instance of Quarkus listens on port 8084

[source]
----
include::{github-raw}/super-heroes/rest-villain/src/main/resources/application.properties[tags=!adocCORS]
----

== Running, Testing and Packaging the Application

First, make sure the tests pass by executing the command `./mvnw test` (or from your IDE).

Now that the tests are green, we are ready to run our application.
Use `./mvnw compile quarkus:dev` to start it (notice the nice banner).
Once the application is started, create a new villain with the following cUrl command:

[source,shell]
----
$ curl -X POST -d  '{"level":2, "name":"Darth Vader", "powers":"Darkness, Longevity"}'  -H "Content-Type: application/json" http://localhost:8084/api/villains -v

< HTTP/1.1 201 Created
< Location: http://localhost:8084/api/villains/562
----

The cUrl command returns the location of the newly created villain.
Take this URL and do an HTTP GET on it.

[source,shell]
----
$ curl http://localhost:8084/api/villains/562 | jq

{
  "id": 562,
  "level": 6,
  "name": "Darth Vader",
  "powers": "Darkness, Longevity"
}
----

Remember that you can also check Swagger UI by going to http://localhost:8084/swagger-ui.
