[[quarkus-lifecycle]]
= Application Lifecycle

:icons: font

Now that you know how is structured Quarkus, let's continue using various extensions.
You often need to execute custom actions when the application starts and clean up everything when the application stops.
In this module we will display a banner in the logs once the Hero API has started.

== Directory Structure

In this module we will add an extra class (`HeroApplicationLifeCycle`) to handle the Hero API lifecycle.
You will end-up with the following directory structure:

[plantuml]
----
@startsalt
{
{
T
super-heroes
+  rest-hero
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  hero
++++++++++  Hero.java
++++++++++  HeroApplication.java
++++++++++  HeroApplicationLifeCycle.java
++++++++++  HeroResource.java
++++++++++  HeroService.java
++  pom.xml
}
}
@endsalt
----

== Displaying a Banner

When our application starts, the logs are pretty boring... and lack of a banner (any decent application *must* have a banner nowadays).
So the first thing that you need to do is to go to the http://patorjk.com/software/taag[following website] and pick up your favourite "Hero API" text banner.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Create a new class named `HeroApplicationLifeCycle` (or pick another name, the name does not matter) in the `io.quarkus.workshop.superheroes.hero` package, and copy your banner so you end up with a similar content:

[source]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroApplicationLifeCycle.java[tags=adocApplicationLifeCycle;!adocProfileManager]
----

Thanks to the CDI `@Observes`, the `HeroApplicationLifeCycle` is invoked:

* on startup with the `StartupEvent` so it can execute code (here, displaying the banner) when the application is starting
* on shutdown with the `ShutdownEvent` when the application is terminating

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Run the application with: `./mvnw quarkus:dev`, the banner is printed to the console.
When the application is stopped, the second log message is printed.

[NOTE]
====
If your application was still running, just send an HTTP request, like go to http://localhost:8083.
As the application code changed, the application is restarted.
====
