[[quarkus-profile]]
= Configuration Profiles

:icons: font

Quarkus supports the notion of configuration profiles.
These allow you to have multiple configuration in the same file and select between them via a profile name.

By default Quarkus has three profiles, although it is possible to use as many as you like. The default profiles are:

* `dev` - Activated when in development mode (i.e. `quarkus:dev`)
* `test` - Activated when running tests
* `prod` - The default profile when not running in development or test mode

Let's change the `HeroApplicationLifeCycle` so it displays the current profile.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

For that, just add a log invoking the `ProfileManager.getActiveProfile()` method:

[source,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroApplicationLifeCycle.java[tags=adocStartupEvent]
----

[NOTE]
--
If not already done, you need to add the following import statement: `import io.quarkus.runtime.configuration.ProfileManager;`
--

In the `application.properties` file, you can prefix a property to be defined in the running profile.
For example, we did add the `%test.level.multiplier=1` property in the previous chapter.
This indicates that the property `level.multiplier` is set to 1 in the `test` profile.

Now, if you start your application in dev mode with `mvn compile quarkus:dev`, you will get the `dev` profile enabled.
If you start the tests, the `test` profile is enabled (and so the `multiplier` is set to 1).

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Package your application with `mvn package`, and start it with `java -Dquarkus.profile=foo -jar target/rest-hero-1.0-SNAPSHOT-runner.jar`.
You will see that the `foo` profile is enabled.
As not overridden, the `level.multiplier` property has the value 3.

Profiles are very useful to customize the configuration per environment.
We are going to see an example of such customization in the next section.
