[[rest-configuration]]
= Configuration

Hardcoded values in our code are a no go (even if we all did it at some point ;-)).
In this guide, we learn how to configure our Hero API as well as some parts of Quarkus.

== Configuring Logging

Run time configuration of logging is done through the normal `application.properties` file.

[source,properties]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/application.properties[tags=adocLogging]
----

== Configuring Quarkus Listening Port

Because we will end-up running several microservices, let's configure Quarkus so it listens to a different port than 8080:

[source,properties]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/application.properties[tags=adocPort]
----

== Injecting configuration value

When we persist a new hero we want to multiply its level by a value that can be configured.
For this, Quarkus uses MicroProfile Config to inject the configuration in the application.A statement.footnote:[Microprofile Config https://microprofile.io/project/eclipse/microprofile-config]
The injection uses the `@ConfigProperty` annotation.

[NOTE]
====
When injecting a configured value, you can use `@Inject @ConfigProperty` or just `@ConfigProperty`.
The `@Inject` annotation is not necessary for members annotated with `@ConfigProperty`, a behavior which differs from https://microprofile.io/project/eclipse/microprofile-config[MicroProfile Config].
====

Edit the `HeroService`, and introduce the following configuration properties:

[source,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroService.java[tag=adocConfigProperty]
----

* If you do not provide a value for this property, the application startup fails with `javax.enterprise.inject.spi.DeploymentException: No config value of type [int] exists for: level.multiplier`
* A default value of `2` injected if the configuration does not provide a value for `level.multiplier`

Now, modify the `persistHero` method to use the injected properties:

[source,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroService.java[tag=adocPersistHero]
----

== Create the configuration

By default, Quarkus reads `application.properties`.
Edit the `src/main/resources/application.properties` with the following content:

[source,properties]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/application.properties[tag=adocConfigProperty]
----
