[[rest]]
= Creating a REST/HTTP Microservice

'''

At the heart of the Super Hero application comes Heroes.
We need to expose a REST API allowing CRUD operations on Super Heroes.
This microservice is, let's say, a _classical_ microservice.
It uses HTTP to expose a REST API and internally store data into a database.
This service will be used by the _fight_ microservice.

[plantuml,align=center,width=300]
----
include::plantuml/rest-physical-architecture.puml[]
----

In the following sections, you learn:

* how to create a new Quarkus application
* how to implement REST API using JAX-RS
* how to compose your application using CDI beans
* how to access your database using Hibernate with Panache
* how to use transactions
* how to enable OpenAPI and Swagger-UI

But first, let's describe our service.
The Super Heroes microservice stores super-heroes, with their names, powers, and so on.
The REST API allows adding, removing, listing, and picking a random hero from the stored set.
Nothing outstanding but a good first step to discover Quarkus.
