[[rest-transaction-orm]]
= Transactions and ORM

The Hero API's role is to allow CRUD operations on Super Heroes.
In this module we will create a Hero entity and persist/update/delete/retrieve it from a Postgres database in a transactional way.

== Directory Structure

In this module we will add extra classes to the Hero API project.
You will end-up with the following directory structure:

[source,text]
----
super-heroes/
└── rest-hero/
    ├── pom.xml
    └── src
        └── main
            └── java
                └── io
                    └── quarkus
                        └── workshop
                            └── superheroes
                                └── hero
                                    ├── Hero.java
                                    ├── HeroResource.java
                                    └── HeroService.java
----

== Installing the PostgreSQL Dependency

To install the PostgreSQL driver dependency, just run the following command:

[source,shell]
----
$ ./mvnw quarkus:add-extension -Dextensions="jdbc-postgresql"
----

This will add the following dependency in the `pom.xml` file:

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/pom.xml[tags=adocDependencyPostgresql]
----

Fomr now on, you can choose to either edit your pom directly or use the `quarkus:add-extension` command.
The command does accept partial extension names: in this case we used `jdbc-postgresql` instead of the complete `io.quarkus:quarkus-jdbc-postgresql`.

== Hero Entity

Hibernate ORM is the de-facto JPA implementation and offers you the full breadth of an Object Relational Mapper.
It makes complex mappings possible, but it does not make simple and common mappings trivial.
Hibernate ORM with Panache focuses on making your entities trivial and fun to write in Quarkus.footnote:[Panache https://github.com/quarkusio/quarkus/tree/master/extensions/panache]

Because JPA and Bean Validation work well together, we will use Bean Validation to constrain our business model.
So first, make sure to add the Panache JPA and Bean Validation extensions to your `pom.xml`:

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/pom.xml[tags=adocDependencyHibernate]
include::{github-raw}/super-heroes/rest-hero/pom.xml[tags=adocDependencyValidator]
----

[TIP]
--
When you change your POM, don't forget to restart the `quarkus:dev` mode.
--

To define a Panache entity, simply extend `PanacheEntity`, annotate it with `@Entity` and add your columns as public fields (no need to have getters and setters).
The `Hero` entity should look like this:

[source]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/Hero.java[tags=adocEntity;!adocFindRandom]
----

Notice that you can put all your JPA column annotations and Bean Validation constraint annotations on the public fields.

=== Adding Operations

Thanks to Panache, once you have written the `Hero` entity, here are the most common operations you will be able to do:

[source]
----
// creating a hero
Hero hero = new Hero();
hero.name = "Superman";
hero.level = 9;

// persist it
hero.persist();

// getting a list of all Hero entities
List<Hero> heroes = Hero.listAll();

// finding a specific hero by ID
hero = Hero.findById(id);

// counting all heroes
long countAll = Hero.count();
----

But we are missing a business method:
we need to return a random hero.
For that it's just a matter to add the following method to our `Hero.java` entity:

[source,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/Hero.java[tags=adocFindRandom]
----

== Configuring Hibernate

Quarkus development mode is really useful for applications that mix front end or services and database access.
We use `quarkus.hibernate-orm.database.generation=drop-and-create` in conjunction with `import.sql` so every change to your app and in particular to your entities, the database schema will be properly recreated and your data (stored in `import.sql`) will be used to repopulate it from scratch.
This is best to perfectly control your environment and works magic with Quarkus live reload mode:
your entity changes or any change to your `import.sql` is immediately picked up and the schema updated without restarting the application!

For that, make sure to have the following configuration in your `application.properties`:

[source,properties]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/application.properties[tags=adocHibernate]
----

== HeroService Transactional Service

To manipulate the `Hero` entity we will develop a transactional `HeroService` class.
The idea is to wrap methods modifying the database (e.g. `entity.persist()`) within a transaction.
Marking a CDI bean method `@Transactional` will do that for you and make that method a transaction boundary.

`@Transactional` can be used to control transaction boundaries on any CDI bean at the method level or at the class level to ensure every method is transactional.
You can control whether and how the transaction is started with parameters on `@Transactional`:

* `@Transactional(REQUIRED)` (default): starts a transaction if none was started, stays with the existing one otherwise.
* `@Transactional(REQUIRES_NEW)`: starts a transaction if none was started ; if an existing one was started, suspends it and starts a new one for the boundary of that method.
* `@Transactional(MANDATORY)`: fails if no transaction was started ; works within the existing transaction otherwise.
* `@Transactional(SUPPORTS)`: if a transaction was started, joins it ; otherwise works with no transaction.
* `@Transactional(NOT_SUPPORTED)`: if a transaction was started, suspends it and works with no transaction for the boundary of the method ; otherwise works with no transaction.
* `@Transactional(NEVER)`: if a transaction was started, raises an exception ; otherwise works with no transaction.

[source]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroService.java[tags=adocTransactional;!adocConfigProperty;!adocPersistHeroLevel]
----

Notice that both methods that persist and update a hero, pass a `Hero` object as a parameter.
Thanks to the Bean Validation's `@Valid` annotation, the `Hero` object will be checked to see if it's valid or not.
It it's not, the transaction will be rollbacked.

== Configuring the Datasource

Our project now requires a connection to a PostgreSQL database.
The main way of obtaining connections to a database is to use a datasource.
In Quarkus, the out of the box datasource and connection pooling implementation is Agroal.footnote:[Agroal https://agroal.github.io]

This is done in the `src/main/resources/application.properties` file.
Just add the following datasource configuration:

[source,properties]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/application.properties[tags=adocDatasource]
----

== HeroResource Endpoint

The `HeroResource` Endpoint was bootstrapped with only one method `hello()`.
We need to add extra methods that will allow CRUD operations on heroes.

But first, our application will use JSON as payload, so let's add the RESTEasy JSON-B extension.

[source]
----
include::{github-raw}/super-heroes/rest-hero/pom.xml[tags=adocDependencyResteasyJsonB]
----

Here are the new methods to add to the `HeroResource` class:

[source]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroResource.java[tags=adocResource;!adocOpenAPI;!adocMetrics]
----

== Dependency Injection

Dependency injection in Quarkus is based on ArC which is a CDI-based dependency injection solution tailored for Quarkus' architecture.footnote:[ArC https://github.com/quarkusio/quarkus/tree/master/independent-projects/arc]
You can learn more about it in the Contexts and Dependency Injection guide.footnote:[Quarkus - Contexts and Dependency Injection https://quarkus.io/guides/cdi-reference.html]

ArC comes as a dependency of `quarkus-resteasy` so you already have it handy.
That's why you were able to use `@Inject` in the `HeroResource` to inject a reference to `HeroService`.

== Adding Data

To load some SQL statements when Hibernate ORM starts, add the following `import.sql` in the root of the `resources` directory.
It contains SQL statements terminated by a semicolon.
This is useful to have a data set ready for the tests or demos.

[source,sql]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/import.sql[tag=adocSQL]
----

If you want to add more heroes to the database, download the SQL file {github-raw}/super-heroes/rest-hero/src/main/resources/import.sql[import.sql] and copy it under `src/main/resources`.
This is recommended to do so now because test assertions depend on the full data set.

== CRUD Tests in HeroResourceTest

To test the `HeroResource` endpoint, we will be using TestContainers to fire a Postgres database and then test CRUD operations.footnote:[TestContainers https://www.testcontainers.org]
As you will see, these tests are more complex as they start a Postgres database to allow CRUD operations to be tested against a real database.
For that we will install the TestContainers dependency in our `pom.xml` as well as some extra test dependencies:

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/pom.xml[tags=adocDependencyTestContainers]
include::{github-raw}/super-heroes/rest-hero/pom.xml[tags=adocDependencyTestREST]
----

You will add the following test methods to the `HeroResourceTest` class:

* `shouldNotGetUnknownHero`: giving a random Hero identifier, the `HeroResource` endpoint should return a 204 (No content)
* `shouldGetRandomHero`: checks that the `HeroResource` endpoint returns a random hero
* `shouldNotAddInvalidItem`: passing an invalid `Hero` should fail when creating it (thanks to the `@Valid` annotation)
* `shouldGetInitialItems`: checks that the `HeroResource` endpoint returns the list of heroes
* `shouldAddAnItem`: checks that the `HeroResource` endpoint creates a valid `Hero`
* `shouldUpdateAnItem`: checks that the `HeroResource` endpoint updates a newly created `Hero`
* `shouldRemoveAnItem`: checks that the `HeroResource` endpoint deletes a hero from the database

The code is as follow:

[source]
----
include::{github-raw}/super-heroes/rest-hero/src/test/java/io/quarkus/workshop/superheroes/hero/HeroResourceTest.java[tags=adocResourceTest;!adocOpenAPI;!adocHealth;!adocMetrics]
----

Execute the test using `./mvnw test`.
The test should pass.

== Downloading and Running the Infrastructure

To execute the application we now need a database (and later one we will need Prometheus and Kafka).
Let's use Docker and docker compose to ease the installation of such infrastructure.

Go to {github-raw}/super-heroes/infrastructure and download the entire code into the `infrastructure` directory.
Here, you will find a `docker-compose.yaml` file which defines all the needed Docker images.
Notice that there is a `db-init` directory with a `initialize-databases.sql` script which sets up our databases (the `monitoring` directory will be explained later).

Now, for the infrastructure to be up and running, just execute `docker-compose -f docker-compose.yaml up -d`.
You should see a few logs going on and then all the containers get started.

[NOTE]
====
During the workshop, just leave all the containers up and running.
Then, after the workshop, remember to shut them down using: `docker-compose -f docker-compose.yaml down`
====

== Running the Application

Now that the tests pass and that our infrastructure is up and running, we are ready to run our application.
Use `./mvnw compile quarkus:dev` to start it.
Once started, check that there are heroes in the database with the following cUrl command:

[source,shell]
----
$ curl http://localhost:8083/api/heroes
----
