[[rest-configuration]]
= Configuring the Hero Microservice

:icons: font

Hardcoded values in our code are a no go (even if we all did it at some point ;-)).
In this guide, we learn how to configure our Hero API as well as some parts of Quarkus.

== Configuring Logging

Run time configuration of logging is done through the normal `application.properties` file.

[source,properties]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/application.properties[tags=adocLogging]
----

== Configuring Quarkus Listening Port

Because we will end-up running several microservices, let's configure Quarkus so it listens to a different port than 8080:
This is quite easy as we just need to add one property in the `application.properties` file:

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

[source,properties]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/application.properties[tags=adocPort]
----

Changing the port is one of the rare configuration that cannot be done while the application is running.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

You would need to restart the application to change the port.

Hit `CTRL+C` to stop the application and restart it with: `./mvnw quarkus:dev`

== Injecting Configuration Value

When we persist a new hero we want to multiply its level by a value that can be configured.
For this, Quarkus uses MicroProfile Config to inject the configuration in the application.footnote:[Microprofile Config https://microprofile.io/project/eclipse/microprofile-config]
The injection uses the `@ConfigProperty` annotation.

[NOTE]
====
When injecting a configured value, you can use `@Inject @ConfigProperty` or just `@ConfigProperty`.
The `@Inject` annotation is not necessary for members annotated with `@ConfigProperty`, a behavior which differs from https://microprofile.io/project/eclipse/microprofile-config[MicroProfile Config].
====

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Edit the `HeroService`, and introduce the following configuration properties:

[source,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroService.java[tag=adocConfigProperty]
----

[NOTE]
====
You may need to add the following import statement if your IDE does not do it automatically: `import org.eclipse.microprofile.config.inject.ConfigProperty;`
====

* If you do not provide a value for this property, the application startup fails with `javax.enterprise.inject.spi.DeploymentException: No config value of type [int] exists for: level.multiplier`
* A default value (property `defaultValue`) is injected if the configuration does not provide a value for `level.multiplier`

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Now, modify the `HeroService.persistHero()` method to use the injected properties:

[source,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/src/main/java/io/quarkus/workshop/superheroes/hero/HeroService.java[tag=adocPersistHero]
----

== Create the Configuration

By default, Quarkus reads `application.properties`.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

Edit the `src/main/resources/application.properties` with the following content:

[source,properties]
----
include::{github-raw}/super-heroes/rest-hero/src/main/resources/application.properties[tag=adocConfigProperty]
----

== Running and Testing the Application

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

If you didn't already, start the application with `./mvnw quarkus:dev`.
Once started, create a new hero with the following cUrl command:

[source,shell]
----
$ curl -X POST -d  '{"level":5, "name":"Chewbacca", "powers":"Agility, Longevity"}'  -H "Content-Type: application/json" http://localhost:8083/api/heroes -v

< HTTP/1.1 201 Created
< Location: http://localhost:8083/api/heroes/952
----

As you can see, we've passed a level of 5 to create this new hero.
The cUrl command returns the location of the newly created hero.
Take this URL and do an HTTP GET on it.
You will see that the level has been increased.

[source,shell]
----
$ curl http://localhost:8083/api/heroes/952 | jq

{
  "id": 957,
  "level": 15,
  "name": "Chewbacca",
  "powers": "Agility, Longevity"
}
----

[NOTE]
====
You may not know `jq`.
It's an amazing tool to manipulate JSON in the shell.
More info on: https://stedolan.github.io/jq/
====

Hey! Wait a minute! Tests are failing now!
Indeed, they don't know the multiplier.

icon:hand-o-right[role="red", size=2x] [red big]#Call to action#

In the `application.properties` file, add: `%test.level.multiplier=1` which set the multiplier to 1 when running the tests.
We will cover the `%test` syntax soon.

