[[rest-bootstrapping]]
= Hero Microservice

First thing first, we need a project.
That's what your are going to see in this section.

== Bootstrapping the Hero REST Endpoint

The easiest way to create a new Quarkus project is to use the Quarkus Maven plugin.
Let's say you have a `quarkus-workshop` root directory where you have all your code, create a `rest-hero` sub-directory, open a terminal and run the following command:

[source,shell]
----
include::{github-raw}/super-heroes/rest-hero/bootstrap.sh[tag=adocSnippet]
----

[TIP]
.Prefering Web UI
====
Instead of the Maven command, you can use https://code.quarkus.io.
====

== Directory Structure

Once you bootstrap the project, you get the following directory structure with a few Java classes and other artifacts :

[source,text]
----
super-heroes/
└── rest-hero/
   ├── mvnw
   ├── mvnw.cmd
   ├── pom.xml
   └── src
       ├── main
       │   ├── docker
       │   │   ├── Dockerfile.jvm
       │   │   └── Dockerfile.native
       │   ├── java
       │   │   └── io
       │   │       └── quarkus
       │   │           └── workshop
       │   │               └── superheroes
       │   │                   └── hero
       │   │                       └── HeroResource.java
       │   └── resources
       │       ├── META-INF
       │       │   └── resources
       │       │       └── index.html
       │       └── application.properties
       └── test
           └── java
               └── io
                   └── quarkus
                       └── workshop
                           └── superheroes
                               └── hero
                                   ├── HeroResourceTest.java
                                   └── NativeHeroResourceIT.java
----

The Maven archetype generates the following `rest-hero` sub-directory:

* the Maven structure with a `pom.xml`
* an `io.quarkus.workshop.superheroes.hero.HeroResource` resource exposed on `/api/heroes`
* an associated unit test `HeroResourceTest`
* the landing page `index.html` that is accessible on http://localhost:8080 after starting the application
* example `Dockerfile` files for both native and jvm modes in `src/main/docker`
* the `application.properties` configuration file

Once generated, look at the `pom.xml`.
You will find the import of the Quarkus BOM, allowing you to omit the version on the different Quarkus dependencies.
In addition, you can see the `quarkus-maven-plugin` responsible of the packaging of the application and also providing the development mode.

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/pom.xml[tags=adocProperties;!adocPropertiesTestcontainers;!adocDependencyKafkaBom]
include::{github-raw}/super-heroes/pom.xml[tags=adocDependencyManagement;!adocDependencyTestBom]
include::{github-raw}/super-heroes/pom.xml[tags=adocBuild]
----

If we focus on the dependencies section, you can see the extension allowing the development of REST applications:

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/pom.xml[tags=adocDependencyResteasy]
----

[TIP]
.RESTEasy
====
You may not be familiar with RESTEasy.footnote:[RESTEasy https://resteasy.github.io]
It's an implementation of JAX-RS and it uses to implement RestFul services in Quarkus.
====

== The JAX-RS Resource

During the project creation, the `HeroResource.java` file has been created with the following content:

[source]
----
package io.quarkus.workshop.superheroes.hero;

@Path("/api/heroes")
public class HeroResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
----

It's a very simple REST endpoint, returning "hello" to requests on `/api/heroes`.

== Running the Application

Now we are ready to run our application.
Use: `./mvnw compile quarkus:dev`:

[source,shell]
----
$ ./mvnw compile quarkus:dev
[INFO] -------------< io.quarkus.workshop.super-heroes:rest-hero >--------------
[INFO] Building rest-hero 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rest-hero ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ rest-hero ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/agoncal/Code/Quarkus/rest-hero/target/classes
[INFO]
[INFO] --- quarkus-maven-plugin:0.25.0:dev (default-cli) @ rest-hero ---
[ERROR] Port 5005 in use, not starting in debug mode
2019-10-04 10:08:11,536 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-10-04 10:08:11,989 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 453ms
2019-10-04 10:08:12,294 INFO  [io.quarkus] (main) Quarkus 0.25.0 started in 0.891s. Listening on: http://0.0.0.0:8080
2019-10-04 10:08:12,295 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2019-10-04 10:08:12,295 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
----

Then check that the endpoint returns `hello` as expected:

[source,shell]
----
$ curl http://localhost:8080/api/heroes
hello
----

Alternatively, you can open http://localhost:8080/api/heroes in your browser.

== Development Mode

`quarkus:dev` runs Quarkus in development mode.
This enables hot deployment with background compilation, which means that when you modify your Java files and/or your resource files and invoke a REST endpoint (i.e. cUrl command or refresh your browser), these changes will automatically take effect.
This works too for resource files like the configuration property and HTML files.
Refreshing the browser triggers a scan of the workspace, and if any changes are detected, the Java files are recompiled and the application is redeployed;
your request is then serviced by the redeployed application.
If there are any issues with compilation or deployment an error page will let you know.

The development mode also allows debugging and listens for a debugger on port 5005.
If you want to wait for the debugger to attach before running you can pass `-Ddebug` on the command line.
If you don't want the debugger at all you can use `-Ddebug=false`.

To check that the hot reload is working, update the method `HeroResource.hello()` by returning the String "hello hero".
Now, execute the cUrl command again, the output has changed without you to having to stop and restart Quarkus:

[source,shell]
----
$ curl http://localhost:8080/api/heroes
hello hero
----

== Testing the Application

All right, so far so good, but wouldn't it be better with a few tests, just in case.

In the generated `pom.xml` file, you can see 2 test dependencies:

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/rest-hero/pom.xml[tags=adocDependencyTest]
----

Quarkus supports Junit 4 and Junit 5 tests.
In the generated project, we use Junit 5.
Because of this, the version of the Surefire Maven Plugin must be set, as the default version does not support Junit 5:

[source,xml,indent=0]
----
include::{github-raw}/super-heroes/pom.xml[tags=adocProperties;!adocPropertiesTestcontainers]
include::{github-raw}/super-heroes/pom.xml[tags=adocBuildSurefire]
----

We also set the `java.util.logging` system property to make sure tests will use the correct log manager.

The generated project contains a simple test in `HeroResourceTest.java`.

[source]
----
package io.quarkus.workshop.superheroes.hero;

@QuarkusTest
public class HeroResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/api/heroes")
          .then()
             .statusCode(200)
             .body(is("hello"));
    }
}
----

By using the `QuarkusTest` runner, the `HeroResourceTest` class instructs JUnit to start the application before the tests.
Then, the `testHelloEndpoint` method checks the HTTP response status code and content.
Notice that these tests use RestAssured, but feel free to use your favorite library.footnote:[RestAssured http://rest-assured.io]

Execute it with `./mvnw test` or from your IDE.

== Packaging and Running the Application

The application is packaged using `./mvnw package`.
It produces 2 jar files in `/target`:

* `rest-hero-1.0-SNAPSHOT.jar` : containing just the classes and resources of the projects, it's the regular artifact produced by the Maven build;
* `rest-hero-1.0-SNAPSHOT-runner.jar` : being an executable jar.
Be aware that it's not an über-jar as the dependencies are copied into the `target/lib` directory.

You can run the application using: `java -jar rest-hero-1.0-SNAPSHOT-runner.jar`.

[NOTE]
====
Before running the application, don't forget to stop the hot reload mode (hit CTRL+C), or you will have a port conflict.
====

== Troubleshooting

You might come across the following error while developing:

[source,shell]
----
WARN  [io.qu.ne.ru.NettyRecorder] (Thread-48) Localhost lookup took more than one second, you need to add a /etc/hosts entry to improve Quarkus startup time. See https://thoeni.io/post/macos-sierra-java/ for details.
----

If this is the case, it's just a matter to add the node name of your machine to the /etc/hosts.
For that, first get the name of your node with the following command:

[source,shell]
----
$ uname -n
my-node.local
----

Then `sudo vi /etc/hosts` so you have the rights to edit the file and add the following entry

[source,shell]
----
127.0.0.1 localhost my-node.local
----
