= Provider tests

So far, we've done good work and set up tests for the fight service, to extend our testing of the fight service, and also encode its expectations for the hero service into a json contract.

The next step is to make sure the Hero service actually produces what the contract says it should!

== Sharing the contract

There are a few possibilities for sharing the contract.
A self-hosted or https://pactflow.io/[managed] https://docs.pact.io/getting_started/sharing_pacts[pact broker] can host all of the contracts, as well as providing extra services such as metrics about when tests were run and compatibility dashboards.

Alternatively, some teams check the json contract into the provider's source control after a successful run.
Note that Pact is consumer-driven contract system; the consumer has responsibility for defining the contract, and therefore also has responsibility for sharing it.

The simplest sharing mechanism is copying on a filesystem, so that's what we'll do.
From the fights service, copy the contract to the heroes service.

[source,bash]
----
mkdir -p ../rest-heroes/src/test/resources
cp -r target/pacts ../rest-heroes/src/test/resources
----

== Writing the test

The great thing about the provider Pact tests is that the provider doesn't have to do much.
The Pact framework will generate a test for each expectation in the contract and run them, based on just a small amount of boilerplate code:

[source,java]
----
@TestTemplate
@ExtendWith(PactVerificationInvocationContextProvider.class)
void pactVerificationTestTemplate(PactVerificationContext context) {
    context.verifyInteraction();
}
----

(No need to put that snippet anywhere yet, we will see how it fits into a test class in a moment.)

[example, role="cta"]
--

Add the Pact dependency to the heroes service `pom.xml`:

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>io.quarkiverse.pact</groupId>
    <artifactId>quarkus-pact-provider</artifactId>
    <version>{quarkus-pact-version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-panache-mock</artifactId>
    <scope>test</scope>
</dependency>
----

We also add the https://quarkus.io/guides/hibernate-orm-panache#mocking[Panache Mock dependency], which allows us to use Mockito to mock all provided static methods.
That will come in handy at various points in the provider testing.

Create a `io/quarkus/workshop/superheroes/hero/HeroContractVerificationTest.java` class in the `rest-heroes` project.
It doesn't need to do much except tell Pact what port the Hero provider is listening on,
and create a JUnit test template, which will be expanded into the full set of tests
needed to verify the contract.

[source,java]
----
@QuarkusTest
@Provider("rest-heroes")
@PactFolder("pacts")
public class HeroContractVerificationTest {
    @ConfigProperty(name = "quarkus.http.test-port")
    int quarkusPort;


    @BeforeEach
    void beforeEach(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", this.quarkusPort));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }
}
----

When you run the tests they should pass.
--
