[[introduction-preparing]]
= Preparing for the Workshop

In this workshop, you will be developing an application dealing with Super Heroes (and Super-Villains 🦹) as well as Quarkus extensions.
The code will be separated into two different directories:

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes         | The entire Super Hero application
}
}
@endsalt
----

== Download the workshop scaffolding

[example, role="cta"]
--

We've done some of the layout for you. First, download the zip file  {github-raw}/dist/quarkus-super-heroes-workshop.zip, and unzip it wherever you want.
This zip file contains _some_ of the code of the workshop, along with assets you will need to complete it.

--

// NOTE: Inlined from common-no-zip-download.adoc to work around Roq's lack of base-dir support for nested includes.
// Once Roq 2.1.10+ is released, restore to: include::../common-no-zip-download.adoc[]
ifdef::use-no-zip[]
[NOTE]
.Working without the zip
====
In some security-conscious environments, downloading the zip isn't an option.
If that's a constraint you have, you can follow the workshop without it.
We'll fill in the gaps as we go, showing you how to create the pieces the zip would have provided (and, where a piece is too big to paste, how to copy it from source control).
====
endif::use-no-zip[]

=== Super Heroes Application

Under the `super-heroes` directory you will find the entire Super Hero application spread throughout a set of subdirectories, each one containing a microservice or some tooling.
The final structure will be the following (don't worry if you don't have all this yet, this is what we're aiming towards):

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+ super-heroes
++ event-statistics        | UI and application dealing with fight statistics (you will create it)
++ infrastructure          | All the needed infrastructure (Postgres, Kafka...)
++ kubernetes              | All the files required to deploy on Kubernetes
++ load-super-heroes       | CLI tool to load stress on heroes, villains and fights
++ rest-fights             | REST API allowing super heroes to fight (you will create it)
++ rest-heroes             | Reactive REST API for CRUD operations on Heroes (you will create it)
++ rest-narration          | REST API invoking an AI to narrate the fight (you will create it)
++ rest-villains           | REST API for CRUD operations on Villains (you will create it)
++ ui-super-heroes         | React application so we can fight visually
}
}
@endsalt
----

ifdef::use-maven[]
Most of these subdirectories are Maven projects and follow the Maven directory structure:
endif::use-maven[]
ifdef::use-gradle[]
Most of these subdirectories are Gradle projects and follow the standard Java directory structure:
endif::use-gradle[]

[plantuml]
----
@startsalt
{
{
T
quarkus-workshop-super-heroes
+  super-heroes
++ rest-villains
+++ src
++++  main
+++++  docker
+++++  java
+++++  resources
++++  test
+++++  java
}
}
@endsalt
----

include::introduction-preparing-checking-ports.adoc[leveloffset=+1]

== Ready?

After the prerequisites have been installed and the environment has been checked,  it's now time to write some code!

