@startuml
!include style.puml

left to right direction

node "Super Hero UI" as ui {
    agent "Quarkus" <<frontend>> as uiQuarkus
}

node "Hero" as hero {
    agent "Quarkus (reactive)" <<application>> as heroQuarkus
    database "Postgresql" as heroPostgresql
    heroQuarkus .up> heroPostgresql
}

node "Villain" as villain {
    agent "Quarkus (imperative)" <<application>> as villainQuarkus
    database "Postgresql" as villainPostgresql
    villainQuarkus .up> villainPostgresql
}

node "Fight" as fight {
    agent "Quarkus" <<application>> as fightQuarkus
    database "Postgresql" as fightPostgresql
    fightQuarkus .up> fightPostgresql
}

package "stats" {
    node "Statistics" as stat {
        agent "HTML+JQuery" <<frontend>> as statUI
        agent "Quarkus (imperative)" <<application>> as statQuarkus
        statUI .up> statQuarkus
    }

    node "Statistics UI" as statUi {
            agent "Browser" <<frontend>> as uiStats
    }
}

node "Kafka + Zookeeper" as kafka {
}

node "Prometheus" as prometheus {
}


uiQuarkus --> fightQuarkus : HTTP
fightQuarkus --> heroQuarkus : HTTP
fightQuarkus --> villainQuarkus : HTTP

fightQuarkus ..> kafka : Message
stat <.. kafka : Message
statQuarkus ..> uiStats : Web Sockets

prometheus .down.> fight : polling
prometheus  .> hero : polling
prometheus .> villain : polling
@enduml
