[[azure-intro-installing-wsl]]
= WSL

https://docs.microsoft.com/windows/wsl[Windows Subsystem for Linux] (WSL) lets developers run a GNU/Linux environment -- including most command-line tools, utilities, and applications -- directly on Windows, unmodified, without the overhead of a traditional virtual machine or dual-boot setup.

[WARNING]
====
If you are using Windows, it is recommended to install WSL.
====

== Installing WSL

You can install everything you need to run Windows Subsystem for Linux (WSL) by entering this command in an administrator PowerShell or Windows Command Prompt and then restarting your machine:

[source,shell]
----
wsl --install
----

This command will enable the required optional components, download the latest Linux kernel, set WSL 2 as your default, and install a Linux distribution for you (Ubuntu by default).

The first time you launch a newly installed Linux distribution, a console window will open and you'll be asked to wait for files to de-compress and be stored on your machine.
All future launches should take less than a second.
