[[quarkus-kubernetes]]
= From Container to Kubernetes

[NOTE]
====
This section is optional and demonstrates how to ask Quarkus to create a container and deploy it to Kubernetes.
We will need a running Kubernetes.
We will use Rancher Desktop as indicated in the prerequisites.
====

== Prerequisites

1. Make sure that Docker Desktop (if installed) is turned off
2. Make sure Rancher Desktop is started. The container runtime must be _dockerd_ (Preferences -> Container Runtime -> dockerd (moby)).

== Deploying to Kubernetes

Quarkus can also run our application in Kubernetes and compute the Kubernetes descriptor.
In addition to allow customizing any part of the descriptor, it is possible to configure config maps, secrets...

[IMPORTANT]
====
As mentioned above, we will use Rancher Desktop.
Adapt the instructions for your Kubernetes:

1. Make sure you are logged in
2. Make sure you use the correct namespace
====

[example, role="cta"]
--

Edit the `src/main/resources/application.properties` to add the following lines:

[source, properties]
----
quarkus.kubernetes.namespace=default # Added
quarkus.kubernetes.image-pull-policy=IfNotPresent # Added

%prod.quarkus.http.port=8080 # Added
%prod.quarkus.datasource.username=superbad
%prod.quarkus.datasource.password=superbad
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://my-villains-db-postgresql:5432/villains_database # Updated
%prod.quarkus.hibernate-orm.sql-load-script=import.sql
----

Add the `quarkus-kubernetes` extension using the following command:

[source, shell]
----
./mvnw quarkus:add-extension -Dextensions="kubernetes"
----
--

TIP: If you are behind a proxy, check the https://quarkus.io/guides/extension-registry-user#how-to-register-as-a-nexus-repository-proxy[Quarkus Registry] proxy documentation.

Alternatively, you can add the following dependency to the `pom.xml` file directly:

[source, xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-kubernetes</artifactId>
</dependency>
----

Rancher Desktop authentication use elliptic algorithms not supported by default in Java.
So, we also need to add the following dependency to the project:

[source, xml]
----
<dependency>
  <groupId>org.bouncycastle</groupId>
  <artifactId>bcpkix-jdk18on</artifactId>
  <version>1.71</version>
</dependency>
----

Before deploying our application, we need to deploy the database.
To achieve this, we are going to use https://helm.sh/[helm] (installed alongside Rancher Desktop) and the following https://artifacthub.io/packages/helm/bitnami/postgresql[postgresql package].

Run the following commands:
[source, shell]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install my-villains-db \
    --set auth.postgresPassword=superbad \
    --set auth.username=superbad \
    --set auth.password=superbad \
    --set auth.database=villains_database bitnami/postgresql
----

Finally, deploy the application using:

[source, shell]
----
./mvnw clean package -Dquarkus.kubernetes.deploy=true -DskipTests
----

Check the pods with the following command:

[source, shell]
----
kubectl get pods
----

You should see something like:

[source, shell]
----
NAME                             READY   STATUS    RESTARTS   AGE
my-villains-db-postgresql-0      1/1     Running   0          28m
rest-villains-7c7479b959-7fn64   1/1     Running   0          12m
----

Make sure you wait for the `rest-villains` pod to be ready (1/1).

Enable port-forwarding to port 8080 either from the rancher desktop UI (Preferences -> Port Forwarding -> default / rest-villains / http), or using the following command line:

[source, shell]
----
kubectl port-forward pods/rest-villains-7c7479b959-7fn64 8080:8080
----

Now, you can access the application from your browser using: http://localhost:8080/api/villains
