[[quarkus-container]]
= From Java to Container

This section demonstrates how to ask Quarkus to create a container.

== Building a container

Quarkus is able to build a container image automatically.
It proposes multiple approaches to do so, but we recommend using https://github.com/GoogleContainerTools/jib[jib].

The resulting image follows the container good practices such as the usage of layers, avoiding the `root` user...

[example, role="cta"]
--
Add the `quarkus-container-image-jib` extension using the following command:

[source, shell]
----
./mvnw quarkus:add-extension -Dextensions="jib"
----
--

It adds the following dependency to the `pom.xml` file:

[source, xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-container-image-jib</artifactId>
</dependency>
----

[example, role="cta"]
--
Then, launch the following command to build the application and create the container image:

[source, shell]
----
./mvnw clean package -Dquarkus.container-image.build=true
----

Once done, verify that the container image has been created using:

[source, shell]
----
docker images | grep villains
----

You should get a similar output:

[source, shell]
----
.../rest-villains              1.0.0-SNAPSHOT         1298cad04f5e   About a minute ago   388MB
----
--

== Building a container running a native executable

We've just created a container that embeds the Java application and a JVM.
But you can also build and use the native executable.
To do this, runs the following command:

[source, shell]
----
./mvnw clean package -Dquarkus.container-image.build=true -Pnative -Dquarkus.native.container-build=true
----

`-Dquarkus.native.container-build=true` is indicating that we need a Linux 64bits executable.
This option is not required if you use Linux.
