[[quarkus]]
= Quarkus

'''

In the previous chapter, you had a quick peek at Quarkus and how you can build HTTP / REST-based applications with it.
But that was just the beginning; Quarkus can do a lot more, which is the purpose of this chapter.
In this chapter, you are going to see:

* What's Quarkus? and how does it change the Java landscape
* What are the main Quarkus idea, and how it helps in the _cloud native world_
* The Quarkus build process, in other words, the _secret sauce number 1_
* The Quarkus reactive nature, in other words, the _secret sauce number 2_
* Some Quarkus features such as the application lifecycle support
ifdef::use-native[]
* How you can use Quarkus to generate native executable
endif::use-native[]

include::quarkus-definition.adoc[leveloffset=+1]

Quarkus does not stop there.
As you have seen in the previous chapter, it proposes a stellar developer experience.
It also unifies reactive and imperative to let you decide how you want to handle I/O. It allows implementing both REST and event-driven applications using a consistent model.
To do this, Quarkus is based on a reactive core allowing high concurrency and reducing memory consumption.

// TODO IMAGE

Quarkus detects if your method can be called on the I/O thread and follows the reactive execution model; or if your method must be called on a worker thread and follows the imperative execution model.

// TODO IMAGE

Ok, but enough talking, time to see this in action.
