quarkus.http.port=8067
quarkus.http.test-port=8068
# These paths are used in packaging, but not, apparently, in dev mode
quarkus.asciidoc.attributes.imagesdir=../../images
quarkus.asciidoc.attributes.assetsdir=../../assets
quarkus.asciidoc.attributes.imagesoutdir=../../lalala
quarkus.asciidoc.attributes.outdir=../../lalala
quarkus.asciidoc.attributes.plantDir=../plantuml
quarkus.asciidoc.attributes.plantuml-theme-dir=https://quarkus.io/assets/plantuml/themes
quarkus.asciidoc.attributes.projectdir=right
quarkus.asciidoc.attributes.options-file=right
quarkus.asciidoc.attributes."showtitle"=false
quarkus.asciidoc.attributes.add-copy-button-to-config-props=true
quarkus.asciidoc.attributes.add-copy-button-to-env-var=true
quarkus.asciidoc.attributes.icons=font
quarkus.asciidoc.attributes.source-highlighter=highlightjs
quarkus.qute.content-types.yaml=text/yaml
quarkus.qute.content-types.txt=text/plain
quarkus.qute.alt-expr-syntax=true
#quarkus.qute.property-not-found-strategy=NOOP
quarkus.qute.strict-rendering=false
quarkus.web-bundler.bundling.external=/assets/*
# Trailing slash works around https://github.com/quarkiverse/quarkus-web-bundler/issues/473
site.collections.versions.link=/version/:dir[1]/:name/
site.date-format=yyyy-MM-dd['T'HH:mm:ss][X]
%dev.site.draft=true
%dev.site.future=true
%test.site.draft=true
%test.site.future=true
site.url=https://quarkus.io/quarkus-workshops/super-heroes
site.ignored-files=**/_**,_**,**/!(.well\\\\-known)**.**
quarkus.roq.tagging.lowercase=true
quarkus.roq.generator.timeout=600
