[[reactive]]
= Reactive

'''

Quarkus combines the build time principle with a reactive core.
The combination of these two characteristics improves the application concurrency and makes use of resources more efficiently.
In this chapter, we will see the counterpart of the Villain microservice: the Hero microservice!
Instead of the imperative approach used for the villains, we will use reactive programming and Hibernate Reactive.
The logic of the microservice is the same.

[plantuml,align=center,width=300]
----
include::{plantDir}/3-reactive-physical-architecture.puml[]
----

In the following sections, you will learn:

* How to create a new reactive Quarkus application
* How to implement REST API using JAX-RS and the Quarkus REST extension using a reactive development model
* How to access your database using Hibernate Reactive with Panache
* How to use transactions the reactive way

IMPORTANT: This service is exposed on the port 8083.

== Why reactive?

"Reactive" is a set of principles to build _better_ distributed systems.
By following these principles, you create more elastic and resilient systems.

One of the central aspects of being reactive is about using non-blocking I/O to handle remote interactions efficiently.
With a few threads, your application can handle many concurrent I/Os.
A consequence of such usage is the need to implement applications that do not block these threads.
There are multiple approaches to do so, such as callbacks, co-routines, and reactive programming.

Quarkus encourages users to use Mutiny, an intuitive and event-driven reactive programming library.
In this section, we will cover the basics of Mutiny and implement an entirely reactive microservice.

== Hero Microservice

New microservice, new project!

The easiest way to create this new Quarkus project is to use the Quarkus Maven plugin.
Open a terminal and run the following command under the `quarkus-workshop-super-heroes/super-heroes` directory

[example, role="cta"]
--

[source,shell,subs="attributes+"]
----
./mvnw io.quarkus:quarkus-maven-plugin:{quarkus-version}:create \
    -DplatformVersion={quarkus-version} \
    -DprojectGroupId=io.quarkus.workshop.super-heroes \
    -DprojectArtifactId=rest-heroes \
    -DclassName="io.quarkus.workshop.superheroes.hero.HeroResource" \
    -Dpath="api/heroes" \
    -Dextensions="rest-jackson,quarkus-hibernate-validator,quarkus-smallrye-openapi,quarkus-hibernate-reactive-panache,quarkus-reactive-pg-client"
----
--

As you can see, we can select multiple extensions during the project creation:

* `rest-jackson` provides Quarkus REST and the ability to map JSON objects,
* `quarkus-hibernate-validator` provides the Hibernate Validator support,
* `quarkus-smallrye-openapi` provides the OpenAPI descriptor support and the Swagger UI in the dev console,
* `quarkus-hibernate-reactive-panache` provides Panache entity supports using Hibernate Reactive, an ORM using reactive database drivers,
* `quarkus-reactive-pg-client` provides the reactive database driver used by Hibernate Reactive to interact with PostGreSQL databases.

If you want your IDE to manage this new Maven project, you can declare it in the parent POM by adding this new module in the `<modules>` section:

[source,xml]
----
<module>super-heroes/rest-heroes</module>
----

=== Directory Structure

At the end of this chapter, you will end up with the following directory structure:

[plantuml]
----
@startsalt
{
{
T
super-heroes
+  rest-heroes
++  src
+++  main
++++  docker
+++++  ...
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  hero
++++++++++  Hero.java
++++++++++  HeroResource.java
++++  resources
+++++  META-INF
++++++  resources
+++++++  index.html
+++++  application.properties
+++++  import.sql
+++  test
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  hero
++++++++++  HeroResourceTest.java
++  mvnw
++  mvnw.cmd
++  pom.xml
}
}
@endsalt
----

=== The Hero entity

Let's start with the `Hero` entity class.

[example, role="cta"]
--

Create the `io.quarkus.workshop.superheroes.hero.Hero` class in the created project with the following content:

[source,java]
----
include::{projectdir}/rest-heroes/src/main/java/io/quarkus/workshop/superheroes/hero/Hero.java[tag=!adocJavadoc]
----
--

First, note that we are extending `io.quarkus.hibernate.reactive.panache.PanacheEntity`.
It's the reactive variant of `import io.quarkus.hibernate.orm.panache.PanacheEntity`.
As a consequence, methods are asynchronous, and instead of returning an object, they return asynchronous structure that will let you know when the object is ready to be consumed.

The field part is the same as for the Villain.
The `toString` method is also equivalent.

The major difference is the `findRandom` method.
Instead of returning a `Hero`, it returns a `Uni<Hero`.
A `Uni` represents an asynchronous action.
Unlike with the imperative development model, we cannot block the thread waiting for the result.
Here, we need to register a _continuation_ invoked when the result is available.
During that time, the thread is released and can be used to handle another request.

Let's split the `findRandom` method to better understand what's going on:

1. `count()` returns a `Uni<Long>` with the number of heroes stored in the database,
2. when this count is retrieved from the database, it transforms the result into a random number,
3. when this is computed, it chains the processing with another asynchronous action which retrieve the hero located at the random index.

As a consequence this method returns a `Uni<Hero>`.
The consumer will need to register a continuation to receive the `Hero`.

=== Uni API in 2 minutes

Uni comes from https://smallrye.io/smallrye-mutiny[Mutiny], an intuitive, event-driven reactive programming library.

There are a few method to understand to use `Uni`:

* `map` : transforms (synchronously) an item when this item becomes available.
* `chain`: transforms an item, when it become available, into another `Uni`. The outcome will be the outcome of the produced `Uni`.
* `replaceWith`: replaces an item with something else.
* `invoke`: invokes the method when the item becomes available. It does not modify the item.

NOTE: `Uni` is lazy. To trigger the computation you need to subscribe to it.
However, most of the time, Quarkus handles the subscription for us.

=== The Hero Resource

Unlike the `VillainResource`, the `HeroResource` uses the reactive development model.
It returns asynchronous structures (`Uni`)footnote:[There is another structure `Multi` to represent asynchronous streams of items. We will see `Multi` examples later].

[example, role="cta"]
--
Open the `HeroResource` and update the content to be:

[source,java]
----
include::{projectdir}/rest-heroes/src/main/java/io/quarkus/workshop/superheroes/hero/HeroResource.java[tag=!adocJavadoc]
----
--

The resource implements the same HTTP API as the villain counterpart.
It does not use a transactional service, but uses Panache method directly.

As you can see, instead of returning the result directly, it returns `Uni<T>`.
Quarkus retrieves the `Uni` and _waits_ for the outcome to be available before writing the response.
During that time, it can handle other requests.

Notice also the `@WithTransaction`, which is the reactive variant of `@Transactional`.

=== Configuring the reactive access to the database

Configuring the reactive access to the database is relatively similar to configuring the JDBC url.

[example, role="cta"]
--
Open the `application.properties` file and add:

[source,properties]
----
include::{projectdir}/rest-heroes/src/main/resources/application.properties[tag=!adocCORS]
----
--

The _prod_ profile contains the `%prod.quarkus.datasource.reactive.url` which configure the access to the database.

We also set the port to be 8083.

=== Importing heroes

[example, role="cta"]
--

Create the `src/main/resources/import.sql` and copy the content from {github-raw}/super-heroes/rest-heroes/src/main/resources/import.sql[import.sql].

[source,text]
----
ALTER SEQUENCE hero_seq RESTART WITH 50;

INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hero_seq'), 'Chewbacca', '', 'https://www.superherodb.com/pictures2/portraits/10/050/10466.jpg',
        'Agility, Longevity, Marksmanship, Natural Weapons, Stealth, Super Strength, Weapons Master', 5);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hero_seq'), 'Angel Salvadore', 'Angel Salvadore Bohusk',
        'https://www.superherodb.com/pictures2/portraits/10/050/1406.jpg',
        'Animal Attributes, Animal Oriented Powers, Flight, Regeneration, Toxin and Disease Control', 4);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hero_seq'), 'Bill Harken', '', 'https://www.superherodb.com/pictures2/portraits/10/050/1527.jpg',
        'Super Speed, Super Strength, Toxin and Disease Resistance', 6);
...
----
--

=== Testing the heroes

Time for some tests!
Open the `io.quarkus.workshop.superheroes.hero.HeroResourceTest` class and copy the following content:

[example, role="cta"]
--

[source,java]
----
include::{projectdir}/rest-heroes/src/test/java/io/quarkus/workshop/superheroes/hero/HeroResourceTest.java[]
----
--

The tests are very similar to the ones from the villain service.

== Running, Testing and Packaging the Application

[example, role="cta"]
--
First, make sure the tests pass by executing the command `./mvnw test` (or from your IDE).
--

Now that the tests are green, we are ready to run our application.

[example, role="cta"]
--

Use `./mvnw quarkus:dev` to start it.
Once the application is started, create a new hero with the following cUrl command:

[source,shell]
----
curl -X POST -d  '{"level":2, "name":"Super level", "powers":"leaping"}'  -H "Content-Type: application/json" http://localhost:8083/api/heroes -v
----

Thanks to the verbose mode (`-v`) you should see a similar output:

[source,shell]
----
< HTTP/1.1 201 Created
< Location: http://localhost:8083/api/heroes/952
----
--

The cUrl command returns the location of the newly created hero.
Take this URL and do an HTTP GET on it.

[NOTE]
====
The example shows a newly created Hero with id `952`.
But this id could be different on your machine.
Just make sure to use the correct id in the next command.
====

[source,shell]
----
curl http://localhost:8083/api/heroes/952 | jq
----

[source,json]
----
{
  "id": 952,
  "name": "Super level",
  "otherName": null,
  "level": 2,
  "picture": null,
  "powers": "leaping"
}
----

Remember that you can also check Swagger UI by going to the dev console: http://localhost:8083/q/dev.

[example, role="cta"]
--

Then, build the application using: `./mvnw package`, and run the application using `java -jar target/quarkus-app/quarkus-run.jar`.
Open your browser and go to http://localhost:8083/api/heroes.
--

