[[quarkus-native]]
= From Java to Native

== Building a Native Executable

Let's now produce a native executable for our application.
As explained in the introduction of this chapter, Quarkus can generate native executables.
Just like Go, native executables don't need a VM to run; they contain the whole application, like an `.exe` file on Windows.

It improves the startup time of the application and produces a minimal disk footprint.
The executable would have everything to run the application, including the "JVM" (shrunk to be just enough to run the application), and the application.

[NOTE]
--
Choosing JVM execution vs. native executable execution depends on your application needs and environment.
--

To do so, you will find in the `pom.xml` the following profile:

[source,xml]
----
<profile>
  <id>native</id>
  <activation>
    <property>
      <name>native</name>
    </property>
  </activation>
  <properties>
    <skipITs>false</skipITs>
    <quarkus.package.type>native</quarkus.package.type>
  </properties>
</profile>
----

Make sure you have the `GRAALVM_HOME` environment variable defined and pointing to where you installed GraalVM.

[example, role="cta"]
--
Then create a native executable using: `./mvnw package -Pnative`.
In addition to the regular files, the build also produces `target/rest-villains-1.0.0-SNAPSHOT-runner` (notice that there is no `.jar` file extension).
You can run it using `./target/rest-villains-1.0.0-SNAPSHOT-runner` and curl the endpoint with `curl http://localhost:8084/api/villains`.
--

[WARNING]
====
Creating a native executable requires a lot of memory and CPU.
It also takes a few minutes, even for a simple application like the Villain microservice.
Most of the time is spent during the dead code elimination, as it traverses the whole (closed) world.
====

