[[quarkus-kubernetes]]
= From Java to Kubernetes

[NOTE]
----
This section is optional and demonstrates how to ask Quarkus to create a container and deploy it to Kubernetes.
We will need a running Kubernetes.
We will use Rancher Desktop as indicated in the prerequisites.
----

== Prerequisites

1. Make sure that Docker Desktop (if installed) is turned off
2. Make sure Rancher Desktop is started. The container runtime must be _dockerd_ (Preferences -> Kubernetes Settings).

== Building a container

Quarkus is able to build a container image automatically.
It proposes multiple approaches to do so, but we recommend using https://github.com/GoogleContainerTools/jib[jib].

The resulting image follows the container good practices such as the usage of layers, avoiding the `root` user...

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

Add the `quarkus-jib` extension using the following command:

[source, shell]
----
$ mvn quarkus:add-extension -Dextensions="jib"
----

It adds the following dependency to the `pom.xml` file:

[source, xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-container-image-jib</artifactId>
</dependency>
----

Then, launch the following command to build the application and create the container image:

[source, shell]
----
$ mvn clean package -Dquarkus.container-image.build=true
----

Once done, verify that the container image has been created using:

[source, shell]
----
$ docker images | grep villains
.../rest-villains              1.0.0-SNAPSHOT         1298cad04f5e   About a minute ago   388MB
----

== Building a container running a native executable

In the previous section, the container embeds the Java application.
You can also build and use the native executable.
To do this, runs the following command:

[source, shell]
----
$ mvn clean package -Dquarkus.container-image.build=true -Pnative -Dquarkus.native.container-build=true
----

`-Dquarkus.native.container-build=true` is indicating that we need a Linux 64bits executable.
This option is not required is you use Linux.


== Deploying to Kubernetes

Quarkus can also run our application in Kubernetes and compute the Kubernetes descriptor.
In addition to allow customizing any part of the descriptor, it is possible to configure config maps, secrets...

[IMPORTANT]
----
As mentioned above, we will use Rancher Desktop.
Adapt the instructions for your Kubernetes:

1. Make sure you are logged in
2. Make sure you use the correct namespace
----

icon:hand-point-right[role="red", size=2x] [red big]#Call to action#

Edit the `src/main/resources/application.properties` to add the following lines:

[source, properties]
----
quarkus.kubernetes.namespace=default # Added
quarkus.kubernetes.image-pull-policy=IfNotPresent # Added

%prod.quarkus.http.port=8080 # Added
%prod.quarkus.datasource.username=superbad
%prod.quarkus.datasource.password=superbad
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://my-villains-db-postgresql:5432/villains_database # Updated
%prod.quarkus.hibernate-orm.sql-load-script=import.sql
----

Add the `quarkus-kubernetes` extension using the following command:

[source, shell]
----
$ mvn quarkus:add-extension -Dextensions="kubernetes"
----

Rancher Desktop authentication use elliptic algorithms not supported by default in Java.
So, we also need to add the following dependency to the project:

[source, xml]
----
<dependency>
  <groupId>org.bouncycastle</groupId>
  <artifactId>bcpkix-jdk18on</artifactId>
  <version>1.71</version>
</dependency>
----

Before deploying our application, we need to deploy the database.
To achieve this, we are going to use https://helm.sh/[helm] (installed alongside Rancher Desktop) and the following https://artifacthub.io/packages/helm/bitnami/postgresql[postgresql package].

Run the following commands:
[source, shell]
----
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install my-villains-db \
    --set auth.postgresPassword=superbad \
    --set auth.username=superbad \
    --set auth.password=superbad \
    --set auth.database=villains_database bitnami/postgresql
----

Finally, deploy the application using:

[source, shell]
----
$ mvn clean package -Dquarkus.kubernetes.deploy=true -DskipTests
...
$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
my-villains-db-postgresql-0      1/1     Running   0          28m
rest-villains-7c7479b959-7fn64   1/1     Running   0          12m
----

Make sure you wait for the `rest-villains` pod to be ready (1/1).

Enable port-forwarding either from the rancher desktop UI (preferences -> port forwarding -> default / rest-villains / http), or using the following command line:

[source, shell]
----
$ kubectl port-forward pods/rest-villains-7c7479b959-7fn64 8080:8080
----

Now, you can access the application from your browser using: http://localhost:$PORT/api/villains
