@startuml
!include style.puml

left to right direction

node "Villain" as villain {
    agent "Quarkus (imperative)" <<application>> as villainQuarkus
    database "Postgresql" as villainPostgresql
    villainQuarkus .up> villainPostgresql
}

REST ()-- villainQuarkus

@enduml
