/**
 * Fight API
 * This API allows a hero and a villain to fight
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { InlineResponse200Hero } from './inlineResponse200Hero';
import { InlineResponse200Villain } from './inlineResponse200Villain';


/**
 * A fight between one hero and one villain
 */
export interface Fighters { 
    hero: InlineResponse200Hero;
    villain: InlineResponse200Villain;
}