name: Surge.sh Preview Teardown

on:
  pull_request_target:
    types: [ closed ]

jobs:
  preview-teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Teardown surge preview
        id: deploy
        run: npx surge@0.23.1 teardown https://quarkus-workshops-pr-${{ github.event.number }}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }} || echo "NOT_TORNDOWN=true" >> "$GITHUB_ENV"
      - name: Update PR status comment
        uses: quarkusio/action-helpers@main
        if: env.NOT_TORNDOWN != 'true'
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🙈 The PR is closed and the preview is expired.
          body-marker: '<!-- Sticky Pull Request Comment -->'
          pr-number: ${{ github.event.number }}

