[[introduction-installing-jdk]]

= JDK {jdk-version}

Essential for the development and execution of this workshop is the _Java Development Kit_ (JDK).footnote:[Java http://www.oracle.com/technetwork/java/javase]
The JDK includes several tools such as a compiler (`javac`), a virtual machine, a documentation generator (`JavaDoc), monitoring tools (Visual VM) and so onfootnote:[Visual VM https://visualvm.github.io].
The code in this workshop is based on JDK {jdk-version}, but any JDK version higher will work as well.

== Installing the JDK

There is an easier way to download and install Java: using https://sdkman.io/[SDKMAN!].

=== Installing SDKMAN!

Installing SDKMAN! is easy.
On Bash and ZSH shells simply open a new terminal and enter:

[source,term]
----
$ curl -s "https://get.sdkman.io" | bash
----

Follow the instructions on-screen to complete installation.

=== Listing Java Versions

To install Java, we need to list the available versions on SDKMAN! using the `list` command.
The result is a table of entries grouped by the vendor and sorted by version:

[source,term]
----
$ sdk list java

==========================================================================
Available Java Versions for macOS ARM 64bit
==========================================================================
Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------
Corretto      |     | 19.0.1       | amzn    |            | 19.0.1-amzn
....
Microsoft     |     | 17.0.5       | ms      |            | 17.0.5-ms
...
Oracle        |     | 19.0.1       | oracle  |            | 19.0.1-oracle
...
Temurin       | >>> | 25.0.2       | tem     | installed  | 25.0.2-tem
              | >>> | 17.0.19      | tem     | installed  | 17.0.19-tem
==========================================================================
----

If you have any Java candidate installed, you should see `installed` in the `Status` column.
If you don't have any Java candidate installed, use SDKMAN! to install one or several.

=== Installing Java {jdk-version}

There are several different vendors of Java, and each vendor has its own distribution.
Most of these distributions are available on SDKMAN! and can easily be installed.
Let's install Temurin.

To install Temurin {jdk-version}, we copy its identifier (`{jdk-version}-tem`), which is the version from the table, and we add it as an argument in the install command:

[source,term,subs="attributes+"]
----
$ sdk install java {jdk-version}.x-tem
----

== Checking for Java Installation

Once the installation is complete, it is necessary to set the `JAVA_HOME` variable and the `$JAVA_HOME/bin` directory to the `PATH` variable.
Check that your system recognizes Java by entering `java -version` and the Java compiler with `javac -version`.

[source,shell,subs="attributes+"]
----
$ java -version
openjdk version "17.0.19" 2025-10-21
OpenJDK Runtime Environment Temurin-17.0.19+10 (build 17.0.19+10)
OpenJDK 64-Bit Server VM Temurin-17.0.19+10 (build 17.0.19+10, mixed mode, sharing)
ifdef::use-native[]
openjdk 25.0.2 2026-01-20
OpenJDK Runtime Environment GraalVM CE 25.0.2+10.1 (build 25.0.2+10-jvmci-b01)
OpenJDK 64-Bit Server VM GraalVM CE 25.0.2+10.1 (build 25.0.2+10-jvmci-b01, mixed mode, sharing)
endif::use-native[]

$ javac -version
javac 17.0.19
----
