[[introduction-installing-jdk]]

= JDK {jdk-version}

Essential for the development and execution of this workshop is the _Java Development Kit_ (JDK).footnote:[Java http://www.oracle.com/technetwork/java/javase]
The JDK includes several tools such as a compiler (`javac`), a virtual machine, a documentation generator (`JavaDoc), monitoring tools (Visual VM) and so onfootnote:[Visual VM https://visualvm.github.io].
The code in this workshop uses JDK {jdk-version}.

== Installing the JDK

To install the JDK {jdk-version}, follows the instructions from https://adoptium.net/installation.html to download and install the JDK for your platform.

ifdef::use-mac[]
There is also an easier way to download and install Java if you are on Mac OS X: using SDKMAN!.
_SDKMAN!_{wj}footnote:[SDKMAN! https://sdkman.io] is a tool for managing parallel versions of multiple Software Development Kits (SDK) on most Unix based systems.
It provides a convenient Command Line Interface (CLI) and API for installing, switching, removing and listing _Candidates_.
Developers often need to manage parallel versions of different builds of SDKs in their environment and switch from one to another.
Manually setting the `PATH` variable can become quickly painful.
That's when SDKMAN! can help you.

=== Installing SDKMAN!

Installing SDKMAN! is easy.
On Bash and ZSH shells simply open a new terminal and enter:

[source,term]
----
$ curl -s "https://get.sdkman.io" | bash
----

Follow the instructions on-screen to complete installation.

=== Listing Java Versions

To install Java, we need to list the available versions on SDKMAN! using the `list` command.
The result is a table of entries grouped by the vendor and sorted by version:

[source,term]
----
$ sdk list java

==========================================================================
Available Java Versions for macOS ARM 64bit
==========================================================================
Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------
Corretto      |     | 19.0.1       | amzn    |            | 19.0.1-amzn
....
Microsoft     |     | 17.0.5       | ms      |            | 17.0.5-ms
...
Oracle        |     | 19.0.1       | oracle  |            | 19.0.1-oracle
...
Temurin       |     | 19.0.1       | tem     |            | 19.0.1-tem
              | >>> | 17.0.5       | tem     | installed  | 17.0.5-tem
              |     | 11.0.17      | tem     | installed  | 11.0.17-tem
==========================================================================
----

If you have any Java candidate installed, you should see `installed` in the `Status` column.
If you don't have any Java candidate installed, use SDKMAN! to install one or several.

=== Installing Java {jdk-version}

There are several different vendors of Java, and each vendor has its own distribution.
Most of these distributions are available on SDKMAN! and can easily be installed.
Let's install Temurin.

To install Temurin {jdk-version}, we copy its identifier (`{jdk-version}-tem`), which is the version from the table, and we add it as an argument in the install command:

[source,term,subs="attributes+"]
----
$ sdk install java {jdk-version}-tem

Downloading: java {jdk-version}-tem
Repackaging Java {jdk-version}-tem...
Installing: java {jdk-version}-tem
Done installing!

Do you want java {jdk-version}-tem to be set as default? (Y/n):
----
endif::use-mac[]

ifdef::use-linux[]
For Linux distributions, there are also packaged java installations.
[source,shell,subs="attributes+"]
----
# dnf (rpm-based)
dnf install java-{jdk-version}-openjdk
# Debian-based distributions:
$ apt-get install openjdk-{jdk-version}-jdk
----
endif::use-linux[]

== Checking for Java Installation

Once the installation is complete, it is necessary to set the `JAVA_HOME` variable and the `$JAVA_HOME/bin` directory to the `PATH` variable.
Check that your system recognizes Java by entering `java -version` and the Java compiler with `javac -version`.

[source,shell]
----
$ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

$ javac -version
javac 17.0.5
----
