[[introduction-installing-graalvm]]

= GraalVM {graalvm-version}

GraalVM extends the _Java Virtual Machine_ (JVM) to support more languages and several execution modes.footnote:[GraalVM https://www.graalvm.org]
It supports a large set of languages:
Java of course, other JVM-based languages (such as Groovy, Kotlin etc.) but also JavaScript, Ruby, Python, R and C/C++.
It includes a high-performance Java compiler, which can be used in a _Just-In-Time_ (JIT) configuration on the HotSpot VM or in an _Ahead-Of-Time_ (AOT) configuration with the GraalVM native compiler.
One objective of GraalVM is to improve the performance of Java virtual machine-based languages to match the performance of native languages.

== Prerequisites for GraalVM

ifdef::use-linux[]
On Linux, you need GCC and the Glibc and zlib headers.
Examples for common distributions:

[source,shell]
----
# dnf (rpm-based)
sudo dnf install gcc glibc-devel zlib-devel
# Debian-based distributions:
sudo apt-get install build-essential libz-dev zlib1g-dev
----
endif::use-linux[]

ifdef::use-mac[]
On macOS X there are several ways to install GraalVM.
But using SDKMAN! is the preferred option, as it allows you to easily switch between different versions of GraalVM if needed.
endif::use-mac[]

ifdef::use-windows[]
On Windows, you need the _Developer Command Prompt for Microsoft Visual C++_.
Check the https://www.graalvm.org/docs/getting-started/windows/#prerequisites-for-using-native-image-on-windows[Windows prerequisites page] for details.
endif::use-windows[]

== Installing GraalVM

ifndef::use-mac[]
GraalVM is installed from the GraalVM project.footnote:[GraalVM Download https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-{graalvm-version}].

Version {graalvm-version} is required.
Select the {jdk-version} version.

Follow the installation instructions:

ifdef::use-linux[]
- Linux - https://www.graalvm.org/{graalvm-version}/docs/getting-started/linux/
endif::use-linux[]
ifdef::use-windows[]
- Windows - https://www.graalvm.org/{graalvm-version}/docs/getting-started/windows/
endif::use-windows[]
endif::use-mac[]


ifdef::use-mac[]
=== Listing GraalVM Versions

First of all, check if you already have the GraalVM Candidates installed on your machine.
To list the available versions of GraalVM, use the SDKMAN! `list java` command.
The result is a table of entries grouped by the vendor and sorted by version.
GraalVM has its own group and is listed under the `GraalVM` vendor:

[source,term]
----
$ sdk list java

=======================================================================
Available Java Versions for macOS ARM 64bit
=======================================================================
Vendor        | Use | Version      | Dist    | Status  | Identifier
-----------------------------------------------------------------------
GraalVM       |     | 22.3.r19     | grl     |         | 22.3.r19-grl
              |     | 22.3.r17     | grl     |         | 22.3.r17-grl
              |     | 22.3.r11     | grl     |         | 22.3.r11-grl
              |     | 22.2.r17     | grl     |         | 22.2.r17-grl
              |     | 22.2.r11     | grl     |         | 22.2.r11-grl
              |     | 22.1.0.r17   | grl     |         | 22.1.0.r17-grl
              |     | 22.1.0.r11   | grl     |         | 22.1.0.r11-grl
=======================================================================
----

If you have any GraalVM candidate installed, you should see `installed` in the `Status` column.
If you don't have any GraalVM candidate installed, use SDKMAN! to install one or several.

=== Installing a GraalVM Version

There are several versions of GraalVM available for different versions of the JDK.
Because we are using Java {jdk-version} in this fascicle, we will install the version of GraalVM that is compatible with Java {jdk-version} (the versions finishing with `r{jdk-version}-grl`).
Let's install GraalVM {graalvm-version}.

[source,term,subs="attributes+"]
----
$ sdk install java {graalvm-version}.r{jdk-version}-grl

Downloading: java {graalvm-version}.r{jdk-version}-grl
Repackaging Java {graalvm-version}.r{jdk-version}-grl...
Installing: java {graalvm-version}.r{jdk-version}-grl
Done installing!

Do you want java {graalvm-version}.r{jdk-version}-grl to be set as default? (Y/n):
----
endif::use-mac[]

Once installed, define the `GRAALVM_HOME` environment variable to point to the directory where GraalVM is installed (eg. on Mac OS X it could be `~/.sdkman/candidates/java/{graalvm-version}.r{jdk-version}-grl`).

The `native-image` tool must be installed.
It can be done by running the following command under `$GRAALVM_HOME/bin`

[source,shell]
----
./gu install native-image
----

from your GraalVM `bin` directory.

ifdef::use-mac[]
[NOTE]
.Mac OS X - Catalina
====
On Mac OS X Catalina, the installation of the `native-image` executable may fail.
GraalVM binaries are not (yet) notarized for Catalina.
To bypass the issue, it is recommended to run the following command instead of disabling macOS Gatekeeper entirely:

[source,shell]
-----
xattr -r -d com.apple.quarantine ${GRAAL_VM}
-----
====
endif::use-mac[]

== Checking for GraalVM Installation

Once installed and set up, you should be able to run the following command and get something like the following output.

[source,shell]
----
$ $GRAALVM_HOME/bin/native-image --version
----

You should get something like:

[source,shell]
----
GraalVM 22.3.1 Java 17 CE (Java Version 17.0.6+10-jvmci-22.3-b13)
----

